"""R3 prompt builder (box side) for the GRPO smoke kernel
(pre-reg kaggle/PREREG-RL-READINESS.md, R3).

Prompts are the REAL arm-B editcap prompts (editcap_run.build_prompt_B, k=1
edit per completion so that one completion = one candidate = one reward) built
from the OLD gf180-era failure library kaggle/editcap-lib-v1a (27 cells,
non-bench). The kernel renders them with the Qwen3 chat template
(enable_thinking=False).

Held-out fence (pre-reg): refuses any bench-v1.2 cell (kaggle/editcap-lib-v12-*)
and any claude-solutions/templates text.

Writes prompts.json next to this file AND embeds it (zlib+base64) into
kernel.py between the PROMPTS markers.

    python kaggle/kernels-editcap/rl-readiness-r3-grpo/build_prompts.py
"""
import base64
import glob
import json
import os
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "kaggle"))
import editcap_run as E                                             # noqa: E402
from spec import Spec                                               # noqa: E402

LIB_REL = os.path.join("kaggle", "editcap-lib-v1a")
LIB = os.path.join(ROOT, LIB_REL)
K = 1


def fence_sets():
    held = set()
    for d in glob.glob(os.path.join(ROOT, "kaggle", "editcap-lib-v12-*")):
        held |= set(os.listdir(d))
    tmpl = []
    for f in glob.glob(os.path.join(ROOT, "kaggle", "claude-solutions", "templates",
                                    "**", "*"), recursive=True):
        if os.path.isfile(f):
            try:
                t = open(f, encoding="utf-8").read().strip()
            except Exception:
                continue
            if len(t) > 40:
                tmpl.append(t)
    return held, tmpl


def main():
    held, tmpl = fence_sets()
    rows = []
    for cell in sorted(os.listdir(LIB)):
        d = os.path.join(LIB, cell)
        if not os.path.isdir(d):
            continue
        assert cell not in held, "FENCE: %s is a bench-v1.2 cell" % cell
        anchor = open(os.path.join(d, "anchor.net"), encoding="utf-8").read()
        ev = json.load(open(os.path.join(d, "evidence.json"), encoding="utf-8"))
        spec = Spec.load(os.path.join(d, "spec.yaml"))
        messages, _ = E.build_prompt_B(spec, anchor, ev, K)
        for t in tmpl:
            assert t not in messages[1]["content"], "FENCE: template text in %s" % cell
        rows.append(dict(cell=cell, source_lib="editcap-lib-v1a", k=K,
                         spec_rel=os.path.join(LIB_REL, cell, "spec.yaml"),
                         anchor_rel=os.path.join(LIB_REL, cell, "anchor.net"),
                         system=messages[0]["content"], user=messages[1]["content"]))
    out = os.path.join(HERE, "prompts.json")
    json.dump(rows, open(out, "w"), indent=1)
    blob = base64.b64encode(zlib.compress(json.dumps(rows).encode(), 9)).decode()
    kp = os.path.join(HERE, "kernel.py")
    src = open(kp, encoding="utf-8").read()
    a, b = "# >>> PROMPTS (generated by build_prompts.py)\n", "# <<< PROMPTS\n"
    i, j = src.index(a) + len(a), src.index(b)
    src = src[:i] + 'PROMPTS_B64 = "%s"\n' % blob + src[j:]
    open(kp, "w", encoding="utf-8").write(src)
    print("prompts=%d  user chars mean=%.0f  blob=%d B"
          % (len(rows), sum(len(r["user"]) for r in rows) / len(rows), len(blob)))


if __name__ == "__main__":
    main()
