"""rl-readiness R3 -- GRPO smoke of Qwen3-14B LoRA on Kaggle T4.

Pre-reg: kaggle/PREREG-RL-READINESS.md section R3 (frozen 2026-09-28).
Question: does TRL GRPOTrainer (via unsloth) run Qwen3-14B 4-bit LoRA on ONE T4
at group size G >= 4 (target 8) with completions >= 1024 tokens, with a REAL
reward (netlist round-trip on every rollout + in-kernel SPICE sizing on a few)?
Decision rule: "GRPO-on-Kaggle feasible" if a G>=4, >=1024-token step completes
without OOM; report rollouts/GPU-h and the implied architecture-B round size.

Flow (every phase time-guarded, R3_BUDGET_MIN total):
  0. env log: nvidia-smi, nproc / os.cpu_count / CPU model, RAM, disk.
  1. clone the repo PINNED at REPO_SHA (circuit-repro-ghtoken dataset) +
     kaggle/bootstrap.sh (ngspice 47 from the circuit-repro-ngspice47 dataset).
  2. CLEAN in-kernel SPICE timing (nothing else running): smoke_run
     (kaggle/bench_anchor_prep.py) of v1a anchors at 1 seed x 300 evals, pdk
     bptm45 -- serial, stability-gated, 1x600, and nproc-parallel.
  3. pip-install the E-e unsloth stack (torch untouched via constraints);
     pre-download the model; in the BACKGROUND build a --system-site-packages
     venv with vllm (torch-2.10-compatible release) for unsloth fast_inference.
  4. GRPO trials, each its own subprocess on ONE T4 (CUDA_VISIBLE_DEVICES), two
     GPUs = two parallel trial queues:
       H-G8-L1024  HF generation, G=8, 1024 forced tokens, 3 steps (MAIN)
       H-G4-L1024  HF generation, G=4 (fallback point / G scaling)
       V-*         unsloth fast_inference (vLLM colocated) when the venv is ready
       H-G8-L2048, H-G16-L1024  OOM-boundary probes (only if the MAIN passed)
     "forced" = min_new_tokens = max_completion_length (EOS suppressed), so every
     step is a true >=1024-token step (worst case for memory and time).
     Rewards: reward_valid (proposal.round_trip, every rollout), reward_novel
     (WL hash != anchor), reward_spice (smoke_run 1x300 bptm45 on up to
     N_SPICE valid+novel rollouts per step, parallel CPU pool; 0 for the rest).
  5. summary.json; big files stay in /tmp; ngspice prefix removed from output.

Prompts: real arm-B editcap prompts (k=1) from the OLD library
kaggle/editcap-lib-v1a (non-bench), embedded below (build_prompts.py). The
kernel re-checks the held-out fence against the clone's editcap-lib-v12-*.
"""
import base64
import glob
import json
import os
import re
import shutil
import subprocess
import sys
import threading
import time
import zlib

T0 = time.time()
WORK = "/kaggle/working"
OUT = os.path.join(WORK, "r3")
TMP = "/tmp/r3"
PY = sys.executable
BUDGET_MIN = float(os.environ.get("R3_BUDGET_MIN", "75"))
MIN_TRIAL_START_MIN = 16      # do not start a trial with less than this left

REPO_SLUG = "Devavavava/circuit-repro"
REPO_BRANCH = "worktree-externals-gf180"
REPO_SHA = "519bcf452c27cddf9e460b3d4a212ceacaf7e0c5"   # PREREG rl-readiness commit
CLONE = "/tmp/circuit-repro"
ENV_SH = os.path.join(WORK, "env-kaggle.sh")
PDK = "bptm45"
SPICE_BUDGET = 300
SPICE_CELLS = ["bnl-09-gain-g0", "bnl-1575-lown-n0", "bnl-24-powe-p0", "bnl-35-diag-t4"]

MODEL = "unsloth/Qwen3-14B-unsloth-bnb-4bit"
PINS = [
    "unsloth==2026.9.11",
    "unsloth_zoo==2026.9.7",
    "transformers==5.5.0",
    "trl==0.24.0",
    "peft==0.21.0",
    "bitsandbytes==0.50.2",
    "accelerate==1.15.0",
    "datasets==4.3.0",
]
# vLLM for fast_inference: the newest release pinned to torch==2.10.0 is 0.19.1;
# it needs transformers <5 or >=5.5.1, unsloth needs <=5.5.0 -> 4.57.6 (allowed
# by both). Installed ONLY into a --system-site-packages venv so the main stack
# (transformers 5.5.0, as E-e) is untouched.
VLLM_PINS = ["vllm==0.19.1", "transformers==4.57.6"]
VENV = os.path.join(TMP, "venv-vllm")

# >>> PROMPTS (generated by build_prompts.py)
PROMPTS_B64 = "eNrtnftTGzmewP8VVX64hVvc0ftBNndFDDOTW4akgJnduWVr1uAGXDE2ZZtkM1t7f/t9pX67JQMB27tGqXnE3S116yu1Wp/vS3/5x6uLdDh8tYtenY+GHWw6/UHvqjPDr3bQq+n4bnKR/jocnNvzaX8wu+jdduBn5zPp2Qs+wXFiL7xNL36dpK6aT72rq2H6eu7q183aX9sSydfezdBW0xtdXI8nj6sgK5OM0pl70q/TWXpjS/8yvkO9SYp6I/inNxxfofdd1E+ng6tROkGT9LY3mAxGV6iHhuMvndF4MIVrb26Hg8sBnN86PNrbRrPr3gx9t/f+8GAfDWZTZB8Wzl/0ZoMxVHs5gysv74ZDdPLxffcATQe/QY0JsreepL2pveZ8fDeDelJ02RsM79zz9NHtZHw7hvudnB7/1D396XjvEG3N4BA85ddtdHHdG12l06weKH4LNZx++Pjh8MP3v6APR4e/oN4UHnt604M7DwejtDOeDNLRLO0jkMJwMJ29gdP98ZfRdAaPcQOthge9GYzgzOACzcbjIRqMpukEWnQ+6E2dFOCp4PHTKUo/p5OvUOTz4CJFXwaza6gra974dja4gWsmCTqyV0Eln+G2xbWfe8O7dLqD9rsoGy/w9/HE3cE+15fx5NMUdTpoPBp+dRK5GI9G6cVs8Hkw+5rYzruDZ7Jd9/btW7jlQRdtNft6G8GZsxF04sVkcGv7YBcVo+M8hXEA4wNBxyGD8c31b8gWQzPozl2EE0ME+v6H39z5rRNK/ustoejouz+8ZQlG7/v9P7wlGJ0Q8oe3HYK3z0bnIJJdNOpNJuMv9u876BK/hUqw+wNlfvjtbHTVs1KHhoCke4PRbLp7NkJodPlr/xy5Pze9vyNmj00JKQ7aY3APd5RWRwcjRKg9OOj3f73plZfaK89GViZ7R90fPhyjo4PTw/cnpzBk8mFlH2EwubgbzHZsm4cgVHQ5ntzk8vrb3/6Wj4uz0X+i4ajX6ZHOYNTvp1fpqHPRm16M++ku9Gb/zvZGOvzacafSSda67ALUPbGyS2wdhzDoeldQ5uS6l15ewlD4D3SYpjvo7NUeIono/Lzj/mfl3f3xAxQcf0FH7hXbK16xs1c7tqr/OTnpImKMStC7oguzV/oNgjF2Dq/aDRpfugEDrw0MOPQZJxSlf4cxDe81uiC2mq3J+G7U75Dy+A76MkT9i35PYGJIX12IVDF4KvyacnR1STRGxRuHLiZ2FG27pp3MJiAFeFE7dpzuoP89OP4AHXxzOx7ZsZ4N8gR9vDsHgV6DeN693zuxXfKnD8d/BBl2ilp3bW0Xd5MJFOvcDGAY2VkHZAWtTNHWMUGd/4LespI9+pFto8s07U9dMwcj+8bboQU/oV1X1+iYvrHVZWf2u53z4fjiE9x8q0u235Q95IrAjPXz/j7a2uuiKyeUrF17t056fUQxlfadIhxeLytx5K6y0/fZq152FYKZ5eyVLdhFXYJ+fn9E0AiG4SE6tH9BI5D5ke3Xox/hN4XfaMTQzycn7hJa/sivgQPcPRRcWlzEsgPc3SK74MNPp1DvMQLRuHOirIDBD/sPFM4qgIuoO0bc8C5eEDtV/3R8gA5+fr9/cARTFrwig2nxcqAvMBPZSa7vprsf35+cHOzn78g5jH47D27BNDWdbdde6d3y1b3pTa4Go7cdnEippEZbI3jHekNb4RuY4UD68PJAde6dhMpgErmEr8DgfAhvyne9IYx+BINuBoM2+1LAXAtH7VfF3oZQ7N7023TSqW6f33WKtnoX14PU9uDnqevpHVTdP79q200/N+lsAvO8/VOWKWYjexUq/kzvbm/HE3jH5yYtmhgFk2PxByY7bGT583Ryl87NaB2WMMrKEqWE5gpUk51KMOEE1QpwIrihzQK1iZDAQxCYwasCuPY7K3A2gml8t2pzUeZmr95VhRDyKrip/mjOrXDdO5jdGr4sza4d2+/e+V3/KnXzBfSw/fy7QQWfoOksFz50VzF52T75h23N2atMYmfwicsFtlMdh5m+dg6EUZyjRZlMZrXD8MXIT0n4ujGZn8oe3R7OBZAfdx1sD2fdW1ZEi/vqRDGma8drz6QTmEdF+bxlGWESonBR6NOvl9geNiwx2qjyKDypO4wTpkxRy81dfjVNFIyv6mh+NU0kk7XD08lFXoAkXJLmibyMPZOf6KfDWS8vAB8MgVXjBLStOKNKoc5657/ab70985cz96IYTIsv/k5+hOriiD3w11qPwKrkdpjmssEgGcMq4cPIuB67quHiFFZs018n07NXZ6N/2nH0y4efjtHp3skf4UWf3KB3dtiQBO2/3/v+6MPJQWMJCaMXpqn+dBd9sQtUmOFur79OYVk6hJXVENZoMzu52BLFtFabT6CwW3zlcyIsUD+n/302ovBNy1elB3/e657CKpPU16f2Czm1C8/vfjo8LNaZ06K2YtVxnsJiOkEH8A66EvbZeu7zOYQ1aFHMvo4zu0QdXF5u76DUXj3Nv7uuDfvvv/vu4Pjg6BRdTsY37g7ZmsBN3OWxMfxnkj0ZvIssQXtuRX6w1/3BHd2BWt0nEX08Pth/3z2FZXx/MLFrTlia7x3tw1xwNRrM7uDbCeulhsTySXQrTWBB/7t8rhvcuM8jLJu/ov9jqP/ud9kkcAAiz5qRNXrkaOHDn47gqw5f+z6qlmDIfbpdqWIdB318eNCF9dz4PP0KC5jexcyuPGDBUSyt4ZPgFvrZ/H76y8cDWJjegDzhq0/cfyn6i/0fcz/4X8vL4FH+YT+iO+ij++/xDuruoMN/JvYKe+K1PY5mvU8p4q6w61MYXXDLffQ9OkHv3qDj193Xh9lFNL/oIzrK6khh0ZutELbc8gQ61H3JoTkOXezv/f0d9+3eylckwCejr3CffAlna8wa5Hr0C6wTATE+NMHCHfm5QAv3q4EWyat/7qAAxJKlQix5KsSSCLEvBmLJc0MsdxBLE5FBrF4Ow0L9D6dY7qFY/fwQK2CZfHMzdg3YRdnfO46BMk5yQiKvr27Q+WTc61sBwKPMLq5hSjqEF6bXnzZptl6FLddxV9t6dtDecDiFtXtnCi/qOBuxUCb/PpT12+q639sSMG5Ou3snrx3fdr/vZI902bsZDL9ut1h3B+TxJwTyH5WjwjbeVlc9+2v3kru/Xth1KNw/eSCvNsh21z6iJTf3Ylj5n8DiA96NXp0/LRnkU3qdOAEHf29ry96OXEKZ6gDeE8DD2dhN9fZDOegX6xB4nSYp3HsEU//sbgT19O1Yc53guoC6cvv7b4q5on7L7KT9qNTBu8baDsJtPTmH7z4GvKfwBctf5ar797u2ugK/LZtDHVMYfVAZwLi7PhtqU7TX7WTfNbjo3M46F+O726FbdvVuUff8663TUIzcjUE2cMsxKtZG0CnNO8Nkffzd8yN7ncdLZsc1Zs/4vMBx2sZxVsdxljN+HceZw/Gua7Gt3p1aPp3TeTpXTAvJNxnPhRKqDs+YYaoX4DlRieKclTyvar98eM6A33EDz3OZhvBcJQZrWdcYAFnTxXiel/HTeVEDLv8QvSo2z6Xlh3M4yYU2LTrPROalc5YIXnJ1RedZ+9twbju3DeeEJJSUODxH53CSEGzaeE5FooyZx3ORaM31PJ3DpUJ44FwbqTxwriUxPjgXCRFSe+lcJFhS6uVzQgj18zkhbFl8Tgklkc8jn0c+XzOf06XyOX0qn9PI5y+Gz+lz87nM+Tw3MsuCz+nz8rmXzqmPzqWHzmWk80jnkc4jna+AzjUXZqPpXHLN6+zMKKeLjOdEJ0YpUrKz0C12nqNzzqVo0Hkm0xCdywQbSRsKAyIxY2wBnedlwrbzrIbiD1Uro/NMWgE614lklHjo3IosQOeMKNai86z9bTq3neulc2JMAM5hWVArVINzmVBd2qsLOJcJ04rOwzlcyj1sbqg0PjZXTPvZHCTHA2wuRalBaLI5NqXNfp7N8dLQnJU6hIjmEc0jmq8LzdlS0Zw9Fc1ZRPMXg+bsudFcOzQnhemcLwfNScB07oVz7YFzHuE8wnmE8wjnzw3n+URVsblWm203B7CWdQx27V1A5pQlmhNekrnRUmm2iMwxUw27uWaEqrBbO0sMo7xhN5dmztN+nszzMmG7uTS49ofKVZF5Li0/mcNJqkrOrpO5FZmXzAFvK6N2ReZZ+9tkbjvXQ+bQa4bJIJorw312c5VgXD5tgeYKeL10zC/RXCWEKO1jc0J8bK4J8bG5TjgtjeNNNtcJMZL52VzpgF87VqVP/fPDOY5wHuE8wvm64ZwvFc75U+GcRzh/MXDOnxnOKc7hnGZwTgs4F88M537LufDAOcUeOKcxODsGZ8fg7LUFZ88xLEmI4lJttHm5HoxdNjgMsTAfasNrTGoMxzwMsSJhlJim8zczWAQhliYwbBsWb4IJXQyxeZmgeRlqILXIbLMyiM2k5WdYe07pFsJmAvMirEiI5rSFsFnrPcblKg66EZetGeahuGxptPHGZWMj1BzA8kRU1vESYHnCSd0qXAAsx5J7AJYJTP1R2RhrEQjLhlPcC7BMGOYHWCYrMn9ugK2iwSPARoCNALt6gL2CMd+5WlZ2sbz2bwfYooIIsJsPsHlfPxZgbbH7AbYdmE1XEphNHwqwMTA7WpejdTlal1fg+q2JNmSj47Jrjt9ZXDaTaHFctmFKl9ZfbrgmamFcNiW6YV92Il0Ul02pnMvkpu6Ny7ZlgvZlW0M9a9oKw7KtsIJh2ZJR6gvLBokFHL9B3NQXlg3N94RlB/y+qabBoGzMNPEHZTOm2kHZqgy/rgdl83oStNK4jJUvY5oWKhSUbZQKOH5bXYs/KBsHHb+rcO3nNy4zE9k8snlk8zWzOVkqm5OnsnlMmvZy2Jw8N5vTQFC2WEFQtte0TGNQdiTzSOaRzNdE5pwJLTfaai4kagZla3RPULbCZZY1wBKuMFeLg7JJ0/U7k+mCoGwlmtoCUkZ9h4Oy1aJ85qSeMA1jtsKYbCusYEw201J7Y7JJKGMao8IXkq08ycyhZ/0B2dioMJmTqlQjIpsRYVoR2Rxj4onIFsoXko39EdlU+MFcVmb6eTAXSofAnLBQRDZdmtGcEBnBPIJ5BPO1gTkMx1FntCyjeV77t4N5UUEE880H87yvHwvmtpjr13szppWe32VYNluJ5zd7aM40Hj2/o+d39Pz+F9qWyyij8Ubvy0XqzGg9s4VsZwpr+H7T6gJUiSi8LxdhphEiLQRTKuz7zROQTsMijQW+x/c7LxPGWFFQSh7BvDrfbyutkO83ldi3KZcVmBdibQhx6eRdUWzW+jbGkgpum77fOBS9rBOpqG9PLjjB6bx92SRKGtPakivhzNA2xQpDfcHLogxDnnf9pjq0IxecCnh+Mxnw/BZmadZlERE2ImxE2LUh7O34S9q5XRbC5rV/O8IWFUSE3XyEzfv6sQhri00esiMXnotcXlvGb76auOVoXI7G5WhcjsbllnFZYLO5UM5sEufGblwAX2wRlDOgasyLCGuSCE6xWrAbF7Vhx434aidRtCAgG0s8v0EYE/cEZLsyYSi3NdR241rZRtmZsAJJxXRiOGt7fWcS81I5SUy1y1U9Its2f57Ks771JhWTxJBgUjFmKqfwRlIxJVvWZZ0obeQ8l+tEKM48m3Ep6jUvU+WNyTaJFIGYbBBdFTk+l1Sskul8UjHOxLLInEfzcmTzyOZrZ3OyVDYnT2Xz6Pf9cticPDub09y2rOfYHD+zbVk/fLdsGuk80nmk80jna6JzRigVG83nAF3NmGnOtFmQ9Vtb115V8rmu/QrwORVsPus3DRvNgUExa0Rlc03vyfqdlwlGZUMNa7GZ58IK8LlKuCdhWiawAJ5rXbptV3ietd6D5xVPN/GcU0KDeE6MdzsunXBjWlZzoWuh2qXVnHHhSfmtJfZGZfszfsOTYMr9Kb/hvgTzEJ2HUn7Xdi1/djrXMWNapPNI52uicyKUyDMtL8V2Xq//Gwm9UUVk9A1n9HpvP5jSr26nDshqub8JfGD9BnRWGNAJvpfS7dNw+lhMZw+HdJ8JneBI6ZHSI6VHSl8+pXOpBdngvblIIomiNSTmEhvGFu3Nhe1uTKykdFz75Xdt57zpqZ7LNETpJlFUNPbmoorLxZSelwlSOtQgaqnTxMooPRNWIEDbJIbXYqUr33YrsYBvOyftPbOz1s9Teta1bUoH3hY6lNec2uxsPud2ShKN5fym2TSRGrcwHY7CrecxnSeU1Kk7v5glmhJvjDY8iiDGi+nMysG/MxcxWAditM0iSidCijlMJ0LLB3I65pJETo+cHjl97ZxOlszp5OmcHm3pL4nTyXI4vZ3h/JkxPZTi/MGgHlOcR06PnB45fRWcrrURG43pmteZmFFJF26hDXCJdblnNk5M7VcgAl003ekzkS5Ica4VFs0ttIluhqy3U5y7Mgu20LY1rN6YngsrmEdNCh+lW4EFKJ1gwz0Zzm3rPZgOXdvGdEYTwrQJYDpPbDZ4D6ZTG/1uWpiuiWBtTFdGsDam88Z2YiVxG8ylH9OZCuQ4Z3YzsQCmKx2IQieV4X8JnB430I6UHil9/ZROl0zp9OmUTiOlvyBKp89N6TKQ65w+M6U/PB5dxmTnkdEjo0dGXw+jC8H4ZjO6qbmjA8iIKh49lOtcVx7oICCFpWYLGZ1zPZclji9gdGEpUTe2IRNMynzbcj+j52XC25C5Goo/wqwy2bmVVhDSheDePHEgsiCly/Y+ZFn7PZRuaq7zFaUzIFnFApSuEmq0F9KlKP3kP5UcjSnx2NKtv0Ib0hXH7URxPGGG+RldYCJDpnQphJ/RpQilO5fVBmvPz+hSRVt6pPRI6eundLZkSmdPp3QWKf0FUTp7bkrXeWC6mEt6/syUTh6xXTjRq8l6Hjk9cnrk9Mjp85wuKazVySaDusa0kc6dAhzlUOwHdWHDo2nN+s4JWmBMl4mquDzLTZfJNATqLDFAkU1Qv2+/8LzMAlBv7Beu5cpAPZNWANSF3Rm8bU7PROYFdQnsTdte71n726BuO9fj9S7hcqyC5nTKiI/UAe9lqVaoSJ2adnC6jYrXHnO6qLYXr5M6rRzY51CdSCYCqE44DZjTuQyhuqDLI3XFoj09knok9fWTOl8yqfOnkzqPpP6CSJ0/M6lT3NyejN67d/i3kvojtg/HMYdcJPVI6pHU10TqRrMNDk6v4tJLjJZyMagDRtZ90gmprveDOmaMNu7gRLogxTuhqpFzDksm70vx7sqEU7xDDTVQN3ploG6lFcB0ac3C1IPpVmBeTBdJaeuu53e3bW/vuoY92eOsf7wJZY9TCRa1dPS0hu5Cs3mHdw63LV3tP1XQjTWT84RuA9DL6Pm6w7sULODwLgnVAUIXioX2DheB9HGEYLE8RDc8InpE9Ijo60T0Kxj1navlJZDL638KohdVRER/CYie9/ajEd2WuxfR24HpdDWB6fShiB4D0yOiR0SPiL4KRGd8w/PHSVb3MGes5qIeyB/HuakC0xXmpMwP53V6Z/UMdaVIFwSmA0WaRv44oe8NTHdlwvnjbA0Vowu6wgRyVlqBNO8up5n2OL2zeua3ptM71Vp5QtNt+z1O77JWfT2DnBEsnEFOicojvuH1TrQU7dB0hmnb611jY9q2dGaML4OcUQGndxPmdIFNIDDdhCzpuiyyjARyikdOj5weOX3tnE6WzOnk6ZweE8i9JE4nz83pNBCaLlYRmu41pNMYmh4pPVJ6pPQ1UboSWqlNxnRFZMMwzokS9+SPU8SoiusJl1wtjE1nzb3Pc5mGMN1aknFjd3WMBS7M9X5Mz8uELelZDcUftbrt0nNxBRO9CyaZLzid4VAKOWxUOzg9E0Cb023velPIMU1DKeSktYZTL6eLKgV8LTq9yt7eiE6nxBOdLjH3RadXGfPmLeqM8hCpGxzweZcylEJOqiWSuig7JpJ6JPVI6usgdRiQo85oeRb1vP6nkHpRRST1l0DqeW8/mtRtOde19yWSKx3fyxB1thrHd/bQVHIxRD3yeuT1yOurSCWntJFms0PUTcPNXGClxCJeV4nmZa434HVFzSKzuo23lo0Q9VymIV63LtWiYYfHjLDF27LlZcK8DjXUNk8neHUx6pm4AryuEqmU9Maoy2CMepkRrcL1rP2+EHXjySVnDeTVVmjzDvBWhyCMN0Sdcg+us0rjUAtRZwR7QtSxwj6zuuI4gOsgOhLKJsdDhnVOaQDXOVserhNcz7kfcT3iesT1leP67fhL2rldHq7n9T8F14sqIq6/BFzPe/vRuG7LTR6wNRueC1JfX9J3HkPUI6lHUo+kviZSl5TRDSZ1mOpFk9QxNXIhqfO6MR4nlErWRvs6qROqGobyXKbhGHWsKWk8Eif4vhh1VyZM6raGGqqvLus7bxi350CdJ0JoXzI5K7IAqGMtfXHqtv2eOHXhJXWSSK5ChnVsVQvSG6rOWBmNXZG6EVi2Sd0Q6fF/rzLW1+3qxITSvhPBQqnkiNGBQHUdDFQnSwxUlyYGqkdOj5y+fk4nS+Z08nROjw7wL4nTybNzOs1t6nqO0/Fz29T1w7dQp5HUI6lHUo+kvqYt1I0QVGw0qSvdsHjbDbwpXWhTZ6TmNK9qvwLZ5ARr7qGeyTRE6iQxmqhG2ndDxGKbel4mnPbdkHoyOUNWaFIvU5+1s8nBgzBfNjnBVCibnCkjwCtOz1rv4XSlPQ7wxCQmlPPd7RhXS3/XyCiHS/N2LaMcELMno5yqu7SX12rjC1NnJpBQTlEawHQp52i8wnTJg/nklrg5mxHRnB4xPWL6mjCd8mVuzVbV/o2IXqsgAvqGA3rV1w/G8y/QSfU87zTh/Mk7slGegfm//45svAO9AfO7pWr4W8f9NSe/HHayHsyFCWPgsJvNOe7SJpd3r3voP9Bhmlre2UNdOynC+qlj5V3Vbmt6ndWRHekAsY1H8PamtrZK1vbKs1doy6E5tSaguUfsdE/CpJ5hpgfW3YibDa6uZ6ltJlEdWJL331UpDKYtWrd1+YG9gr/sQZy8d+137buD0yn6PWLoEP6b4619Axxj5hPawZ9PD46P9g5POu8AtH7odOFz+n5/7/TgJLmB5nf2+Pa8SiCTGEHdDBC94O9GIbTP4ngBwNtvHCjPMX2hCLBA3+hYtFVUaTHz9yhbawF/wlQ4dnoF9xw0ew7qbvGmPNi+DQvrDZwuhj1IdVDpDex3vak7sNUsUh9Y2UML3n04/cE97bTUGuRts8qDrJJMfwD8AbQMlVg5Z6R4zLLfWXuzvjk93js66R6//3j6/sMRfFBPgZfhga/S/vZuNt0PQKRWGJczYKEJ3KuPRKmKgbukf4f+slW5viyUWVbome6mn17BSJ1kn5rD7UypYd+iTMcAgztNR25YWdooKwYs2EaXw559FGSnBPtKuVWgZ8jaNaYdqjArwyW2suyBLezDGu7mBi5/t9f9YzGkijpe35adZauxMA2L0n7v1k6IsBIbj+y9n0lNQlqakVKz4dQn86qREc91JiNYlYmyMPyW8LtRmGWFpSvM7AUtvYqq61WU/WdOr6LcEx7bUWL/LlagVMk/MZVOhWAhGNvo9H9CN7wf8hYv1KkIKkuNB+cSiwU6FZtrjtYzF0gsDV+Q/g/gW9GmQwZneHH6v7zMAu8HqKGmVVF8lUoVEFdArZIoQtveD5nIvFoVKuAUp75ABUU9e+nZ3m2rVYzNVif9ahWRSE+QAiOJpozN6VRwYkzb9QHXN+ordSr2qGQtpQr0jRZepQoUkMwfpIATaoxfqwK97HV+gHUTLbMN+LQqlBeuMaVWhXLNxEO0KipRzEStStSqRK3KurUqfKlaFf5UrUrcQu/laFX4c2pVHr973rdqVeLuedHhITo8RIeHf4d97pnZ6Jx/kjTZnHFd0nog5x9cUbE5UFKVoc+b809QLJvb3DOj0EJ/ByOb29xTdL+/A5RZsM09qbs7aLrClH+8Ys92CgFDjfCk/LMiC6T846Tc+L3p8VC6DdTRnPjQHB5KNl0hmuESkhDp3+aectZO+cdqfhBVyj9NmG8TPaNbeG4vxjTg82B4aJt7qWnA6UGxUA4BGNpLwnPrUUFVxPOI5xHP14bnS0z4V9X+7Xgek/29HDx/bKo/h+dzef58jg+PzvP3vIi+zjx/0fEhOj5Ex4fo+BAdHzbE8YEazjbb8UEI1siGmLc4vO+hBOIto0NIgiVZ6PjA4IvFeU1XYkwtX6NHuWLjC2Q9XAUTYdTitA95maByxdZQ83tYWXrGXFghtwfBtWmpVjKB+d0eTEKEZ9vDrPlt3YrtW49uJeFYa69qxaZbFNyjWNEgQ21afg9aYdL2e9BEmLbfg90e0+f3wBTz+z1gE0j6YN1zKJcezQo0WWqvZoWCiIRYmuOD3VUkalaiZiVqVtamWVlibsaq9m/XrMS8jC9Hs/LYrIxOs1JP9eBTqzw6JeO3qVX+9VIy0k5BppMURF4Zu93P2tR2eze97tza8Q0UDZJralP+2Jv0RoOL8bA3zfQpNFGdn5HBuPMjSNppV6y4HTAM/p5OzqCPna6E2BXj64woYRxZRYvrl8ZzbBc+Ei3VyRtULBLR+LLAQfd1GaHPsOCG70A+O14Aabhps0PKgzvoyxBRKgXnwuA+V4qo8x0kX1OOri6Jxk4PUVA9sCsMsO2H+knUdANzLgUndWXBrhNy5gDwedBDlZcBmtMLlEqAY+oUJB8b5bLLPgIxFrKz3gj2E3vMt6uionCayHQd9PddausaXzrpoek1zJN9+97e9mbXb1BLZbPVzfU8347IvO1RsAiXHVRbDwN2NnJN/phfk3Ew/FuQc0bRGVHzsjDzeiCIOiGLBmJnhCzcQ+U3zDBcVjeEa7g7kBcQ7gK2DowG8W94SgZBRTN5oqQLkyfa/eIJrxhXGqpb2F3Nt8RtLWfm7kDzGvzJE/lc+AAl5N7kiXxh+ICtoZY8Ea/ORyETV4CjSUK1Ii2QzmXmJWk4J5j25k/k7QCCrH9bJI2BlpXfRwHbVAieTQmJSITGogXSlBkPSFMmWBukBWbcA9Ki2iCgAdIu7qPu0zBH0hWWz4UQEBXIn6iqaIcl+ChgySJJR5KOJL1mkiZLJWnyVJKOmRNfDkmT5yXpRydN/FYHhX+9pInRQSE6KEQHheigEB0UNsVBQRIh5CarVqgq93/MHBSyFi9SrUgsTBX9UfvlzcwgEmKqjJgkwcZwtsBBwWoDlGmqVrS5V7ViyyxQrUANa9mXIpOWX7Niwx5oOy9DJjC/hwK1uUKpT68iyo0manoV27keDwW7WYZi/ugPnTAjfMEfJqkaUk/NUMY81FMzcM49qRm0oB7NCq3cJeZTM2gZSs3A59UnRRmJcSA1g6DlppbPrVeRzq8n6lWiXiXqVdajV2FimakZqtq/Ua9SqyDqVTZcr1L19YP1KkxcXf9Wz83AEvHk1AxMVB+0f+/UDKQDM7XDts5Fb3oBU8huDnywXBt+rYjOVp1d4PVROLnupZeAtHWtCqwLOj/vuP99X/opjL+gI/eC7RUv2Nkrp7UoHBbU/W4IAR8E4sjS64bQv+j3BCaG9NWFSGGBhggu/RDaTggNTcZj/BAK7G/4INjaHpHmwNJ9Pb+Dc0KY807weA4Q+B4UPVTkJ7A0uLXXRfkH4/mTFXhAN0s3UOAsa+QzyFwHHPvO82zdt+Ab3QnWkF2QCiI3OoMBzHQNJ/u8xWGGFYnCVFXuAVxq3ipQY1ibVk7pms8819qghRkMSojOClD6gAwGtkzQyZ7SRgYDo1fGsJm0/AxrEsJkO4FBLjE/xEIHGax9KQyE8KQwsL3r2VzR7uZAZAhiqRbe/IKS8nn3AJJoXOJqCbEkUUa3IJYmWnj87G2KReJjWEBwKbiXYW2uw3KriCbDMhzYs4EJuWjPBtZGWCarQ/e4BihTVyFEhI0IGxF2xQi7xPQFVe3fjrAxfcHLQdjHpi/IEHYuf0EbYx+fvuB5MXad6QsixkaMjRj7zU7ujOkNDxanvJknr2jyIjd3xWmtADZSSUNDbu7GpptTFZYCDMnylv5gcWJ4g2PxfTsP5mXCHGtrWKFju+I0hK5Ym7b9NReS36/dJJRp6osQhza30dV2aBtdbQq/kPlVAPxJj2c7Y4lipcv7pxIvsWae3HtYEzmPrsC+0ouuvEqjN8eu1vzpZVe4g+F++yvVJXm34JWypcGrJibaXyO8RnhdEbz+9f8BLAVa8w=="
# <<< PROMPTS


# ============================================================ helpers
def el_min():
    return (time.time() - T0) / 60.0


def left_min():
    return BUDGET_MIN - el_min()


_LOCK = threading.Lock()


def log(*a):
    msg = "[r3 %6.1fm] %s" % (el_min(), " ".join(str(x) for x in a))
    with _LOCK:
        print(msg, flush=True)
        with open(os.path.join(OUT, "kernel.log"), "a") as f:
            f.write(msg + "\n")


def event(kind, **kw):
    kw.update(kind=kind, t_min=round(el_min(), 2))
    with _LOCK:
        with open(os.path.join(OUT, "events.jsonl"), "a") as f:
            f.write(json.dumps(kw, default=str) + "\n")
    log("EVENT", json.dumps(kw, default=str)[:1500])


def redact(s):
    return re.sub(r"://[^@/\s]+@", "://REDACTED@", s)


def sh(cmd, timeout=None, logfile=None, env=None, shell=False, cwd=None):
    shown = cmd if isinstance(cmd, str) else " ".join(cmd)
    log("$", redact(shown)[:400])
    try:
        p = subprocess.run(cmd, shell=shell, env=env, timeout=timeout, cwd=cwd,
                           stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                           text=True, errors="replace")
        out, rc = p.stdout or "", p.returncode
    except subprocess.TimeoutExpired as e:
        out = e.stdout or b""
        out = out.decode("utf-8", "replace") if isinstance(out, bytes) else out
        rc = "TIMEOUT"
    out = redact(out)
    if logfile:
        with open(logfile, "a") as lf:
            lf.write(out)
    log("rc=%s" % rc, "| tail:", out[-600:].replace("\n", " \\n "))
    return rc, out[-4000:]


# ============================================================ phase 0/1
def env_log():
    lf = os.path.join(OUT, "env.log")
    sh("nvidia-smi; nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv",
       shell=True, logfile=lf)
    sh("free -g; echo NPROC=$(nproc); lscpu; df -h / /tmp /kaggle/working", shell=True,
       logfile=lf)
    model = None
    try:
        for line in open("/proc/cpuinfo"):
            if line.startswith("model name"):
                model = line.split(":", 1)[1].strip()
                break
    except Exception:
        pass
    try:
        aff = len(os.sched_getaffinity(0))
    except Exception:
        aff = None
    rc, npr = sh(["nproc"])
    event("cpu", os_cpu_count=os.cpu_count(), sched_affinity=aff,
          nproc=npr.strip().splitlines()[-1] if npr.strip() else None, cpu_model=model)
    sh("pip freeze", shell=True, logfile=os.path.join(OUT, "pip-freeze-pre.txt"))


def _token():
    for p in sorted(glob.glob("/kaggle/input/**/gh_token*", recursive=True)):
        tok = open(p).read().strip()
        if tok:
            return tok
    sys.exit("[r3] no gh token dataset attached")


def preflight():
    need = {"gh token": ["/kaggle/input/**/gh_token*"],
            "ngspice cache": ["/kaggle/input/**/ngspice47.tar.gz",
                              "/kaggle/input/**/ngspice47/bin/ngspice"]}
    missing = [k for k, pats in need.items()
               if not any(glob.glob(p, recursive=True) for p in pats)]
    if missing:
        log("/kaggle/input:", glob.glob("/kaggle/input/*") + glob.glob("/kaggle/input/*/*"))
        sys.exit("[r3] PREFLIGHT FAILED -- missing inputs: %s" % missing)
    log("preflight OK")


def clone_and_bootstrap():
    tok = _token()
    url = "https://x-access-token:%s@github.com/%s.git" % (tok, REPO_SLUG)
    if not os.path.isdir(os.path.join(CLONE, ".git")):
        sh(["git", "clone", "--depth", "1", "--branch", REPO_BRANCH, url, CLONE])
    head = subprocess.run(["git", "-C", CLONE, "rev-parse", "HEAD"],
                          capture_output=True, text=True).stdout.strip()
    if head != REPO_SHA:
        sh(["git", "-C", CLONE, "fetch", "--depth", "1", "origin", REPO_SHA])
        sh(["git", "-C", CLONE, "checkout", "--detach", "FETCH_HEAD"])
        head = subprocess.run(["git", "-C", CLONE, "rev-parse", "HEAD"],
                              capture_output=True, text=True).stdout.strip()
    if head != REPO_SHA:
        sys.exit("[r3] clone HEAD %s != pinned %s" % (head, REPO_SHA))
    log("clone pinned at", head)
    env = dict(os.environ, WITH_PANDAS="1", GH_READ_TOKEN=tok, REPO_SLUG=REPO_SLUG,
               REPO_BRANCH=REPO_BRANCH, CLONE_DIR=CLONE)
    rc, _ = sh(["bash", os.path.join(CLONE, "kaggle", "bootstrap.sh")], env=env,
               timeout=1200, logfile=os.path.join(OUT, "bootstrap.log"))
    event("bootstrap", rc=rc, clone_head=head)
    if rc != 0:
        sys.exit("[r3] bootstrap failed")
    return head


def check_fence(rows):
    held = set()
    for d in glob.glob(os.path.join(CLONE, "kaggle", "editcap-lib-v12-*")):
        held |= set(os.listdir(d))
    bad = [r["cell"] for r in rows if r["cell"] in held]
    assert not bad, "FENCE: bench-v1.2 cells in prompts: %s" % bad
    assert all(r["source_lib"] == "editcap-lib-v1a" for r in rows)
    event("fence", n_prompts=len(rows), n_heldout_cells=len(held), violations=0)


# ============================================================ reward module
REWARD_PY = r'''
"""r3_reward -- GRPO reward functions for the R3 smoke (written by kernel.py).

reward_valid : 1.0 if the FIRST fenced netlist of the completion round-trips
               (kaggle/loop/proposal.round_trip -> ok) else 0.0   [every rollout]
reward_novel : 0.5 if valid AND its WL hash differs from the cell anchor's
reward_spice : REAL SPICE sizing (bench_anchor_prep.smoke_run, 1 seed x
               SPICE_BUDGET evals, pdk PDK) on the first N_SPICE valid+novel
               rollouts of the step, run in a CPU process pool; reward 2.0 if
               feasible, else 1/(1+sum of normalized violations); unsizable 0.0.
               Every other rollout gets 0.0 (the "trivial" reward).
"""
import json
import os
import re
import sys
import time

CLONE = os.environ.get("R3_CLONE", "/tmp/circuit-repro")
for _p in (os.path.join(CLONE, "kaggle"), os.path.join(CLONE, "lna"),
           os.path.join(CLONE, "kaggle", "loop")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

NET_RE = re.compile(r"```(?:netlist|spice|text)?\s*\n(.*?)```", re.DOTALL | re.IGNORECASE)
PDK = os.environ.get("R3_PDK", "bptm45")
SPICE_BUDGET = int(os.environ.get("R3_SPICE_BUDGET", "300"))
LOGF = os.environ.get("R3_REWARD_LOG", "/tmp/r3/reward.jsonl")
N_SPICE = 0
POOL = None
_INFO = {}
_ANCHOR = {}
_STEP = [0]
BAP = None


def _log(**kw):
    with open(LOGF, "a") as f:
        f.write(json.dumps(kw, default=str) + "\n")


def first_netlist(text):
    for m in NET_RE.finditer(text or ""):
        nl = m.group(1).strip("\n")
        first, _, rest = nl.partition("\n")
        if first.strip().lower() in ("netlist", "spice", "text"):
            nl = rest.strip("\n")
        if nl.strip():
            return nl
    return None


def round_trip(text):
    import proposal as P
    return P.round_trip(text)


def anchor_info(cell):
    if cell not in _ANCHOR:
        path = os.path.join(CLONE, "kaggle", "editcap-lib-v1a", cell, "anchor.net")
        _ANCHOR[cell] = round_trip(open(path, encoding="utf-8").read())
    return _ANCHOR[cell]


def spec_path(cell):
    return os.path.join(CLONE, "kaggle", "editcap-lib-v1a", cell, "spec.yaml")


def info(text, cell):
    key = (cell, text)
    if key in _INFO:
        return _INFO[key]
    t = time.time()
    nl = first_netlist(text)
    out = {"has_fence": nl is not None, "ok": False, "novel": False, "tokens": None,
           "error": None}
    if nl is not None:
        try:
            rt = round_trip(nl)
            out["ok"] = bool(rt.get("ok"))
            out["error"] = rt.get("error")
            if out["ok"]:
                out["tokens"] = rt["tokens"]
                out["novel"] = rt.get("wl_hash") != anchor_info(cell).get("wl_hash")
        except Exception as e:                                   # noqa: BLE001
            out["error"] = "EXC %r" % (e,)
    out["rt_s"] = round(time.time() - t, 4)
    _INFO[key] = out
    return out


# ------------------------------------------------------------- SPICE worker
def worker_init():
    global BAP
    os.environ.setdefault("OMP_NUM_THREADS", "1")
    import bench_anchor_prep as _B
    BAP = _B


def size_job(job):
    t = time.time()
    out = {"cell": job.get("cell"), "budget": job["budget"], "seed": job["seed"],
           "pdk": job["pdk"], "stab": bool(job.get("stab"))}
    try:
        if BAP is None:
            worker_init()
        sp = job["spec"]
        if job.get("stab"):
            sp = BAP.stability_spec(sp, out_dir=os.path.join(os.environ.get("TMPDIR", "/tmp"),
                                                            "r3-stab-%d" % os.getpid()))
        res = BAP.smoke_run(job["tokens"], sp, job["seed"], job["budget"], job["pdk"])
        out["sizable"] = res is not None
        if res is not None:
            spec = BAP.SZ._spec_for_sizing(sp, nf_gate=None, pdk=job["pdk"])
            ok, viol = spec.feasible(res.get("metrics") or {})
            out.update(feasible=bool(res["feasible"]), viol_sum=round(sum(viol.values()), 4),
                       viol={k: round(v, 4) for k, v in viol.items()},
                       n_evals=res.get("n_evals"), n_sim_fail=res.get("n_sim_fail"),
                       mu_min_wide=res.get("mu_min_wide"))
    except Exception as e:                                       # noqa: BLE001
        out["error"] = repr(e)[:800]
    out["secs"] = round(time.time() - t, 2)
    out["pid"] = os.getpid()
    return out


def start_pool(n):
    """Spawn-context pool, created BEFORE torch/CUDA initialise in the parent."""
    global POOL, N_SPICE
    N_SPICE = int(n)
    if N_SPICE > 0:
        import multiprocessing as mp
        POOL = mp.get_context("spawn").Pool(N_SPICE, initializer=worker_init)
    return POOL


# ------------------------------------------------------------- TRL rewards
def reward_valid(prompts, completions, cell=None, **kw):
    _STEP[0] += 1
    t = time.time()
    rs = [1.0 if info(c, ce)["ok"] else 0.0 for c, ce in zip(completions, cell)]
    infos = [info(c, ce) for c, ce in zip(completions, cell)]
    _log(kind="valid", call=_STEP[0], n=len(rs), n_fence=sum(i["has_fence"] for i in infos),
         n_valid=int(sum(rs)), n_novel=sum(i["novel"] for i in infos),
         errors=[(i["error"] or "")[:160] for i in infos if not i["ok"]][:4],
         secs=round(time.time() - t, 3),
         completion_chars=[len(c) for c in completions])
    return rs


def reward_novel(prompts, completions, cell=None, **kw):
    return [0.5 if (info(c, ce)["ok"] and info(c, ce)["novel"]) else 0.0
            for c, ce in zip(completions, cell)]


def reward_spice(prompts, completions, cell=None, **kw):
    rs = [0.0] * len(completions)
    if POOL is None or N_SPICE <= 0:
        return rs
    idx = [i for i, (c, ce) in enumerate(zip(completions, cell))
           if info(c, ce)["ok"] and info(c, ce)["novel"]][:N_SPICE]
    if not idx:
        _log(kind="spice", call=_STEP[0], n_jobs=0)
        return rs
    jobs = [{"tokens": info(completions[i], cell[i])["tokens"], "spec": spec_path(cell[i]),
             "cell": cell[i], "seed": 1, "budget": SPICE_BUDGET, "pdk": PDK} for i in idx]
    t = time.time()
    res = POOL.map(size_job, jobs)
    wall = round(time.time() - t, 2)
    for i, r in zip(idx, res):
        if r.get("sizable"):
            rs[i] = 2.0 if r.get("feasible") else 1.0 / (1.0 + float(r.get("viol_sum") or 0))
    _log(kind="spice", call=_STEP[0], n_jobs=len(jobs), wall_s=wall, results=res,
         rewards=[rs[i] for i in idx])
    return rs
'''

SPICE_BENCH_PY = r'''
import json, os, sys, time
from concurrent.futures import ProcessPoolExecutor
sys.path.insert(0, "/tmp/r3")
t = time.time()
import r3_reward as RW
RW.worker_init()
imp = round(time.time() - t, 2)
out = sys.argv[1]
cells = sys.argv[2].split(",")
budget = int(sys.argv[3])
jobs = []
for c in cells:
    a = RW.anchor_info(c)
    assert a["ok"], (c, a.get("error"))
    jobs.append({"tokens": a["tokens"], "spec": RW.spec_path(c), "cell": c, "seed": 1,
                 "budget": budget, "pdk": RW.PDK})
def emit(**kw):
    with open(out, "a") as f: f.write(json.dumps(kw, default=str) + "\n")
    print("SPICE", json.dumps(kw, default=str)[:600], flush=True)
emit(phase="import", secs=imp, ncpu=os.cpu_count())
for j in jobs[:3]:                                   # serial, plain spec
    emit(phase="serial", **RW.size_job(j))
emit(phase="serial600", **RW.size_job(dict(jobs[0], budget=2 * budget)))
for j in jobs[:2]:                                   # serial, stability-gated spec
    emit(phase="serial_stab", **RW.size_job(dict(j, stab=True)))
n = os.cpu_count() or 4
pj = [jobs[i % len(jobs)] for i in range(n)]
t = time.time()
with ProcessPoolExecutor(n, initializer=RW.worker_init) as ex:
    rs = list(ex.map(RW.size_job, pj))
wall = round(time.time() - t, 2)
for r in rs:
    emit(phase="parallel", **r)
emit(phase="parallel_wall", n_jobs=n, wall_s=wall)
'''


# ============================================================ GRPO trial script
TRIAL_PY = r'''
import argparse, json, os, sys, time, traceback, statistics


def _main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model"); ap.add_argument("--tag"); ap.add_argument("--out")
    ap.add_argument("--G", type=int); ap.add_argument("--L", type=int)
    ap.add_argument("--steps", type=int); ap.add_argument("--forced", type=int, default=1)
    ap.add_argument("--fast", type=int, default=0); ap.add_argument("--gmu", type=float, default=0.7)
    ap.add_argument("--n-spice", type=int, default=0); ap.add_argument("--deadline", type=float)
    ap.add_argument("--prompts"); ap.add_argument("--max-prompt", type=int, default=1536)
    ap.add_argument("--pdbs", type=int, default=1)        # per-device micro-batch (grad-accum = G/pdbs)
    ap.add_argument("--gen-chunk", type=int, default=0)   # >0: generate the G rollouts in chunks
    ap.add_argument("--fake-gen", type=int, default=0)    # 1: random-token completions (update-cost probe)
    ap.add_argument("--save-lora", default="")
    a = ap.parse_args()
    T0 = time.time()

    def emit(**kw):
        kw.update(tag=a.tag, G=a.G, L=a.L, fast=a.fast, forced=a.forced, t_s=round(time.time() - T0, 1))
        with open(a.out, "a") as f: f.write(json.dumps(kw, default=str) + "\n")
        print("EMIT", json.dumps(kw, default=str)[:3000], flush=True)

    def is_oom(e):
        s = (type(e).__name__ + " " + str(e)).lower()
        return ("out of memory" in s or "outofmemory" in s or "cuda_error_out_of_memory" in s
                or "no available memory for the cache" in s or "not enough memory" in s)

    sys.path.insert(0, "/tmp/r3")
    import r3_reward as RW
    RW.start_pool(a.n_spice)          # BEFORE torch / CUDA

    TARGETS = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
    GiB = 1024 ** 3
    try:
        from unsloth import FastLanguageModel
        import torch
        kw = dict(model_name=a.model, max_seq_length=a.max_prompt + a.L + 64, load_in_4bit=True,
                  dtype=None)
        if a.fast:
            kw.update(fast_inference=True, max_lora_rank=16, gpu_memory_utilization=a.gmu)
        model, tok = FastLanguageModel.from_pretrained(**kw)
        load_mid = round(torch.cuda.memory_allocated() / GiB, 3)
        model = FastLanguageModel.get_peft_model(
            model, r=16, lora_alpha=32, lora_dropout=0, bias="none", target_modules=TARGETS,
            use_gradient_checkpointing="unsloth", random_state=3407)
    except Exception as e:
        emit(phase="load", status="OOM" if is_oom(e) else "ERROR", error=repr(e)[:2000],
             tb=traceback.format_exc()[-4000:], load_s=round(time.time() - T0, 1))
        sys.exit(3)
    emit(phase="load", status="OK", load_s=round(time.time() - T0, 1),
         mem_alloc_after_load_gib=round(torch.cuda.memory_allocated() / GiB, 3),
         mem_reserved_after_load_gib=round(torch.cuda.memory_reserved() / GiB, 3),
         mem_alloc_before_peft_gib=load_mid,
         gpu_total_gib=round(torch.cuda.get_device_properties(0).total_memory / GiB, 3),
         has_vllm_engine=hasattr(model, "vllm_engine"),
         trainable=sum(p.numel() for p in model.parameters() if p.requires_grad))

    rows = json.load(open(a.prompts))
    def render(r):
        return tok.apply_chat_template([{"role": "system", "content": r["system"]},
                                        {"role": "user", "content": r["user"]}],
                                       tokenize=False, add_generation_prompt=True,
                                       enable_thinking=False)
    texts = [render(r) for r in rows]
    plen = [len(tok(t, add_special_tokens=False)["input_ids"]) for t in texts]
    emit(phase="prompts", n=len(rows), prompt_tokens_mean=round(sum(plen) / len(plen), 1),
         prompt_tokens_max=max(plen), prompt_tokens_min=min(plen),
         no_think_suffix=texts[0][-40:])
    from datasets import Dataset
    ds = Dataset.from_list([{"prompt": t, "cell": r["cell"]} for t, r in zip(texts, rows)])

    from trl import GRPOConfig, GRPOTrainer
    from transformers import TrainerCallback
    cfg_kw = dict(output_dir="/tmp/r3/out-" + a.tag, learning_rate=5e-6,
                  per_device_train_batch_size=a.pdbs, gradient_accumulation_steps=a.G // a.pdbs,
                  beta=0.0,          # no reference-model forward (unsloth default is 0.001)
                  num_generations=a.G, max_prompt_length=a.max_prompt,
                  max_completion_length=a.L, max_steps=a.steps, logging_steps=1,
                  save_strategy="no", report_to="none", fp16=True, bf16=False,
                  optim="adamw_8bit", temperature=1.0, seed=3407, weight_decay=0.0,
                  lr_scheduler_type="constant", warmup_steps=0, max_grad_norm=1.0)
    if a.fast:
        from vllm import SamplingParams
        sp = dict(temperature=1.0, max_tokens=a.L)   # NO seed: a fixed seed would make the G samples identical
        if a.forced:
            sp.update(min_tokens=a.L)
        cfg_kw.update(use_vllm=True, vllm_sampling_params=SamplingParams(**sp))
    elif a.forced:
        cfg_kw.update(generation_kwargs={"min_new_tokens": a.L})
    dropped = []
    for _ in range(6):
        try:
            cfg = GRPOConfig(**cfg_kw)
            break
        except TypeError as e:
            m = __import__("re").search(r"unexpected keyword argument '(\w+)'", str(e))
            if not m:
                raise
            dropped.append(m.group(1)); cfg_kw.pop(m.group(1))
    emit(phase="config", dropped_kwargs=dropped, use_vllm=getattr(cfg, "use_vllm", None),
         beta=getattr(cfg, "beta", None), loss_type=getattr(cfg, "loss_type", None),
         gen_kwargs=getattr(cfg, "generation_kwargs", None),
         per_device_train_batch_size=cfg.per_device_train_batch_size,
         gradient_accumulation_steps=cfg.gradient_accumulation_steps,
         generation_batch_size=getattr(cfg, "generation_batch_size", None),
         steps_per_generation=getattr(cfg, "steps_per_generation", None),
         num_generations=cfg.num_generations,
         gradient_checkpointing=getattr(cfg, "gradient_checkpointing", None))

    GEN = []
    def _wrap(obj, name):
        f = getattr(obj, name, None)
        if f is None:
            return False
        def g(*x, **k):
            t = time.time(); r = f(*x, **k)
            try: torch.cuda.synchronize()
            except Exception: pass
            GEN.append(round(time.time() - t, 2)); return r
        try:
            setattr(obj, name, g); return True
        except Exception:
            return False
    PAD = tok.pad_token_id if tok.pad_token_id is not None else tok.eos_token_id
    def _chunked(obj, name, chunk, fake):
        """Instance-level generate wrapper (TRL calls unwrapped_model.generate(input_ids=...,
        attention_mask=..., generation_config=...) and splits prompt/completion at the prompt
        length). chunk>0: run the G rows in sub-batches (KV cache of 8 x 2.5k tokens does not
        fit next to the 10.6 GiB of 4-bit weights); fake=1: return random non-special token
        ids of exactly L new tokens (update-cost / OOM-boundary probe, no generation)."""
        f = getattr(obj, name)
        def g(*x, **k):
            ids = k.get("input_ids", x[0] if x else None)
            if fake:
                new = torch.randint(1000, 100000, (ids.shape[0], a.L), device=ids.device,
                                    dtype=ids.dtype)
                return torch.cat([ids, new], dim=1)
            if not chunk or ids.shape[0] <= chunk:
                return f(*x, **k)
            am = k.get("attention_mask")
            outs = []
            for i in range(0, ids.shape[0], chunk):
                kk = dict(k); kk["input_ids"] = ids[i:i + chunk]
                if am is not None:
                    kk["attention_mask"] = am[i:i + chunk]
                outs.append(f(**kk))
                torch.cuda.empty_cache()
            n = max(o.shape[1] for o in outs)
            outs = [torch.nn.functional.pad(o, (0, n - o.shape[1]), value=PAD) for o in outs]
            return torch.cat(outs, dim=0)
        setattr(obj, name, g)
    if not a.fast and (a.gen_chunk or a.fake_gen):
        _chunked(model, "generate", a.gen_chunk, a.fake_gen)
    wrapped = _wrap(model.vllm_engine, "generate") if a.fast and hasattr(model, "vllm_engine") \
        else _wrap(model, "generate")

    STEPS = []
    class CB(TrainerCallback):
        def on_step_begin(self, args, state, control, **kw):
            torch.cuda.synchronize(); torch.cuda.reset_peak_memory_stats()
            self.t = time.time(); self.g0 = len(GEN)
        def on_step_end(self, args, state, control, **kw):
            torch.cuda.synchronize()
            rec = dict(step=state.global_step, s=round(time.time() - self.t, 2),
                       gen_s=GEN[self.g0:], peak_alloc_gib=round(torch.cuda.max_memory_allocated() / GiB, 3),
                       peak_reserved_gib=round(torch.cuda.max_memory_reserved() / GiB, 3))
            STEPS.append(rec)
            emit(phase="step", **rec)
            if a.deadline and time.time() > a.deadline:
                control.should_training_stop = True
                emit(phase="deadline_stop", step=state.global_step)

    status, err, tb = "PASS", None, None
    try:
        trainer = GRPOTrainer(model=model, processing_class=tok,
                              reward_funcs=[RW.reward_valid, RW.reward_novel, RW.reward_spice],
                              args=cfg, train_dataset=ds, callbacks=[CB()])
        emit(phase="trainer_built", gen_wrapped=wrapped,
             trainer_class=type(trainer).__name__,
             trainer_use_vllm=getattr(trainer, "use_vllm", None))
        torch.cuda.reset_peak_memory_stats()
        trainer.train()
    except Exception as e:
        status = "OOM" if is_oom(e) else "ERROR"
        err, tb = repr(e)[:2000], traceback.format_exc()[-5000:]
        print(tb, flush=True)
    hist = []
    try:
        hist = trainer.state.log_history
    except Exception:
        pass
    times = [s["s"] for s in STEPS]
    steady = times[1:] if len(times) > 1 else times
    if status == "PASS" and len(times) < a.steps:
        # a deadline stop after >= 1 full step still answers the pre-reg question
        status = "PASS" if (times and a.deadline and time.time() > a.deadline) else "INCOMPLETE"
    emit(phase="train", status=status, error=err, tb=tb, steps_req=a.steps, steps_done=len(times),
         s_per_step=times, s_per_step_median_excl_first=(round(statistics.median(steady), 2) if steady else None),
         gen_s_all=GEN, peak_alloc_gib_max=max([s["peak_alloc_gib"] for s in STEPS] or [None], key=lambda v: v or 0),
         peak_alloc_gib_at_fail=round(torch.cuda.max_memory_allocated() / GiB, 3),
         peak_reserved_gib_at_fail=round(torch.cuda.max_memory_reserved() / GiB, 3),
         log_history=hist)
    if a.save_lora and STEPS:
        try:
            model.save_pretrained(a.save_lora); tok.save_pretrained(a.save_lora)
            emit(phase="save_lora", status="OK", dir=a.save_lora)
        except Exception as e:
            emit(phase="save_lora", status="ERROR", error=repr(e)[:800])
    if RW.POOL is not None:
        RW.POOL.terminate()


if __name__ == "__main__":   # spawn children re-import this file as __mp_main__
    _main()
'''


# ============================================================ vLLM on a DEDICATED T4
VGEN_PY = r"""
import json, os, sys, time, traceback
out, model, lora, tag = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
G, L, NP = int(sys.argv[5]), int(sys.argv[6]), int(sys.argv[7])
T0 = time.time()
def emit(**kw):
    kw.update(tag=tag, t_s=round(time.time() - T0, 1))
    with open(out, "a") as f: f.write(json.dumps(kw, default=str) + "\n")
    print("EMIT", json.dumps(kw, default=str)[:2000], flush=True)
def main():
    import torch
    from vllm import LLM, SamplingParams
    rows = json.load(open("/tmp/r3/prompts.json"))
    use_lora = bool(lora) and os.path.isdir(lora)
    kw = dict(model=model, quantization="bitsandbytes", dtype="float16",
              gpu_memory_utilization=0.92, max_model_len=1536 + L + 64, max_num_seqs=16,
              enable_prefix_caching=True, seed=0)
    llm = None
    for attempt in ([True, False] if use_lora else [False]):
        try:
            k = dict(kw)
            if attempt:
                k.update(enable_lora=True, max_lora_rank=16, max_loras=1)
            llm = LLM(**k); use_lora = attempt
            break
        except Exception as e:
            emit(phase="init", status="ERROR", with_lora=attempt, error=repr(e)[:1500],
                 tb=traceback.format_exc()[-3000:])
            llm = None
            torch.cuda.empty_cache()
    if llm is None:
        return
    emit(phase="init", status="OK", with_lora=use_lora, load_s=round(time.time() - T0, 1),
         mem_used_gib=round((torch.cuda.mem_get_info()[1] - torch.cuda.mem_get_info()[0]) / 1024 ** 3, 2))
    tokz = llm.get_tokenizer()
    texts = [tokz.apply_chat_template([{"role": "system", "content": r["system"]},
                                       {"role": "user", "content": r["user"]}], tokenize=False,
                                      add_generation_prompt=True, enable_thinking=False)
             for r in rows]
    lr = None
    if use_lora:
        from vllm.lora.request import LoRARequest
        lr = LoRARequest("r3", 1, lora)
    for phase, n_prompts, forced in (("warmup", 1, True), ("forced", NP, True),
                                     ("natural", NP, False)):
        sp = SamplingParams(n=G, temperature=1.0, max_tokens=L,
                            min_tokens=(L if forced else 0))
        t = time.time()
        try:
            res = llm.generate(texts[:n_prompts], sp, lora_request=lr)
        except Exception as e:
            emit(phase=phase, status="ERROR", error=repr(e)[:1500], tb=traceback.format_exc()[-3000:])
            return
        dt = time.time() - t
        ntok = sum(len(o.token_ids) for r in res for o in r.outputs)
        lens = [len(o.token_ids) for r in res for o in r.outputs]
        emit(phase=phase, status="OK", prompts=n_prompts, rollouts=len(lens), gen_tokens=ntok,
             secs=round(dt, 1), tok_per_s=round(ntok / dt, 1),
             rollouts_per_hour=round(len(lens) / dt * 3600, 1),
             len_mean=round(sum(lens) / len(lens), 1), len_max=max(lens), len_min=min(lens),
             sample=res[0].outputs[0].text[:600])
        if phase == "natural":
            try:
                sys.path.insert(0, "/tmp/r3")
                import r3_reward as RW
                cells = [rows[i]["cell"] for i, r in enumerate(res) for _ in r.outputs]
                infos = [RW.info(o.text, c) for r, c in zip([o for r in res for o in r.outputs], cells)]
                emit(phase="natural_validity", n=len(infos), n_fence=sum(i["has_fence"] for i in infos),
                     n_valid=sum(i["ok"] for i in infos), n_novel=sum(i["novel"] for i in infos))
            except Exception as e:
                emit(phase="natural_validity", status="ERROR", error=repr(e)[:800])
main()
"""


# ============================================================ phase 2: SPICE timing
def spice_bench():
    outp = os.path.join(OUT, "spice_bench.jsonl")
    inner = "source %s && exec %s %s %s %s %d" % (
        ENV_SH, PY, os.path.join(TMP, "spice_bench.py"), outp, ",".join(SPICE_CELLS),
        SPICE_BUDGET)
    env = dict(os.environ, R3_CLONE=CLONE, R3_PDK=PDK, OMP_NUM_THREADS="1",
               R3_REWARD_LOG=os.path.join(OUT, "reward-bench.jsonl"))
    t = time.time()
    rc, _ = sh(["bash", "-c", inner], env=env, timeout=900,
               logfile=os.path.join(OUT, "spice_bench.log"))
    event("spice_bench", rc=rc, wall_s=round(time.time() - t, 1))


# ============================================================ phase 3: installs
def constraints():
    rc, tv = sh([PY, "-c", "import importlib.metadata as m\n"
                 "for p in ('torch','torchvision','torchaudio'):\n"
                 "  try: print(p+'=='+m.version(p))\n"
                 "  except Exception: pass"])
    pins = [l.strip() for l in tv.splitlines() if "==" in l and l.strip().split("==")[0]
            in ("torch", "torchvision", "torchaudio")]
    cons = os.path.join(TMP, "constraints.txt")
    open(cons, "w").write("\n".join(pins) + "\n")
    return cons, pins


def install_main(cons, pins):
    plog = os.path.join(OUT, "pip-install.log")
    rc, _ = sh([PY, "-m", "pip", "install", "-q", "-c", cons, "--only-binary=xformers"] + PINS,
               timeout=1500, logfile=plog)
    chk = ("import torch, transformers, peft, trl, bitsandbytes, accelerate\n"
           "import unsloth, unsloth_zoo\n"
           "import importlib.metadata as m, json\n"
           "v={}\n"
           "for p in ['unsloth','unsloth_zoo','torch','transformers','peft','trl','bitsandbytes',"
           "'accelerate','datasets','triton','xformers','cut_cross_entropy','torchao','vllm']:\n"
           "  try: v[p]=m.version(p)\n"
           "  except Exception: v[p]=None\n"
           "v['cuda']=torch.version.cuda; v['gpu']=torch.cuda.get_device_name(0)\n"
           "print('VERSIONS_JSON='+json.dumps(v))\n")
    rc2, tail = sh([PY, "-c", chk], timeout=600, logfile=plog)
    m = re.search(r"VERSIONS_JSON=(\{.*\})", tail)
    event("install_main", rc=rc, rc_check=rc2, versions=json.loads(m.group(1)) if m else None,
          torch_constraints=pins)
    sh("pip freeze", shell=True, logfile=os.path.join(OUT, "pip-freeze.txt"))
    return rc2 == 0


VLLM_STATE = {"status": "pending"}


def install_vllm_venv(cons):
    """Background: --system-site-packages venv + vllm. Sets VLLM_STATE."""
    lf = os.path.join(OUT, "vllm-install.log")
    t = time.time()
    try:
        rc, _ = sh([PY, "-m", "venv", "--system-site-packages", VENV], timeout=300, logfile=lf)
        if rc != 0:
            sh([PY, "-m", "pip", "install", "-q", "virtualenv"], timeout=300, logfile=lf)
            rc, _ = sh([PY, "-m", "virtualenv", "--system-site-packages", VENV], timeout=300,
                       logfile=lf)
        vpy = os.path.join(VENV, "bin", "python")
        if rc != 0 or not os.path.exists(vpy):
            VLLM_STATE.update(status="venv_failed", secs=round(time.time() - t))
            return
        rc, _ = sh([vpy, "-m", "pip", "install", "-q", "-c", cons] + VLLM_PINS, timeout=1500,
                   logfile=lf)
        chk = ("import importlib.metadata as m, json, torch\n"
               "v={p:(m.version(p) if p else None) for p in ['vllm','transformers','torch','unsloth',"
               "'unsloth_zoo','trl','numpy','numba','xformers','flashinfer-python']}\n"
               "import vllm\n"
               "print('VLLM_JSON='+json.dumps(v))\n")
        rc2, tail = sh([vpy, "-c", chk], timeout=600, logfile=lf)
        m = re.search(r"VLLM_JSON=(\{.*\})", tail)
        VLLM_STATE.update(status="ok" if (rc == 0 and rc2 == 0) else "install_failed",
                          rc_pip=rc, rc_import=rc2, versions=json.loads(m.group(1)) if m else None,
                          tail=None if rc2 == 0 else tail[-1500:], python=vpy,
                          secs=round(time.time() - t))
        sh([vpy, "-m", "pip", "freeze"], logfile=os.path.join(OUT, "pip-freeze-vllm-venv.txt"))
    except Exception as e:
        VLLM_STATE.update(status="exception", error=repr(e)[:800])
    finally:
        event("install_vllm", **{k: v for k, v in VLLM_STATE.items()})


def predownload():
    t = time.time()
    rc, _ = sh([PY, "-c", "from huggingface_hub import snapshot_download as s;"
                "print(s(%r))" % MODEL], timeout=1500,
               logfile=os.path.join(OUT, "download.log"))
    event("download", rc=rc, model=MODEL, secs=round(time.time() - t, 1))


# ============================================================ GPU memory sampler
GPU_PEAK = {}


def gpu_sampler(stop):
    f = open(os.path.join(OUT, "gpu_mem.csv"), "a")
    f.write("t_min,gpu,mem_used_mib,util\n")
    while not stop.is_set():
        try:
            o = subprocess.run(["nvidia-smi", "--query-gpu=index,memory.used,utilization.gpu",
                                "--format=csv,noheader,nounits"], capture_output=True,
                               text=True, timeout=20).stdout
            for line in o.strip().splitlines():
                i, mu, ut = [x.strip() for x in line.split(",")]
                f.write("%.2f,%s,%s,%s\n" % (el_min(), i, mu, ut))
                with _LOCK:
                    for k in list(GPU_PEAK):
                        g, _ = k
                        if g == i:
                            GPU_PEAK[k] = max(GPU_PEAK[k], int(mu))
            f.flush()
        except Exception:
            pass
        stop.wait(3)


# ============================================================ phase 4: trials
RESULTS = {}


def run_vgen(gpu, tag, G=8, L=1024, n_prompts=4, lora=""):
    tfile = os.path.join(OUT, "trials.jsonl")
    remaining = left_min() - 3
    vpy = VLLM_STATE.get("python")
    inner = "source %s && exec %s %s %s %s %s %s %d %d %d" % (
        ENV_SH, vpy, os.path.join(TMP, "vgen.py"), tfile, MODEL, lora or "none", tag, G, L,
        n_prompts)
    env = dict(os.environ, CUDA_VISIBLE_DEVICES=str(gpu), TOKENIZERS_PARALLELISM="false",
               R3_CLONE=CLONE, TMPDIR=os.path.join(TMP, "tmp-" + tag))
    os.makedirs(env["TMPDIR"], exist_ok=True)
    key = (str(gpu), tag)
    with _LOCK:
        GPU_PEAK[key] = 0
    log("VGEN START", tag, "gpu", gpu, "lora", lora, "exists", os.path.isdir(lora or "/nonexistent"))
    t = time.time()
    rc, tail = sh(["bash", "-c", inner], env=env, cwd=env["TMPDIR"],
                  timeout=max(120, int(min(remaining, 25) * 60)),
                  logfile=os.path.join(OUT, "trial-%s.log" % tag))
    recs = []
    try:
        recs = [json.loads(l) for l in open(tfile) if l.strip()]
    except Exception:
        pass
    mine = [r for r in recs if r.get("tag") == tag]
    with _LOCK:
        peak = GPU_PEAK.pop(key, None)
    ok = [r for r in mine if r.get("phase") in ("forced", "natural") and r.get("status") == "OK"]
    RESULTS[tag] = dict(tag=tag, gpu=gpu, kind="vgen", rc=rc,
                        status="PASS" if ok else "FAIL", wall_min=round((time.time() - t) / 60, 2),
                        nvsmi_peak_mib=peak,
                        phases={r.get("phase"): {k: r.get(k) for k in ("status", "tok_per_s", "secs",
                                "rollouts", "rollouts_per_hour", "len_mean", "with_lora",
                                "n_valid", "n_fence", "error")} for r in mine},
                        error=None if ok else tail[-600:])
    event("trial_done", **RESULTS[tag])
    return RESULTS[tag]


def run_trial(gpu, tag, G, L, steps, fast=0, forced=1, n_spice=0, gmu=0.7, extra_env=None,
              pdbs=1, gen_chunk=0, fake=0, save_lora=""):
    tfile = os.path.join(OUT, "trials.jsonl")
    remaining = left_min() - 3
    deadline = time.time() + max(60, (remaining - 4) * 60)
    py = VLLM_STATE.get("python") if fast else PY
    args = [py, os.path.join(TMP, "r3_trial.py"), "--model", MODEL, "--tag", tag,
            "--out", tfile, "--G", str(G), "--L", str(L), "--steps", str(steps),
            "--forced", str(forced), "--fast", str(fast), "--gmu", str(gmu),
            "--n-spice", str(n_spice), "--deadline", "%.0f" % deadline,
            "--prompts", os.path.join(TMP, "prompts.json"), "--pdbs", str(pdbs),
            "--gen-chunk", str(gen_chunk), "--fake-gen", str(fake)]
    if save_lora:
        args += ["--save-lora", save_lora]
    inner = "source %s && exec %s" % (ENV_SH, " ".join(args))
    env = dict(os.environ, CUDA_VISIBLE_DEVICES=str(gpu), TOKENIZERS_PARALLELISM="false",
               R3_CLONE=CLONE, R3_PDK=PDK, R3_SPICE_BUDGET=str(SPICE_BUDGET),
               R3_REWARD_LOG=os.path.join(OUT, "reward-%s.jsonl" % tag),
               TMPDIR=os.path.join(TMP, "tmp-" + tag), OMP_NUM_THREADS="1")
    os.makedirs(env["TMPDIR"], exist_ok=True)
    if not fast:
        env["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
    if extra_env:
        env.update(extra_env)
    key = (str(gpu), tag)
    with _LOCK:
        GPU_PEAK[key] = 0
    log("TRIAL START", tag, "gpu", gpu, "G", G, "L", L, "fast", fast, "left_min %.1f" % left_min())
    t = time.time()
    # per-trial cwd: unsloth writes its compiled trainer cache (unsloth_compiled_cache/)
    # into cwd, and the vLLM venv runs a different transformers -> never share it
    rc, tail = sh(["bash", "-c", inner], env=env, cwd=env["TMPDIR"],
                  timeout=max(120, int(remaining * 60)),
                  logfile=os.path.join(OUT, "trial-%s.log" % tag))
    wall = round((time.time() - t) / 60, 2)
    recs = []
    try:
        recs = [json.loads(l) for l in open(tfile) if l.strip()]
    except Exception:
        pass
    mine = [r for r in recs if r.get("tag") == tag]
    tr = [r for r in mine if r.get("phase") == "train"]
    ld = [r for r in mine if r.get("phase") == "load"]
    if tr:
        status = tr[-1]["status"]
    elif ld and ld[-1]["status"] != "OK":
        status = "LOAD_" + ld[-1]["status"]
    else:
        status = "CRASH_rc%s" % rc   # e.g. -9 = host-RAM OOM kill, TIMEOUT
    with _LOCK:
        peak = GPU_PEAK.pop(key, None)
    RESULTS[tag] = dict(tag=tag, gpu=gpu, G=G, L=L, fast=fast, forced=forced, rc=rc,
                        pdbs=pdbs, gen_chunk=gen_chunk, fake_gen=fake,
                        status=status, wall_min=wall, nvsmi_peak_mib=peak,
                        steps_done=(tr[-1]["steps_done"] if tr else 0),
                        s_per_step=(tr[-1]["s_per_step"] if tr else None),
                        s_med=(tr[-1]["s_per_step_median_excl_first"] if tr else None),
                        peak_alloc_gib=(tr[-1]["peak_alloc_gib_max"] if tr else None),
                        error=(tr[-1].get("error") if tr else (ld[-1].get("error") if ld else tail[-600:])))
    event("trial_done", **RESULTS[tag])
    return RESULTS[tag]


def passed(tag):
    r = RESULTS.get(tag)
    return r is not None and r["status"] == "PASS"


def gpu_queue(gpu, plan, lock_state):
    """Pull the next runnable item from the shared plan; run it on this gpu."""
    while True:
        if left_min() < 7:
            log("gpu", gpu, "stop: budget left %.1f min" % left_min())
            return
        item = None
        with lock_state["lock"]:
            for it in plan:
                if it.get("taken"):
                    continue
                if left_min() < it.get("min_left", MIN_TRIAL_START_MIN):
                    it["taken"] = True
                    RESULTS.setdefault(it["tag"], dict(tag=it["tag"], status="NOT_RUN",
                                                       reason="budget"))
                    continue
                ok = it.get("when", lambda: True)()
                if ok is None:          # prerequisite not decided yet -> skip for now
                    continue
                if ok is False:
                    it["taken"] = True
                    it["skipped"] = True
                    RESULTS.setdefault(it["tag"], dict(tag=it["tag"], status="SKIPPED",
                                                       reason=it.get("why", "")))
                    continue
                if (it.get("fast") or it.get("kind") == "vgen") and VLLM_STATE["status"] != "ok":
                    if VLLM_STATE["status"] == "pending":
                        continue
                    it["taken"] = True
                    RESULTS.setdefault(it["tag"], dict(tag=it["tag"], status="SKIPPED",
                                                       reason="vllm venv: %s" % VLLM_STATE["status"]))
                    continue
                it["taken"] = True
                item = it
                break
            pending = [it for it in plan if not it.get("taken")]
        if item is None:
            if not pending:
                return
            time.sleep(20)
            continue
        if item.get("kind") == "vgen":
            run_vgen(gpu, item["tag"], lora=item.get("lora", ""))
            continue
        run_trial(gpu, item["tag"], item["G"], item["L"], item["steps"], fast=item.get("fast", 0),
                  n_spice=item.get("n_spice", 0), gmu=item.get("gmu", 0.7),
                  extra_env=item.get("env"), pdbs=item.get("pdbs", 1),
                  gen_chunk=item.get("gen_chunk", 0), fake=item.get("fake", 0),
                  save_lora=item.get("save_lora", ""))


def decided(tag):
    """None until tag finished; else whether it passed."""
    r = RESULTS.get(tag)
    if r is None:
        return None
    return r["status"] == "PASS"


def not_passed(tag):
    r = RESULTS.get(tag)
    if r is None:
        return None
    return r["status"] != "PASS"


# ============================================================ main
def main():
    os.makedirs(OUT, exist_ok=True)
    os.makedirs(TMP, exist_ok=True)
    rows = json.loads(zlib.decompress(base64.b64decode(PROMPTS_B64)))
    json.dump(rows, open(os.path.join(TMP, "prompts.json"), "w"))
    open(os.path.join(TMP, "r3_reward.py"), "w").write(REWARD_PY)
    open(os.path.join(TMP, "r3_trial.py"), "w").write(TRIAL_PY)
    open(os.path.join(TMP, "spice_bench.py"), "w").write(SPICE_BENCH_PY)
    open(os.path.join(TMP, "vgen.py"), "w").write(VGEN_PY)
    log("prompts:", len(rows), "cells from", rows[0]["source_lib"], "k=%d" % rows[0]["k"])
    summary = {"prereg": "kaggle/PREREG-RL-READINESS.md#R3", "model": MODEL, "pins": PINS,
               "vllm_pins": VLLM_PINS, "budget_min": BUDGET_MIN, "repo_sha": REPO_SHA,
               "pdk": PDK, "spice_budget": SPICE_BUDGET}
    stop = threading.Event()
    sampler = threading.Thread(target=gpu_sampler, args=(stop,), daemon=True)
    sampler.start()
    try:
        env_log()
        preflight()
        summary["clone_head"] = clone_and_bootstrap()
        check_fence(rows)
        spice_bench()
        cons, pins = constraints()
        if not install_main(cons, pins):
            sys.exit("[r3] main stack import check failed")
        vth = threading.Thread(target=install_vllm_venv, args=(cons,), daemon=True)
        vth.start()
        predownload()
        # push-2 lessons (run2): vLLM colocated with training cannot fit 14B on one T4
        # (unsloth: KV cache 0 GB, max_model_len 256); HF generation of 8 x 2.5k tokens
        # OOMs next to 10.6 GiB of weights; the reference-model forward (beta 0.001)
        # hit the memory wall at G=4. -> beta=0, micro-batch 1, generation in chunks of 4.
        LM, LF = "/tmp/r3/lora-main", "/tmp/r3/lora-fake"
        plan = [
            dict(tag="H-G8-L1024", G=8, L=1024, steps=2, n_spice=3, gen_chunk=4,
                 save_lora=LM),
            dict(tag="F-G8-L1024", G=8, L=1024, steps=3, fake=1, save_lora=LF, min_left=7),
            dict(tag="F-G8-L2048", G=8, L=2048, steps=2, fake=1, min_left=7),
            dict(tag="F-G16-L1024", G=16, L=1024, steps=2, fake=1, min_left=8),
            dict(tag="VGEN-G8-L1024", kind="vgen", lora=LF, min_left=10),
            dict(tag="F-G8-L3072", G=8, L=3072, steps=2, fake=1, min_left=8,
                 when=lambda: decided("F-G8-L2048"), why="F-G8-L2048 did not pass"),
            dict(tag="H-G4-L1024", G=4, L=1024, steps=2, n_spice=1, gen_chunk=4, min_left=14,
                 when=lambda: not_passed("H-G8-L1024"), why="H-G8-L1024 passed"),
        ]
        st = {"lock": threading.Lock()}
        # GPU1 takes the MAIN first; GPU0 starts 30 s later (takes G4 or vLLM)
        t1 = threading.Thread(target=gpu_queue, args=(1, plan, st))
        t1.start()
        time.sleep(30)
        t0 = threading.Thread(target=gpu_queue, args=(0, plan, st))
        t0.start()
        t1.join()
        t0.join()
        for it in plan:
            if not it.get("taken"):
                RESULTS.setdefault(it["tag"], dict(tag=it["tag"], status="NOT_RUN",
                                                   reason="budget"))
    finally:
        stop.set()
        summary["vllm_state"] = VLLM_STATE
        summary["results"] = RESULTS
        summary["wall_min"] = round(el_min(), 1)
        try:
            json.dump(summary, open(os.path.join(OUT, "summary.json"), "w"), indent=1,
                      default=str)
        except Exception as e:
            log("summary write failed", e)
        log("SUMMARY", json.dumps(summary, default=str)[:4000])
        # keep kernel output lean: the ngspice prefix + env file are not results
        shutil.rmtree(os.path.join(WORK, "ngspice47"), ignore_errors=True)


if __name__ == "__main__":
    main()
