"""E-e data builder (box side): SYNTHETIC fine-tune smoke rows for the Kaggle
QLoRA feasibility kernel (pre-reg kaggle/PREREG-BENCH-V12-AUDIT.md, E-e).

Rows are built ONLY from the OLD gf180 failure library kaggle/editcap-lib-v1a
(legacy, non-bench-v1.2) using the REAL arm-B prompt builder
(editcap_run.build_prompt_B), paired with the archived Qwen completion for the
same cell from campaigns/editcap-v1-baseline (content only). The kernel pads
the <think> block with the cell's archived diagnosis text to reach an exact
sequence length (4096 / 8192) -- the rows are for VRAM/throughput measurement,
not for learning anything.

Held-out fence (pre-reg): refuses any bench-v1.2 cell (kaggle/editcap-lib-v12-*)
and any text from kaggle/claude-solutions/templates/.

Writes rows.json next to this file AND embeds it (zlib+base64) into kernel.py
between the ROWS markers (a script push uploads only kernel.py).

    python kaggle/kernels-editcap/bench-v12-audit-ee-ftsmoke/build_rows.py
"""
import base64
import glob
import json
import os
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "kaggle"))
import editcap_run as E                                             # noqa: E402
from spec import Spec                                               # noqa: E402

LIB = os.path.join(ROOT, "kaggle", "editcap-lib-v1a")
BASELINE = os.path.join(ROOT, "kaggle", "campaigns", "editcap-v1-baseline")


def fence_sets():
    held = set()
    for d in glob.glob(os.path.join(ROOT, "kaggle", "editcap-lib-v12-*")):
        held |= set(os.listdir(d))
    tmpl_txt = []
    for f in glob.glob(os.path.join(ROOT, "kaggle", "claude-solutions", "templates",
                                    "**", "*"), recursive=True):
        if os.path.isfile(f):
            try:
                tmpl_txt.append(open(f, encoding="utf-8").read())
            except Exception:
                pass
    return held, tmpl_txt


def main():
    held, tmpl_txt = fence_sets()
    rows = []
    for cell in sorted(os.listdir(LIB)):
        d = os.path.join(LIB, cell)
        if not os.path.isdir(d):
            continue
        assert cell not in held, "FENCE: %s is a bench-v1.2 cell" % cell
        anchor = open(os.path.join(d, "anchor.net"), encoding="utf-8").read()
        ev = json.load(open(os.path.join(d, "evidence.json"), encoding="utf-8"))
        spec = Spec.load(os.path.join(d, "spec.yaml"))
        messages, _ = E.build_prompt_B(spec, anchor, ev, E.K_EDITS)
        raws = sorted(glob.glob(os.path.join(BASELINE, "*", "adjudication", cell,
                                             "B", "raw_output.txt")))
        if not raws:
            continue
        raw_path = raws[-1]
        answer = open(raw_path, encoding="utf-8").read().strip()
        diag_p = os.path.join(os.path.dirname(raw_path), "diagnosis.txt")
        diag = (open(diag_p, encoding="utf-8").read().strip()
                if os.path.exists(diag_p) else "")
        think_seed = ("The binding constraint is %s. %s Let me reconsider the "
                      "anchor topology device by device and check which edit "
                      "moves the binding metric without breaking the others."
                      % ((ev.get("worst_margin") or ["?"])[0], diag))
        for t in tmpl_txt:  # no template netlist may leak into a row
            body = t.strip()
            if len(body) > 40:
                assert body not in answer and body not in messages[1]["content"], \
                    "FENCE: template text in row %s" % cell
        rows.append(dict(cell=cell, source_lib="editcap-lib-v1a",
                         answer_src=os.path.relpath(raw_path, ROOT),
                         system=messages[0]["content"], user=messages[1]["content"],
                         think_seed=think_seed, answer=answer))
    out = os.path.join(HERE, "rows.json")
    json.dump(rows, open(out, "w"), indent=1)
    blob = base64.b64encode(zlib.compress(json.dumps(rows).encode(), 9)).decode()
    kp = os.path.join(HERE, "kernel.py")
    src = open(kp, encoding="utf-8").read()
    a, b = "# >>> ROWS (generated by build_rows.py)\n", "# <<< ROWS\n"
    i, j = src.index(a) + len(a), src.index(b)
    src = src[:i] + 'ROWS_B64 = "%s"\n' % blob + src[j:]
    open(kp, "w", encoding="utf-8").write(src)
    print("rows=%d  user chars mean=%.0f  answer chars mean=%.0f  blob=%d B"
          % (len(rows), sum(len(r["user"]) for r in rows) / len(rows),
             sum(len(r["answer"]) for r in rows) / len(rows), len(blob)))


if __name__ == "__main__":
    main()
