"""bench-v12-audit E-e -- QLoRA fine-tune feasibility smoke on Kaggle T4.

Pre-reg: kaggle/PREREG-BENCH-V12-AUDIT.md section E-e (frozen 2026-09-26).
Question: the LARGEST Qwen3 that can be QLoRA fine-tuned on Kaggle T4 at our
sequence lengths (4096, 8192), plus the round trip back into our inference
stack (LoRA -> merged -> GGUF Q4 -> the kernel's llama.cpp llama-server).

Flow (every phase time-guarded, EE_BUDGET_MIN total):
  0. env log (nvidia-smi, torch, disk, RAM); start a CPU build of llama-quantize
     from llama.cpp tag b10636 (== the attached llama-server build) in background.
  1. pip-install a pinned unsloth stack WITHOUT touching the image's torch
     (constraints file pins torch/torchvision/torchaudio to what is installed).
  2. trials (each in its own subprocess, so an OOM cannot poison the next):
       14B dynamic-4bit, ONE T4: seq 4096 x10 steps, 8192 x10 steps
       14B plain-4bit, ONE T4: only the seqs the dynamic quant failed
       8B  (fallback ONLY if no 14B passes 4096)
       32B plain-4bit, BOTH T4s via a SUPPORTED split (unsloth
           device_map="balanced"; else HF+peft device_map="auto") -- only if
           14B passed 4096; seq 4096 x5, 8192 x3.
  3. round trip for the largest passing model:
       <=14B: unsloth save_pretrained_merged(16bit) -> convert_hf_to_gguf ->
              llama-quantize Q4_K_M -> llama-server loads it -> 1 completion.
       32B  : merged fp16 (~65 GB) does not fit Kaggle disk -> LoRA ->
              convert_lora_to_gguf -> llama-server (our Qwen3-32B Q4_K_S GGUF)
              --lora -> completion with LoRA scale 1 and 0.
     If time remains after a 32B round trip, the 14B merged round trip runs too.

Training rows are SYNTHETIC: real arm-B prompts built from the OLD gf180
library kaggle/editcap-lib-v1a (non-bench-v1.2) + archived v1-baseline
completions, padded to an exact length (see build_rows.py). No bench-v1.2 cell
or claude-solutions template is ever used (held-out fence).

No repo clone, no GH token: the rows are embedded below. Outputs (small only)
in /kaggle/working/ee/; all large artifacts live in /tmp (not kernel output).
"""
import base64
import glob
import json
import os
import re
import shutil
import signal
import subprocess
import sys
import time
import traceback
import urllib.request
import zlib

T0 = time.time()
WORK = "/kaggle/working"
OUT = os.path.join(WORK, "ee")
TMP = "/tmp/ee"
PY = sys.executable
BUDGET_MIN = float(os.environ.get("EE_BUDGET_MIN", "130"))
LLAMACPP_TAG = "b10636"   # == the llama-server in devavratpatni/circuit-repro-llamacpp-cuda
PORT = 8081

# ---- pinned training stack (PyPI latest mutually-compatible set, 2026-09-26) ----
PINS = [
    "unsloth==2026.9.11",
    "unsloth_zoo==2026.9.7",
    "transformers==5.5.0",      # unsloth 2026.9.11: transformers<=5.5.0
    "trl==0.24.0",              # unsloth 2026.9.11: trl<=0.24.0
    "peft==0.21.0",
    "bitsandbytes==0.50.2",
    "accelerate==1.15.0",
    "datasets==4.3.0",          # unsloth: datasets<4.4.0
]
# --no-deps fallback: unsloth + zoo runtime deps minus xformers (optional; T4 uses SDPA)
NODEPS_EXTRA = ["cut_cross_entropy", "torchao", "tyro", "msgspec", "hf_transfer",
                "sentencepiece", "protobuf", "diffusers", "structlog", "typer",
                "click", "rich", "pydantic", "nest-asyncio", "regex", "pillow",
                "huggingface_hub", "safetensors", "psutil", "wheel", "packaging"]

M14_DYN = "unsloth/Qwen3-14B-unsloth-bnb-4bit"
M14_PLAIN = "unsloth/Qwen3-14B-bnb-4bit"
M8_DYN = "unsloth/Qwen3-8B-unsloth-bnb-4bit"
M32_PLAIN = "unsloth/Qwen3-32B-bnb-4bit"   # the -unsloth-bnb-4bit 32B repo is 39 GB
TARGETS = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]

# >>> ROWS (generated by build_rows.py)
ROWS_B64 = "eNrtfQt320aS7l/Byc7ZSLIIox94KZO9x5GdjO8otkfyZO/sek8MiZDMNUVqScqOMzvz229VvxtoQJStt+GzOxFJoIGu6uf3VX/1n3//5qieTr/Zib45nE1HSTkaT6qT0Sr5Zjv6Zjk/XxzVv04nh/h7PZ6sjqqzEXwcfSAVXlDNlh/rxa/LxRFe8L46OZnWj4+q07NqcjJbPtZ3fCCjw2pZTyez+vFhtTp6N6oeV+P/Ph9PjqrVZD577D/68Q+PF9XHX+fnq7PzVbz6bSXe5dNyVZ/iY/42P4+qRR1VM/i/ajo/iZ7vRuN6CY+sF9GihocvJrOTqIqm84+j2XyyhGtPz6aT4wn8vrH34slmtHpXraIfnzzfe/Y0mqyW0fKsPoLf5etE1fEKrjw+n06jg1fPd59Fy8nvUGIc4aMXdbXEaw7h/aCcOjquJtNz8T7j6GwxP5vD8w5e7/919/Vf95/sRRsr+Are8tNmdPSump3US1mOrF70+uWrl3svf/pb9PLF3t+iagmvvTyt4MlordF8Malnq3oczerVdLJcfQc/j+cfZ8sVvMYp1Bpe9HQyg18mR9FqPp9Gk9myXkCNDifVUlgB3gpev15G9Yd68Qlu+TA5qqOPk9U7KEtWb362mpzCNYs4eoFXQSEf4LH62g/V9LxebkdPdyPZIuDv+UI8Ad/r43zxfhmNRtF8Nv0kLHI0n83qo9Xkw2T1KUbnncM7oeu+//57eOSz3WjD9/hmBL+8mYETjxaTM/TBTqQbz2E9gwbzgUTguKhMktN3v0d4W7QCd+5ESVySNPrpT7+L3zcOKPm37wmNXvz4x+9ZnETPx+M/fk+S6ICQP34/Isnmm9khmGQnmlWLxfwj/r0dHSffQyGJ+Af3/On3N7OTCq0OFQFLV5PZarnzZhZFs+Nfx4eR+Hda/RYx/G5JiP4Sv4NniG+p/XYyiwjFLyfj8a+nlbkUr3wzQ5s8ebH7p5f70Ytnr/eeH7yGJqOaFb7CZHF0PlltY52nYNToeL44VfZ6+/atahdvZlvRdFaNKjKazMbj+qSejY6q5dF8XO+AN8fn6I16+mkkfqoXsnbygmj3AG0XYxl70OiqE7jn4F1VHx9DU/jXaK+ut6M33zyJSJyOftkW/0F77/78Em6cf4xeiC72RHexN99sY1H/9+BgNyJlmcfRD9qFFfx3vvgugjYG48DkNJofiwYD3QYaXPQhiWlU/wZtGvp1dESwmI3F/Hw2HhHz/Xb0cRqNj8ZVmpCSjPOjtM4ZvFXymPLo5JgUSaR7XHS0wFa0Kap2sFqAFaCjjrCdbkf/8Wz/JTj49Gw+w7YuG3kcvTo/BIO+A/P88PzJAbrk31/u/xlsONKl7mBpR+eLBdw2Op1AM8JRB2wFtayjjX0Sjf4NvIWWffEz24yO63q8FNWczLDHY9OCj1Cvk3fRPv0Oi5O/PN0dHU7nR+/h4Ru7ZPM74yFxC4xYvzx9Gm082Y1OhFFkvZ6cCeuNI5rQDPsU4dC90OKRuCoi6L1KXhXByPLmG7xxN9ol0S/PX5BoBs1wL9rDP6IZ2PwF+vXFz/CZwudoxqJfDg7EJdR8UNfAF1y8FFyqL2LyCy4eIS94+dfXUO5+BKYRv6WmAAYf8P/gZlkAXETFd0Q0b91BcKj+6/6z6Nkvz58+ewFDFnSRyVJ3jugjjEQ4yI3FcPfz84ODZ09VHzmE1o/j4AYMU8vVptOld0zXPa0WJ5PZ96MkzrI8K6KNGfSxaooFfgcjHFgfOg8UJ/okFAaDyDHMApPDKfSUH6sptP4IGt0KGq2cKWCshW9xVsHHEJqInn5WL0b28eqpy2ijOno3qdGDH5bC09uRfb66alMMP6f1agHjPP4z9+jRCK+K9L/l+dnZfAF9vDFo0bjMYXDU/2CwS8rMfHy9OK8bI9qIxYwyc4exUOMGO9jlcUI4iZwbOEl5Sf0bnIGQwEsQGMHtDYnzWd7wZgbD+I6ts77n9InrKm0EVQQv7b+CczSu6IPy0TCz+K6d47x3eD4+qcV4AR7G6V80KpiClitlfHCXHrzQJ3/H2rz5RlrsDUxxymDb9nsY6Z3fwBj6N6rvkTZzvoYZQ/2UwezGMvWTfHX8WhlAfS8cjF9L95qCqH5uEeeMFc73zjsVMYyjqXlfc09axiRP9E3vfz1O8OuSxWVR5uZbeFPxdRKzvNSlnJ6rq2mcQ/uy36qraZyxzPkalo/qBhLzjPg/qHvwF/XDuJ6uKnUDTBhpkns/QN30L7kx6qo6/BXnevzlP9+IjlImVM/42+obWuhv8Iv/cjwCq5Kzaa1sk4BlSmaNDy3j3VwUDRfXsGJb/rpYvvnmzewf2I7+9vKv+9HrJwd/ho6+OI1+wGZD4ujp8yc/vXh58MxbQkLrhWFqvNyJPuICFUa4s3eflrAsncLKagprtBUOLniHHtac8QRuFosvNSbCAvVD/X/ezCjMaWpV+uz/Pdl9DatM5q5PcYZc4sLzx7/u7el15lKXplcdhzUspuPoGfRBcQe+WyWmzymsQfVt2B1XuESdHB9vbkc1Xr1U866ow9PnP/74bP/Zi9fR8WJ+Kp4g1wRi4DbfzeF/FvLNoC+yOHoiVuTPnuz+SXy7DaWKKTF6tf/s6fPd17CMH08WuOaEpfmTF09hLDiZTVbnMHfCesmzmBpEN+oYFvTfqrFuciqmR1g2f4r+yaLxD9/KQeAZmFxWQ1Z6JnYLL//9BczqMNuPI7sEi8TULe7S6zjw8d6zXVjPzQ/rT7CAqY5WuPKABYdeWsOUIBb6cnx//bdXz2Bhegr2hFmfiP+l0X/if5j4wP/LXAav8necRLejV+J/97ej3e1o7x8xXoE/PMbvo1X1vo64uFn4FFoXPPJp9FN0EP3wXbT/ePfxnryIqoteRS9kGTUseuUKYUMsT8ChYiaH6oitC35++nRbzN0bakUC+5PZJ3iOWsJhibJCwqMfYZ0IW4yX/sZCfPOL3lqIT97WQuwgYLqfvf91CUsp3Ee87ugBSzV3xRGsWnHIhoUZ/j7BSjuNzSwQ1Yscmr+wGR69q4/eQw+caLefiqYRaES4i8Jt4CHsxt7rrimqKt9a7o/xjf2l+jMslexET8awOXt3LjovrtGxH6zUYhDbbT2DHSM2M2if9Rj/hIYN+2d4VN8KDv7m8hd3sXZHFnRbW69wVX6EOxDYlemudwpLpa2tHdn7oo2GVaA+sJaHLg8jYoVDST0F18I+XNhEbGbBGKs5jFMrHCmO8PupsiTM9dXRZCUuBfMe4yawuXkSHqE70X59Nq3gOr3yFkXDMHc6n41kCxVNpGo57vP9YUwlzUuv17xcmFdXb1FD267QllALZdzlBMEEz2izVjOFCpkxU1pZNMwuyzLV1sXs6DV2sbUR4wQ2+PEnGC3g6WIAWJ3P1mnos3vZzGmcyobeMAlUyLMK4mQ4H2vL2JEABqgpjgcw8sH/i6FQeRV2f/UxTFSb3/xjO+oA+MjtAXxkAPi+MoCPXDXAxwXAh31IAHzF9eB7UP76CB8PIHzF1QN86UjORliBHT0zieFCDsPCSOTxySksSubVGA2ghmZYHUKHqcZLH+lzi8D7RuJqLGc7ejKdLlfz1WgJq6a5bLFwj1o7m/KxuN2f8A5oN693nxw8Ftjf7k8jtZKBgWv6abOFA26DPf49AvvPTKvAymNx9t0fi04u/jzCPTo8P14Ty/NQvx18RZwdRMdA+x/Axgz6RuVic4iaqOWui8bB/PMIS5O9Q1nIDtli5YFTAQ7xk7FeCEJ3WtTw7Bksi2Eug3LG2NaEE4QLqLjv6dPv9FjhPlL+iFOQC0o6OKQAKLEchVHuXAaUXMLqXnVl6/6nu1ichiYRt8RFFrQ+KGyffieul01tGT3ZHck1P1wkls9H8/OzqZyFzqLdw09nAr2diQeDbeCR80jvG8Ep/pNhsN7/8erhzOC6IHHWBXIN0LP0Yu6Uz9Q6wp3ymZjyd0WNzVLk+pFL2kQuc1akGX/I0GWap7kLLCYsoUUPdEnyOOecGawzdz6FoEsWZ1niQZfKpl3QZR6XSZG5aCohnPZDl+qeMHKpS0jMP1LcFG6prBUGLuFHnhZlC7mUJgsilyxOucEcLXIp698GLtG5beCSkJgSAxU2kEv4kZCkbEOXNI3zsmxCl2lcFLxoIpdwaZoGgMuizPIAcFlkpAwBl2lM0qwIIpdpnGSUBrFLQggNY5eEsOvCLimhZMAuB+xywC7vHHZJJXb5L//yL9FT2ADN5rD2gn4667hl46284+0m3g1L6JXqbbgqWyxhyb4SbYIkMTaLbVyxih0wFAOz9/kx7IcnYr08h8HnBNd2k1kcvW6sCs16czJ7h+vJle7PS3FDND7Ha0Tjgn6m1vNzsTgWOIXYjWwa4BI7FRQL5WG3UQtfXBKLDfhrsRRX8Qria9jQ00144PsanouDzRKfJsG/lQgdgIYIP8GYgxvFn//0+7YoGfsNbpCn9WgpagfvdDw5gc4sOtq0OoJNrWMEhSBIhEC+iIQWxE1izSunaWFiZ9rdhv+upCkmSxXOMIFLP0WH89VqWsNOWXat0WiE/0H3agB4VyE2B6tKrvql3Q8k0giu13hkc6mutvca8fERSllf9MkMUdOl9Kxrb4MixXcNKB8a/9D4b67xR10Yi46dcmKkcDJ+NznB2R1L3G64av09aGL3kBaPZog4O3C0xKyfPtV7U/Z5cDS3e1Pu7E0NOg3uRjhadyZ/MVF4XIG2p2r5HyaVNkfTrsLYJ6fR6fl0NYGGJZvVZrAd0J3o9cf56EB4zW8Bws3q7x/nU+hf8CzwGDIJVbTEAWus3L2hnH+sLtsUXNC5iGATCJh8k0+ql3e5HSZt2V92IvMnuv6RRn50+Z/lbOlVKkCFhlMb7cClhJjx3OU8n1zK1Zlwta20cPE6/mM70XPTD16p0R3ufSnbxB4OYo2uLAem4EinenaDFBkpMmqO6P7uJqw85WPUKgt9rZhShxS0Q2K3v6dHqqidaG/XFCtW3QKvcwboz4aYwg6XjmWigwrySRJSn8E2haCn9XwuqUBlsRVaQDgCNqGCLFgG+rVgT+MeWoleF61Un56toE2MFvXifNZDLtGBXPrKyCV61eRSpsglFT2eaXKJXi25FKSWaIhaygLUUjZQSwO1NFBLA7V0A9RSwdPyQVNLGS+4S/wwymlfVDwp4jLPiSF+0qJF/DSoJc6z1KOWpE27qKUsTsqMemwXyRLGWA+1pO7pDoqXJeh/NL8xaklaq4NaKuKMURKgltBkHdQSIzlrUUuy/m1qCZ0bpJZIWXYwS7AscG5ymKUspoUJRNfMUhazIqdNZgku5QFiqaRZGSKWclaEiSWwHO8glrLU0F8+sZSUJhi/SSwl18YrMUOADbzSwCsNvNKd45Wgh21tGWwdcYGOe3TX25B3CoRdAd1yPSuhcIF4C6BIHeMMAedtSF0CTO+gNqL3QoNpoeYhsNYC2yHg6LT6FGE/M9C42JWK/uUCQfguMLMg8KEx6+NqIXuyKJsIIGwFkyZi212cgQ+XK1jsrjEpg7uv1d0dke7IawT4CLE1bNbEYRMQU5q5dpOHe39SWyIx2Gyr8QC/0Buk2EFfRaEw1sutoIXrW7SHt6chek9DxHal63CCxjIdSuJq9zROwDy2VbV69iYhkgjEUkyJyq3QRv9J5N+bF3iGWsZJz7/Q5t2mKl79kZg8NPGz6dI+AUNuCVtttMCSTfDCBN/bLSzaePUzgSkCHSX3tnuwElFIObRb+FU671K7TmNh8SgsQ1jZOGs9Mom7nuMeCSE9x7/IczTsuXQtz7FmnxK9qX1wSphfn6jY2zWs6yY41e97TucSgAySWbvEOegC5t7Y23XoBGwGprwm92d6XWfX6nXcnehbLOyhTHmoB/Nnt3eUhA1o/1eG9rOrRvsLgfYTfZSEXw/aTzqOkgTx/iKA9/MB7x/w/gHvH/D+q8b71UBl4f4if9jnSArCMxdZF/XtAfspiwtOuAH7yyLLC9YH9ics986RFIzQvFsCh8Ulo9w7R5KVDVWeJtiv7uk+R5KVifOPZjcF9itrhcF++JHmBrp3wX40WRDspzBnG5Tbgv2y/m2wH50bAPvBayXLOtH+vOShcyR5nCTmbTXan8e0MCI+Bu3PY0LyIgT3ExKC+wtCQnB/EXNqDov4cH8RkzJjYbg/Lzo0cJLc6O9cPd6fDHj/gPcPeP+dw/vFcHjXJXBwB3JI1A5E1nunEcndwEyNdCW27w1YlYErTdjvQsWraxWSLavk0gwc9x6y3fUAGHr0FRq9E0iPAwf+B9T7MkKK5OLVoo0DpnaNaBaBAQtSJ1S9VVGjHomWEjB0D5gpVsxjqwoqNlNywY4vNNG48lkFRc+PsWIwBL2rFjACiGe6DfZzVtEddb+BxXXArmw0PodFldqX7UT4yW7TVLPzGsxk5rcsbU8Vp263eEw0XAlSSiBTofrOJhD9JCeW39yG7QQ9XyCLw4J4Pl3LqsoqVr9GdXVHwmYpJ/Dd9furGEXI5k70VgxPjVBkEicjElMVkCw67lJACLbeonSNPo0bVtkUc/yu0wMM5C4eTLsenMQpRuOIB3edZtDiSEdz2BNPBdojnr4ppuWnoZYhn8q6n1pAdSWbcTpfCFstaqRqjmEBAAM8rAGgkTTq2APB8tuDYPkAwX5lECy/YgiWJgqCpRKCpRqCTa8Ygg2HXKcBCJYmAQiWDnLdg1z3INd9a3LdDaSSxCTnWf6g45JdeW5T4W6oEsbDouQO8liWPOHdUGUaM0pKX/KGlUnaCVXSGJqtFypNEkL7oUp1T2dcMpRAHK3u8sagSmmtMFKJv+VFC6iUBgsClWlMCk5bQKWsfSAq2Spje0rdBUt4l1J3VhZlUKk7KdO8AVPyOLVh1Qam5DEnbjixhil5kvEATMnShIZ1upOkSDuEuuEnHoQpWVqyMEzJMou/XjVMafXBB5hygCkHmPKuwZQyTFV2secHPWGqGy9+/B7GTYxGUlIYKki1/g1eZomTg9Ks0G0zAGVtwCpoU+6yzg9V0GgHZqFCWVshg/Aui7lEBKoxNDW4VNgPH43gGGy3pDSvH7zqwSE6ftUGmUKPw3XAAmqiyoKqQ/M/PMcblrJSsMz7Vq46FOYi2jBFC6qN6fNnwoR3MhR58PFV+rg7/ngfRb0dBAweAguhFZpxOcFZoHOLuXuw+aVbjasSMZeTxfOXL7C1yEVxAzFMbcCibDIyYDEm68UCC2xWonUmMuVYgN3EU4/R6KzFyS9tIKjfr6oY8e1tipJfZNckLjrsWqwXqYt2xT30YQXDiLUsFqcwNCgObYRN/MtaWxAQRbZjdHIr+QvVowdA9KsBRJXHLwuIyhMfFwGibXlzeiPy5nRdQHSQNx9iUoeY1CEm9QY0KApSlORBq5s7ChRS3ZxlUb+6ecnywsSM8pIXJO9VN6ek8KJShUn71M0pzRq5IvML1c3xns6oVCzBzct4g+LmaKxOcfOMURoSNweLdShQgLlpSNwcqh8QN+8QoKAF7ZQ2T1hBwtLmjOVtafPciJi70ubcTbNoQlKTPJSTsUjzLmnzMs87FCgQuw9LmyedChRW9PzqQ1JZOWC9A9Y7YL33XoLC1SJQk7vRWnaP5kvYz4RqyVP+swvkCTwBUlzhUrW0RbhPhnnaIleqy8PuVCgghKSW3Uf5Sstt2WhXb1r0VBFBCfXyogfli56cqkhLfAGlAu1Xfw4dp16ppStWXEgZ4F55pvbIMydoTh19NgiOQBUPzEggMJylwhbVJVtbbrLKKnLlQlfV7D3aQ4xIZu2/tXVvlTCGVnefW110IaIQPWqV9CW6vvq8PruZw/tKzLdHX0Fbx8oWWBWQRgOzDcrDdJXhHa2MVlg5TmDrWltzEHjP51jaSFpIGLyhacFv1+hd8uhhOXRoqCFLC20Lw88EDkA0osMvtHzPvZ26L4nvAGG85Hq1KbC49Zu3DJX2rWPmETOK9uvp9LAF5PZUq9ULDJzBV8YZkKvmDGiHanV6A6rVwRBqOqhWD4zBwBgMjMEtMQacpUX2oKPD0yzyVauL6ALV6jwxOVSTmPI84Xm/ajXxhSykTXtUq/PUZzGIkcXuVq2Ge3pEq910qEnCblC0Go3VKVrNiqwIilaTrnyojKYhzeo8DQSHp1lYsTop827GgNi7PMlqRtKyJVnNk4QEJKvTPKRZnYQlq2kaJgwyG47eJAzSvOgiDAjrkqym1xYcTkg2EAYDYTAQBneYMOi+aGtLzVYbAl3Z2tpWwHEgIyR4CPcRYnu4EgM1Qgof4D2xUS3q/zmfICJKEUiTz1xgCsmjCvZxOrXh1lYI3f12aSWSxSZNdPBK4hkXJYiExetIumHkHDjHm9WmZSva/3VvUyHIDaGAjT0ioGqzORiZ0/KYlRH78OF8vhSDjUxZqKFjLRFsCsIskyIppIUOEeVVqcCCuKF6JxMzbdJTTmu5LbFYq8pwiTtoT5TCTzB3h4W0hzb4lbXB7uh6JCTOKpwG62lkJIKVArGsk1ZZccwpBb+NtMUeVRo1loywlXKgZLD7tm+/K9naMfPhSzd2IemQSyC6Wm5YdIQ355SUVOp58/WD+F2OwcqfKwYLXRFws0Bo1H3VeKzWQE3V9m3tCW38vqSnX+gY7up3c2FtD3Tnt0RvhD1E1vOQOg7QSOeJTV1Z71igMqoT6IFDQEG7+i6vf7V7SDtvgEwFenX9RarpUHHSQvoivXFfZN2+KLUrgvwGjPez0exWTkOoRw/MxlfDbCiPX5bZwNuEXy/MyWkkYoxKN7sRiRi2blZOPkjEDBIxg0TMrUnE6J5raYAyL4ukeMg0AHFBd5RwSbN2LkpPJIbaCyJroi4aII8JKz3F7DRled4tEsNjsI531CBJkwtEYtQ93TxAqmFeJWh9cyIxaK0ukRiaOWot+h5psCALgIrSRg3G0gCy9m0egFh2wBeJSbrErIs4y53XtSIx8AOnzYMDZZxnZdmkAWBFyUrapgHSkoa0rFOjSt3UiKEF6dKIoUWHRIypWFMiJi2v7dhAOnAAAwcwcAB3jgMglz00AJuCUOz22Xy+UAsyi8hptEFCiBetqP34asxmWM1UkU1lXlzpjRAV1THcbuw09BuDd7gx3fAlAlQi8yAWLfBiCaWKIBd8EFYv+l5OOxo4NqDxSCTwUiCtzVy2Qj3Z/zmHBv4pUprC7upYh3eP5wKphWn3ZGYDglRYt9xTTevqgx6xZMyLMSXaFwpRb3vv82EOzeguNaOwQDc2CgXGi1qNmhijhyyuzmeKdFGWEvuaxO6WxN7pwt0SWWe3RK9cssVHBzsmOR2k5yUtXE1O3q1q2JA02uvmxcalO0ZBv0PfyBXTd+ItBXIuKuLY19o0aduUdNiUXZFN17YjdaPMnSq5x2nmHxFRs2jzYb3C5YyMgBQm2U/WMK9GxkWySRNTiApNkn+YH5um7A0kL3oOUqy71ReuuRXxoQs9QIQH4PUEKSPtgg1PJB0A68iliejcruFxAx/Gv8/AX6OzW8G/1aMH/Purwb+Vxy+Lf5+JMaUH/OZ+aD+9Jjmg9RNU8ptRRx9C+4fQ/iG0fwjtb4X2p0n5cBF9FtPChOUL+DzjlPUh+iyJ04RrHXcSp5wmedQd2E9R3NxTcRcWjXpk35MsyX15ooSlF8i+i3u6EX0swQL65KYAfWWsjgSVRVxy1tYCkhYLQvokLtM0Dei+Y/WbkL70bTBBZUZK0pmgkpVWKshLUJlnrdj+Is4LQz+8t+kj05yzNqhf5DQY3E/zoPJ7GWdph/I7mM7q0zcSVFqbNhNUcpZeF6zPh+D+AdgfgP0HoAb0Vt7x1tcEb0uyOEHNoq2KTXP0F7hNLF5Vd7F4lozK3aObOmhbqaWIJi8msgqWD536LgLqcoFf7CJTbDlH1Qw7mVImcCTAccM9DYYyGyTbge8EbBn3aabcW5B9cGmfDE6XsLsEZGExr1V2tOIL2E6EiQdkXo6TL9G4wV2BlLhhtyxxk3gSN/pYwLJH06Y7Zrzyo8Zdvfd2XtQvkK1RGTfBPFa25jr3YesYMvVkazSWuLwwwL3TpizQMpv788r2zi82KBc4M9pTfS1xZm7tfFumlXlEnbq2tGk8ha8ZngPpw63J7eHWgyLN14ZbkyvHrakK2i4auHVyxUHbRRC5TkLINR2Q6wG5HpDrAbm+JeSaEUrTB41dZ2npq8xzVpTd2DUtUHQkN9h14XzqwK5pyrwnSJt2YdckLhPm6djzgkb90ejqnk4deyjhVoLRlbE6sOs85oGUpdJgHdB1URhBGQtdy9oHoGuLNfvQNaeEdkLXpLTq9w50XcS8LFvh6GnhiNubcHTG0yKAXGdJUMeekGA4OriNchpEruG5JOFdyHXehVwbOP3qketiyFk6INcDcv2AkGspD3KBKshhLbU+uoTE3UhEgyyExMg3/ombhE1U8XgnIGHYprsS4I1oZYlVvN2jbzXMiTMWvIF8lZBoiKMwos98KoFzJxPnW1jQvRUxv3K53QB49RspXEApcEQOJqr26gJpmIF3pGZ5PRMYroJUPGlzxK8Q2hIP3FYon/hTALmi4YgaK5NOxA7kfserD23s3rSxcECwr5oOO7GLZcBlCKyPHbg7aVMvi822hNz9p6j9dCWPM8PoG3qilehYcyunrrjqzVxiNnPiAQGUFryIx92PVthxTA/xRTXenNOEsCKgLW4avuf4t1ILae+tODPh2PPbpQBlNi/rZp27WHe9xls88gTMO9zrSuA43QJDuqEZY6932A5RDRWhv5YHie9BGy0uwsTNVvqOeZZLz2ZfJNC/hgNxISrGSljGRoh4ex3rVJz4eTd/X1/QM+WgNqoFTCO7oUKG2w/YALdsowugh4qy0W/YNXd/VjhW07PCHfCJOpr/7cMC3W6Wd3YJSd2qn1PpZ0m7tG01np/DGN7oxOjrRf3fUK5Kwh1iYEiapyPYnJyMVskt5QZwX2HgYr4OLsb1+dpszMnZUqwB8D7FxpA4LcKHCJg+RECSC9kYfBtOL0vHsPXJmNAxApIMbMzAxgxszMDGXD8bw7MiRVM9VDaGxBnJqUN98CwpGes5SUCTmBaGXhE6LZZsCWoDce5L/SibdrExZZzTlLtsDM151s/GqHs62RgoIXWSCqc3xsZIY3WkCCjjkjtq/VYcCC3WIQ7EjQa+ZWNk7ZtsjHRtm42hBUz9CQ+zMRTzFofUgSiJiyTLGnQMjbMiadEx8C08uknH8JgSl11RF7O4oCSYJQBeJSVlkI5haAcWzhJQJkVHloCyj40haZY26BiSFtmafEzCMzLwMQMfM/AxDzmvcBcg7mirSwGIAMrdQq43EBm3WVSb6VMb0LeEriXascTbYJmlZdIb6jDOClpHuC9q+EqxDdUHqJSJcJcv14pvF6hJqSJ+sWfjyvC3CTwDRVz+EP3vya9/PyX/iN68ORpDB/+PX/++R//xv9EftoWk+8qNjTfh9nJbHRKHV6Iwy0+zGmbspeYljK67WNvBC+A9OlOuWFXBd1AtDJ1dmYFRh/ODjU5OHz8fo+XHsKU5PoZ9lHaom5+WCLFkKUFz/5WJhtY7tN7u8yG74fyoYvfePCHj5ko9m68kbLrZzBAL+zU5OJPgvtDs6/qyxLZQXbV/kNgftvZHkoL5J0ljIWUOS4nfjmDs151GWkFpVJ3Cq3otQ1XXl9bS+R9sUthT4eOGGaBrqiaP6wa1LBj7XeTCJASNTMkuaycmZWlwTT+M2wcrPtfq9lQE844/GLUf6w12CW9kyhtMekMZ2z0vswEPReJ3cpEC/x+iVmeEy/8R/SFIDpue2CLGmt1PeWodBzEYTT/OR2LoCLlIndZwPIUtpsF4X4GL/JNAlmEx6IibUOMy7lIHo/5JctdfK1NnB+k3WB6+ESLr1vgw/synqG4loCl8s8Nz5FM2TeYMdURoKfvRcj6FAXcph+TltuTL0eX69BD2P9hWNyIH8F6vd/VyL+T2uZfhHMzXx72Q6+FeaJxK7qW4JuoFHvBl5EsxcC8D9zJwLwP3cgPcS1GU6YOmXgru8hyMZpT3Zmcu46QomLmhdD51pGVIfZkoadJO6iWPizxJXeqFZKTw8zg0qRd1Tyf1Iku4+YMwylid2ZmzNMS8oME6mBeSlO20DLL2AeoFXNumXhiNCSvKDuqFx2WWhw7CUEwJUbaol4IYZsmhXvIyZW3qhSeuJJNhUcqEZ2HqheV53kG9sIx3UC950ZGagdhDO9fAvRQD8zIwLwPzcu+ZlyaOLM8QwP5oswPnDeOWCBGhbr7opPW4jV0rPBwWUCoq26LPEgB03qEtlqN3b74EEJT0FxU4qoV8TidLuaxW0vcSxhYdQCLh5pUdYAzqtXDU7xHiju47JzH4tdev/YmEA4H7r2TgfqcekQlWj79ASIc28chrVczxIrkPlG6OicYXAft+pL6eJIJ1b7aMzQuNTT2BokbLk6drfB3+ffGLTuMMXfEv4trPsvi+Kq2DHblpS8scB1ZZX7xb9WE+GS9dXmyJ14d7Rr282OIm8S/6KZRaWSDMxxfm4r68uQ2wLnMXmHwG15pF+WKz+6Jb+mBCUOHOQOtiMfBYrQH6gXJ640JR7sMHiPyrg8jpVUPkmZ/jILswx8FnQuTrJzkI5ffNBoB8AMgHgHwAyK8fIE9Txh82QF46Ok5JTFKb5CAMkBdxYaWbwEB5khWsFyDnvGjkLeY9AHmKEG3hAuRJyrIsy3sAcnVPJ0AuS9D/0pLdGEIurdWJkKcpD2YuBpN1QuQZbUHksv4BiLx0NKcsRM5ikuesAyLPY1oWQYQ8S43A1HsDYieUBA4n4AGQNkKe86SdupjHrGRhgDxNSNZ1NiEz2R4aAHmWsg6APDOJkK8BIM/y4XDCAJEPEPldhsi7L9raUlOWFO/Z2jJxwOj+EtzfhlGd2G5P2mBi4dPDT92qOjq6u9JqOmJBZCO228Cs6EliysMXc4DWDow1oK5zeg7NUgaG1kHc47GOxzZl3uFw/cGfX+DPfki8kqG4VrVFjv1ioyXSgKpzCf2a/Vt+HtdHujwZX+yFD0c/4RVQqhykJkr/6TfEaNBtov+LwYPFDzQZgJjscPEnThvMo38S2o787tbP2VZw3SeXAoE96q970VbUK4vUhOcbjdWmE0AcfmRbp9nFbuxDczbJLxQtsqVPQlitqybg7R0F8FAAPPXxuUD/l/tTtrYv8ynv8CmRPn3SNIYwUFd+AncgcJrAeoH3sj8rFsBqTzV1rlDNSGG44XwsTZeqROYv8BTCeDHBild9ZMOGeIKmGyqEOD6bQfO6rWUbxGpEqWJZwkF9zW48B0Xb+/pswMe5itnXbMsnFda/oS9/c54k4zyyHymFfTSB7ZI8nDOrq4Xu6YjD91MT7PZj+NlAUHx1BAW7aoKiUMksVAw/vyaCgnTE8AcpiiJAUfCBohgoioGiGCiK66coMpoWGXnIHEWR0NRlEGhCNB8Q5ihSTKlAnah/TqKeIP4szi0lIXM9S5t2cRQsLvOc+RxFlvdnYlb39HAUWc6tflKR3RhHIa3VwVGkYAvSDuOXJgtyFFmclbStoCTr3+Yo0LkBBaUMLk/yzjB+ykiIpGAxyQyjYkkKWrYTWmAmjSIQxg/rhTRAUlArhtRgKUjG0g6WgnDaEcbPsy6WIqXXR1LkbIjjH0iKgaS4Z3H8nYoy0CRm0M8uwqt7lWU0Qt2I1kaEulseQoVli6wGI73NlLG6NlRVZL39Xu/iupMDNOPE4YUQYYcNX4zYldztmhy71cqBooWnlAJGoBKVk/R3W6KTWJqBzUTy3/uVxHloCzfRFvrJEf34jV3YTwlCBKeJeip3mHuu5H8bMcc3UPUURrnyLYwQhNe/XQvgedCdGFrMhbA4NICn/BsGXYEQz3QzNIZQtvx22TSVZ6ELiAv3EIcjjXPtBziIG9/us0n8moPde1xRhD3BtScU7qENplc6XucJmsvExOvudTH3cMGJD2FHpX+jMQzFGcgBBv14pR66CYrvoJ8QcJ3CGk6RrGvAEheksHYF1fqZAH6bhxT4wAF8dRwAv2IOgCaKA6CNhNbpVXMA4WMKaYADoMmQ0XrgAAYOYOAAbokDKAv2gFMo2OwJBqDPsn4KABZZrsoOIfb6MAWQMEa9JwiTdlIANCY09zJgJxnL+ikAdU+YAlAlOBRAWdwYBYDW6iAAMoy1pwECAA0WJADS2BwgsPC/rHsT/qcKxvZzWaPiT9mVyzqPk5SXAeyfY97qpoQPh8ca8aD3Fs5PCpY1sX9Mk2ByPLgSPlnKOiR8MkKLDuw/zRkJY/9J2pHMmhDzqtcA/pd8AP8H8H8A/+84+C/72PODPsDXE5OXYuYe7GsU6pVcC17QkACeVQLy2Xj+5pySkv6yabDWJvTTRH4VKmHjdJ2WCGV8nIxhiY0i76EEw8dg8QrFw8HS4lX95MImeL4dfapU3W1ovQw8DciJS1S6OnrvxtSHcW8Vhq6RFLwGN2DyfVwJeCrgTfHGrgK6g39J/Pjp89c2hP4oKEkug2GxiwfUNra27iYNMbTKr7xVRj4e8aWSMFpyvV8m3+7EuLsT4wJV93divA+dlRPu85cvusK1xUkL3S57xHCijd0DZSoJJO7+JD9uho1OTfS9kDbysni3IHZ1jgddeBUG19kgcBcLf7NbN7LgJTBtu8+CQcd4tMc2LSXX5h6aLJA1MAudWvHGAoWGykWuRTRESz/VL7iOzYWdMGczvSADh4YO2nYWa4SbMDXXprb5LqCyYq0qpdQaeVYMxaPYBY0w12qkOvrURSpgJxmd3Gp6ZvUKA7XwFVELyueXphbEmH4RtdBOEUBvJkUAXZdaGFIEDNTCQC0M1MJNUAuMP/DszBlz5YYYc/SKOrIzc17aFAF5wonJvhxUQGJu/mdj0p4UAXlJSy87c1pcmCJA3NOdnRlLsNxCSm8wPTNaK0wuUJExuAgoIDE3r7KvgEShJoEkAVj/gAJS5hTv5mcuU9adnzlPrTySJ4FEiixtJwlgCW1LIBVJWbZPF7CyDOVnLvMOBaSym19Ik7IjRUDZdbagMLdcR3rmnA/8wsAvDPzC/eUXBJQV0L/xQrQVStYtgiMgWxV13tCe8XTfYZ2EkeshsZtQvluT7BXfatvEqivw1Wq3Q5kI7CytFWz0u1rIRmohq3a7vsKKjYc9qmZrBBBj2WC4Iwmjm9cAr907JH/w/1X6vx0VjViwp6u0VoT6l8kdye1FKz6dXQ8OvCbcnviZBjo1jdqweqv9Kv87jcrGSne1wif2yIZzlMQR2VdNbRnOp2vOjPjedWLd5UEQVbSXwcDndgSy/SXgvgb02bUGuF8C398w4L6ou7Wk7wPPsWy9gQk25bhMUASeIMGkdJg+GNSgtEQfcMmaJixh2kkFBeAySdN/GqmQOkU4QoT7cuB58knuU1qCR1/cn/kl+3Pqej7F/2t4PtXnVT63P1PTn00tW/pGOhexUOTrpxPI7dMJQ8bhr49OIFdNJ9COdArpTaRTCJ5ToEM6hYFMGMiEgUy4JTIhT4s8f8hsQk4y79wBJ3l6QcLhnJS5pR8Iz3jem0+BJV7CYWXTLjYBA/UT7h1USNJEn4YIswnqnu6DCrIE/S9PyA2mHEZzdZxVKOOUZSyUUIElXTmHkzJvJ1SQBmjTCejdYM5hVtCunMMZHjagQTohLWnazqhAOA1lVKAkkFEhS3goo4JNsdw8sMAo7yIUyqRDrAhc3JVSIb9GQiE1jhkIhYFQGAiF+5VSQc1Zru4+kTrnDmlNRJziUkcvw3rKkTxfzOcYrg3bNixPLn97YqdhyTkSINMC98+6b0l4cCRhIHcxB3ceT07OFzLJ5WcHtTux7EFE/HwF9f9dPGS7NxuAgrWwt9ezpQaO8GqprCPXX7Bjmh+Lb7H5SehLIlfY6FsVloCECDtfBpN73qusDkOTug9Nar1cy3LgvDT9QfS2iQS2TYn52ld/afAfn0t5JHYHlXjx2J0Ux9aWCMLWdW5VcT3L0Z1odz6DdbGgwXzMWeZNdkO5VWy7Ihyajecye1A/qv3KNXO6KARlNLnU6G392CE9c8SfnQi54+DLFx10Ue3Ot+JVH7vohOOVGWF6Vx03eJxFDI46uUDu5B0QWQa6UHoYlmaj2a0G/atXGFD6rwilVz6/NEqP9wnXXpT42GgKmbwC7GY0hdi6qY+HvAIDVj9g9QNWfxOpj/OizMqHnVeg9BR80iTP0z6sPo8LbnITJzHLadkX+Y8i+ZmXV0DZtAurR7Wa1DsqkDDCol5RIXVPN1YPJST2H0luLrGANFcHVp/HWZ5nwcQCWWdiAZPB10L1sv6hvAJlIPcxxvBTknZoCyF/kJbBvAKUB6B6ZtkGJ68AI0kgr0CSJ6HI/5wnHVA9mI50ZT/mXbH/nNIOqJ6z64PqSWKEiwaofoDqB6j+niQWCNzzVt7xtiEd3wuTyrBv3d/aYZszVMCYwZdi81hNQ2Clp6TSLgNHhCWuX9W8p0TEFcTrwqYImcJeRe77PAX408lSrLMx4NPJq3t38xsPHuv1WDgmt+rJPRoOA5aSPVcSptuD/TE3TpcFgUB2obB/OD7XEx+3zcEdw8uw/HgaZ5Ic2RUQtWiQNjWpRsKWNp2wix9+qKefun3RjIZ30jZA64keRZg8wUkSsQokbNAev4rdGLvmrdl6fsjCfqBSBl52KW0mex7BHpBAR9THx7XTFxunCUK5Lfo6SzBtApjz26UCFxw2oZ3hey2/8J5E3Ih2IzMDBmZr9YIbdVd/KgX/3JCZInrSKGxrV6J7XNKvC2k/m3+sR2e3irSrVxiQ9q8IaVc+vzTSjvctemB27gfE0+vS11k/eS8fhPsHkH0A2QeQ/ZZA9owy+oBBdhjqUx9kT2iZ9YLs3I2hT2JKM9ZG5V2QndDci29XNu1W7k8KSrxX4iS5SLlf3NMNsmMJDsrObgxj515MegNj53GaFqHkvWiyDow9KbKQej/WP6DenwZBdhJnPO+Kh0+QFciCAv6MGY16C7KXaZK1QfaSZAF1nSSjgXB4UpZduXtT1pW6l5gkBk35/qJTvp9co3x/Vg7y/QPEPkDs9zMaHrY/XtwyzlJ+5HLWjlwmvCty2QN3fbWWNqYbCEuuf5tIiCgUNmxkEc7m80WnELkNPXae9W1L0V0qv+//uhdtIcg7ilCZfdkKgbYSLQoNdkKSO2KcPe0YjRQrUNpIuMgw5UqHfkowWCG9SoBFwGVKSeI+RcMPTeo+NKn+aHhPDEiWdP2SQI2MqF+6awrkvDU7Mj89aj3u1SvXOCsxOCvG0G82Zfk/P4q+rRRvM9E2BPof+UrxWr7nru1Ypa6/cuS6xmZBY5fC1m15fmtn3Sx7ouw7zyl4A4a0uIN+CTjUP8Sw/qmPG8QG1jBuGm7JxG3JqjX5FvJHtc1+QoDcPiEwCOR8fYQAuXJCgKq4+6JBCCRXHXdfBCmBJEQJ0IESGCiBgRIYKIHboQR4maY0fdCUQF54UfEk5TmlvXH3jDiiOrnzqSOZb8o8jRxl0y5KgMRlQXJXcT8pSdofd6/u6VTchxLcXL4lucGwe5N5tp3MF16EhZL5gsG6kvmWRsjeEgKy9gFCAFwbyOhbxqUjwOMH3RdxmjrZh72EvokJgXcS+hJSBhL65q7kjbm2KENq+6zsyOebU9rBB2RZA/a3fEDGO9P5kmtM55sOIfcDHzDwAfc/5B63QtEfI3Fqf1PFTWsNkNlayUJlrLaP28jw2TwVEdP9odp+ikSzGhZZVLHtylW0WCvrvWoVHU9+q8fuxRhfjT3SLo21AMlyghBdNavn50vogUa52RfDHpkHOLlMl/LVnTJNHtWlDZDdxj8RBRTwswSZ61m9gKW1RJihwXlJJO9tsP/QVm68rfQj+Hu7UcuWNm7agqdnsglcTSS7RHyjCEZP/WxYTlZHE7Su1J6njrb89eGgKng6iDK/OacJYamTWLcd2G5C1aXJrER/v+2pryVkky5gBPvLg80riFnvoU5c+++qV3DxOin2NIEWj1SQmEfEJMRuEqHu8QyVnjE5Yr18x04SYtHldLrYnyfTKS6IxNmDC9yj5HZC53CuSR7fnrvhzrkbdNCBw9Lt+K5xDjl4LFbk/vsu2hMsiKut5DJ/2o38xt2YSTearMpW6UfB6FrjR2CIj6KT8TLaivb3QtQC5SNYZp+MVuy6iIVDHLBHVZtSsI8eCIWvg1CwHl+bTvgITsKN4ImiEmjMeZNKKBSVkDYkfDrPFlAuiYTLUgnr5+4lxc1I+PAReEMNcXYYkEi1PwpLY8rkNGKPJC71eYTdd1X0r7BCrhGffRLt4hhG4nKE9ralY0mPZRnym5GZ1rE0a2u88s030YagEijGxjZecbR70M0sSFg8QC6IFreCOX5VYzVJPpJaZiYlw7LFLmBZYYLBgtXyRYS9d3Af/uOz10sYPFm0B//rpI0SmLga+Z79v9fP9l882TsY/fAMfDrahe3/86dPXj87iE+h+qMnfLNJYUiLkWhXzmZBokK0QqgfzlUasN/8TgD7DQ5CExdIQHiOjTZ0kThJPdLLdlwWr+aCBxHvQeV7UPGI78yX7cewbp5DcEdsLarD8hwin4/HdWAxfXQH2h5q8MPL138Sb7s0LIeqG5IdshCVhwsKoVgI2lki2/tMfpb1lb55vf/kxcHu/vNXmOcmevHy9bNoA174pB5v7sjhfgImRWMc42J7scBFRGrWBfCU+jfwFxYlfKnJNzS65JrG9QnuM+RUs7cpSRjsRZITgcZd1zPRrBAdNQXvRBzWs9MKXyXCIUGHLlWBJov4AzZVGJXhEixMvjCSE7AlPT2Fy394svtn3aR0GY/PjLOwGAT/Yfk3rs5EFFX9CZc7k9UV0TqkV2mStNbHGFckxRO5m8sIPmdeLiN7yDrT+6SsvSrL3VVZjv/XWJXl4g3FeVT8O70BEkhNMZYDIkmaMvagsy6nhXcsRNW4lwNKaWYYGs6zJO3hgDDFL3UzMWRJVvKerMs8Jjn1T6pwlvRnXVb39BwLgRIcFijnN0kCgbk6aKA4J7R9LESaLMgC0RR+4jQkvgQGCKRdBu+2aaASkwRnYRoojbOA8BIjcUEZa3BASVyW7TMh8G2etDgg/DZjLRIIfFOkQRIIbshYWHgpiWlZhlkg8HLwVAism6jJnhBigSjXZ4YMC0R5wdJ1WKA8zlk5sEADCzSwQHeOBRKDYVfO5RCw/+LHBp5f/wZvscR5QWIZplF6gedK2AbXZy7+L28xKLnqRHINa24k6iCAsx/Ty3Rf+kWWBk+FFnt4Lndg+Dbw7G3RnMRcZAPuEXpVAa2wN/8eJxZHL0Pl4PWE5NX21Fsjw+24RJR1Mzua48kU/hbDz1ysL2ChLxLHjubHMrpMvG0rcSx0z9cRQQ8IKfDw84JG0qCJ3lHck8TOQyO7340s8qGe3g3UrDA7GG4+3OHNVDOp7Isf/ZkPVloS3U5i5hBImoxw2irYQFxZLn07o48O69UqkANBtrH5tJWCWHiPau9V6kyIZdaqVatrmGcLkGRjjwn5pOpwOV8cihY6OkaGEuboT6rJXMqv17Mx5sKX+MstOJak2rNUcIPwre1trR5mhgDP0K7nuPEcwwfqMz4dY5jqZZry8o+luH0dx9lTsXK4WadJS5uvtasu2zEL13+FGhJc/xWO/4rL+I9p93GnYyp7aid1UK8eodgz3PcRVPyWTr7YFxhoqq+MpuJXSVPRxM80QS/MCf25NNUlskInw4mX4cTLcOJlOPFyS1mhKSsfdFLojPhkB+OFoT86kkLDFZbsoGVpUzgHk0KnNMm8pNDCpL0HXsrMO/Di5J3oPvAC93QfeEmJe96loDeYE5pbML+dZ6KkZRrICY0m68gJzQlLg0dezLkRl+sgIa4DXirzz8L4wlwZIVkw0QShnLVzQjPnIIzNCV2QVqIJFhfUKEVZvgMvTmjHoZeSp12nXgraceolZ12JJqBpXxPfgUdqaD7wHQPfMfAdd1wFS3cs3BUvbfsKpcP91kr3tKE63OotliaMlUDdJXauEueKhixmqArWBRYO1tkJGplRxTEFm2jAO5DQnS03mIV3fowLs225dDdrSQ8fb+EfsJIWG/XXWk4fDHcM91YYbi366eF8tZrWsD19b4FuG96utZDc9+hJm3CHT7sMbeSOtZF2KP9uO9GwFU4KURs9aYfjLjkf3MDYTQ6TXzXy5aK2kdzkfGbyXLpekP1BVyrdWKHKulG7LVQDyoGzDnJiBIfJlMVQIjTOUMbukDFFK7R5H2zOh5Zzoa1Dq5ZvLWk49wTWhf61tWim5pYqZp0aZPGXn6ShgqawiblT19nXezDmoCP7tJ/TwcmKYX3RTuog8dtPun2IbhtCtkmoc+pxszKUY6OJSYfqoXDdDqursGbHhfX75PT8NODZ9Xpr64gUdx3LXccGjsqkrmNTj7ySjk2/rBen1rNBI5k5EH6Gac2cbOztnarrC5bPdg9hCHn6ENvNtrSsBCiCA3Org+lc5GEa5HZzb9sXGGiQr4YGuWzebUGDNJJuh07sXDrp9tVSIbeZdHs4sTOc2BlO7AwndoYTOw/kxA4tOXvYJ3bSlHmpyVWNO0ksmsV5aWTYSJxkpPfEDoMZi3OHkypLJ3l6gMRCIa/M1YVLSFrm/Ylc1D2dJBaW4BzYubFc6cpYXed1Ul6ULQpLGix8XqeMic38YjksWf02h4W+DXBYMU+KIkhhYe7zlAcIrAJsWJStAztFnpD2gZ2CpGX7wA4nSRE6sMNyFj6wk5QdaVzwXBnlWYDBgipnRZDBomCiNL22EzuEG7m4gcEaGKyBwbofJ3Zg1fftUockY8RwHThM4QH76wX/K8kq0QDFDK7iztp6+QhkeFQF7tseq+B0gRtN62osMm4LTavG4QwhxKXwlbEf3Ww7j3wxV04pdH5D7NdsPowNMQ8JPTL/QIcbfq2Ntw2T5aprGFqew5J5qRgbx0jG8uCl8RzG9mq2ah29cMYljAYXnrsX53SGpnUPm1a/KFxw/6jEz1ZzAyXYxPPyHfThA5nFpP/ADwtsv+ADl9i7PubBzTEPuS9LLdOCWy67L8udcwbuvizX+7L8y88YZB1nDOQuo+uYgUyoIU8NyE2ORsb8loYSWK1GvLmekJy7/3cIX46sj0YpBAYHHkF3qYNFBrJ/7PeIWLlCOq9QrlTmuNxGmlke1KE6pQN5yGGpdljadljmOizzPC4dljkOy8QD13cY9c6FbCgduWWDjtyOXE+aQyAy/HZzPV25tXoXVQd+3DM9ctRQQ40+wPclMEe/d/QhK9ktM92ZuDnjs57XLtvNLuU14h2zM92sbSmPz9yGCWEpcmXBuhR2vMjUzOSwqu4RC/AOpblrzmnfpzQ35LL/2riry2ayF9yVm7UmRFxdOo395xFXdy+NPR1p7H9Rg8ntsQ3x0dk8np0v343OsH3vHqDlfL7qzxWsAydH82m1lIwVjfPRL1GZJKOfwdKCv0JzC0h28lu9eAM+FmwUQUzuscTsMdNYvRgJv3jvsalP+7TIqe8iDcOpbIBYkhgQZ9EHmMNgp632n0cMRkPcmMI6TX+5HX2cRpRmKedpmYx5npP8cDvKHlMenRyTIhFMjwklwLCE1ea6J34c9qVxOObApWN2ZP5CMXvikseel4kazIuhWfapoKBeeffJy17BZKVth+dqcFbY55v21lQf/5FsEn20S7Gs+bHMpbh8V2FWSei3Z9Xq3XdRixTb2FVM2ueTELwdYdQ3U8u1FhGTswlKmelIMjcohToZC7l7Hpp+XoAKMQ+kenmlHyjP5WfmhlRcwG6DqADzP/DsMilN/YTzGe1NOE/jghFuWYSspEWL2LDjLWFxZvLLmydQVUI44TxvKItRQi5MOM97lcWwBCfhfHJzp22kuTqYChLTIictqkLZLMhVwG8pK4I553lbW0z6t8VVwAKW5eHTNglmdaFtqoKkcVokaYuqoKwMUBWUpaxNVaQJ4wGqAjyThqgKIQnnns5pcBWW+Gioi5G8I+d8boXQruG0TZKxgasYuIqBq3gA6mK4XUnbWUOwzdjFul5laiEPc+jCB2oQAPtY1zM/n7b0hEF4l54Sk9oh6E3jBq5BYTH1eJ+oe+ljXHhCMxb4w/mh2DKCceWKVeYjh92CCsPGMtq4hHqkCKjy0pDAMvQxhuwqHaimhJXantr80W1NJ6ssY60lE0eLTCmjWpzu8EP3Hun44q2t+ywZNrScW2050Xpx/iZOdDkxXIwMe7z8Hkrvj8TexaKa1Dtx8aV7pXX1hjr1v0ybEhOqaEOLGvoGuF50G2WYyXI+bfnH0fty88Kj63dHeyrgdrSrwP+RVALTjSLklINGQqRHLfUwv2FpSFm7RQLDocMzSXNvS690b9sD0ZLbg2iH7OJfG0RLrhaivXRi8c89W3D3EosPZwuGswXD2YLhbMFwtuChnC3ISJpmDxmzp3lSeGcLZI37MPssSUsrkOV8CmYDSWNS2qzxJE7KkrOeswW45c1LH7Mvygsxe7ynB7OHEhzInt0gZI/2CUP2qAxF27lApMHChwtgvVWmNATYQ/3bgD06N3C4gCOszcICWUXMyjSkj1XGtiJuOhAjC+WmA+GcB9KBFCkNQPbUnnRopgMpsq50ILyJy+t7siTpSAeS0oRdE2CfiSM5A2A/APYDYP8wAHua4x7m33CXKfBXXFtUsI9uywi1Aog7A8LdKD1Y5zugiIhGfifQB7lcxmnIUSDxJWA6Uypo9SUrmCKlnLxoXSwBblpUY4VkC31cmN1e/OgncHA2WTLdt7OOx7X7Jiwql3OL5ULRY+gS8B5GvP1O53wf2sJttIV2gLEMA+/TfIFNUjtrhwGl3XhmlapebHkuVMJqBvaTpRs17Hy6E1uhNlrM0ltW5rcvMGDGXwdmbD2+NmbM0pN3v7vS/CxOv1iZn6V2sX6/lfnJCMY+MdqNFG22Y0fD6SeLVtWWVwsF9h68q1CpbuEixrDnGf2yLf7zkwnunX+MXogO9kR3sDffCERWR/nmF8fudgTuEoGaBWN3x0fjKk1IScb5UVrD5jMiiQnebUfueijtZYJ3NaTpBe5iaZdQuUfk0pX3VxOnF9IbCLclsNbVHtLy9Di8bzzZjdRi+Oq16vsPqFHzwU5QXAsANiYo/oUiceRWsvXSlGQPWsAeRjpP+0PVuBufS+M8obmNqeVZwVs3OPgcpmnNC0fKgxdFGfUK2BuAUN5A6RoC9nhPp/YHpZ6AfVncGD4nrRXG58qYsKytX68sFgbowEFlUoQU7NM0oGCP3m0DdJTGSU6yLoCOWnF7L19vRnkzpha2LImB4gxAR+K8LFoAHY2LNCD/gSmLSQifg41RlvIgPoe5g0kZxOdYwsPxtCw1YF8InmNteI5l9qsL4mnz0oVHB3hugOcGeO4OwnOwSZjNl5NlDyQzcVOWOqINBu9YYvi8OLouJgkRnQATTb2SiMbZYgLzzicLVSCKgXtTk6bIJC/a2FepV32Z7+W3aC/Yr0I/10kKA1gJrisfOWmT9um3S2nAbZuNDysnfpAPVTkyz6d46uujfHs3F6Ivhi2WZI2nqk3iq8BP0J/nH5eie1WqeKe+lVwL083txpv5iJEbuRlbmQYzZIjj4ss7qwAyNLAH08DaQCLup89O58sRjkZ2Nx161dVcvaB4A/HkW99hqbBSs8NyTjA2d1hGeRsmtGdCn15F8I5rjfY2RAZoIJYXivXd3wnRomVV9MxZhQuDejpaWAsjgmsaNcxZ+hoV4SZy0iF4uLRiNxrE/gKrI6Tqne68yT1upwe6VB7kiIER9Bq6G7eMEdnku0f4edqOnm77RXlB+6fHLa6cCpjpW8MbWPfgYul6ekNqTMnMh/Ucs6Z2ymUdozIgH1ZTMDUORp5JAplzRYYHbR9/nApi89csF98ZyW0fPaDyXw0qf1mheInKN5Ti28j85YXirxaZv02h+AGZH5D5AZn/bLELxooHLstNuZ/5VVe5T+4i59S5ISmzPCtpl9xFiQlUc4u0U55m5pFhWW5Scg+aT0gaXSTLjfd0Q/NYwg0KXICButD4pCjb4bLKSGF9izKmrKAhLW6ocxuNR4e20XhMStsVLZvGLMkCCheMxTkz0hfvDWKeFCyQTTYpDNhv0HgSZ1kQjec2MWwDjsdo1SAcD08oeThclhaGTGjh8ZRdGx5fkHIIlx3w+AGPv1/hsm2pZLjDoKCif2mQqf7tCEMgdexiQJsYVidiT2VlA2wUoBv+1xuJKCBUREvnUj7Tf47JA1mtnFWjl7ET304+wRwg38NkgX8ZHVfik8BnRWZQ6BOfxIEsG/EJRRuNU6dqMt+go5jr5za0MsvVGNazuO+074xSyrgem2OPOp0sbaZR4VQN6MQNrQNYzKJAa+PkO2qwwuCwkjinyJd3vKj/5xz63if5vM37opAxtL0H2faiNffeo9P5mOBmGh9iUXuBqO6ye7EJk/G/jQyaF2hwaJhSWNJQJiFjor3lJBI3ZDaUeyT6awBhic2L88oCy5xP/aDrv1zWO0rRe583sWb5EMm3mIb+l6bLJJQPLktM2tOE3MFd9Bo+C0D94eHFwszCZ9z4DPbNrzSJYjxmI97bvNllncV2IvOAfdbgw2zKY0vd3YseptmFSziLqg62Nif5zT/+6/8DIEyd9Q=="
# <<< ROWS


# ============================================================ helpers
def el_min():
    return (time.time() - T0) / 60.0


def log(*a):
    msg = "[ee %6.1fm] %s" % (el_min(), " ".join(str(x) for x in a))
    print(msg, flush=True)
    with open(os.path.join(OUT, "kernel.log"), "a") as f:
        f.write(msg + "\n")


def event(kind, **kw):
    kw.update(kind=kind, t_min=round(el_min(), 2))
    with open(os.path.join(OUT, "events.jsonl"), "a") as f:
        f.write(json.dumps(kw) + "\n")
    log("EVENT", json.dumps(kw)[:1500])


def sh(cmd, timeout=None, logfile=None, env=None, shell=False):
    """Run; tee to logfile; return (rc, tail)."""
    shown = cmd if isinstance(cmd, str) else " ".join(cmd)
    log("$", shown[:400])
    lf = open(logfile, "a") if logfile else None
    try:
        p = subprocess.run(cmd, shell=shell, env=env, timeout=timeout,
                           stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                           text=True, errors="replace")
        out, rc = p.stdout or "", p.returncode
    except subprocess.TimeoutExpired as e:
        out = (e.stdout or b"")
        out = out.decode("utf-8", "replace") if isinstance(out, bytes) else out
        rc = "TIMEOUT"
    if lf:
        lf.write(out)
        lf.close()
    tail = out[-3000:]
    log("rc=%s" % rc, "| tail:", tail[-800:].replace("\n", " \\n "))
    return rc, tail


def disk(tag):
    rep = {}
    for p in ("/", "/tmp", WORK):
        try:
            u = shutil.disk_usage(p)
            rep[p] = "free %.1f GB / %.1f GB" % (u.free / 1e9, u.total / 1e9)
        except Exception as e:
            rep[p] = str(e)
    log("DISK[%s]" % tag, rep)
    return shutil.disk_usage("/tmp").free / 1e9


def rm_hf_cache(repo):
    d = os.path.expanduser("~/.cache/huggingface/hub/models--%s" % repo.replace("/", "--"))
    if os.path.isdir(d):
        shutil.rmtree(d, ignore_errors=True)
        log("removed HF cache", d)


# ============================================================ phase 0/1
def env_log():
    sh("nvidia-smi; nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv",
       shell=True, logfile=os.path.join(OUT, "env.log"))
    sh([PY, "-c", "import sys,torch;print(sys.version);print('torch',torch.__version__,"
        "'cuda',torch.version.cuda,'ndev',torch.cuda.device_count())"],
       logfile=os.path.join(OUT, "env.log"))
    sh("free -g; nproc; df -h / /tmp /kaggle/working", shell=True,
       logfile=os.path.join(OUT, "env.log"))
    sh("pip freeze", shell=True, logfile=os.path.join(OUT, "pip-freeze-pre.txt"))


def start_llamacpp_tools():
    """Background CPU build of llama-quantize + the converter scripts at the SAME
    tag as the attached llama-server (converter/server format parity)."""
    script = r"""
set -x
cd /tmp && rm -rf llama.cpp
git clone --depth 1 --branch %s https://github.com/ggml-org/llama.cpp /tmp/llama.cpp || exit 11
cd /tmp/llama.cpp
cmake -B build -DGGML_CUDA=OFF -DLLAMA_CURL=OFF -DBUILD_SHARED_LIBS=OFF \
      -DCMAKE_BUILD_TYPE=Release -DGGML_NATIVE=ON || exit 12
cmake --build build --config Release --target llama-quantize -j2 || exit 13
ls -la build/bin/llama-quantize && echo QUANTIZE_OK
""" % LLAMACPP_TAG
    lf = open(os.path.join(OUT, "llamacpp-tools.log"), "w")
    log("background: llama.cpp %s clone + llama-quantize CPU build" % LLAMACPP_TAG)
    return subprocess.Popen(["bash", "-c", script], stdout=lf, stderr=subprocess.STDOUT)


def install():
    rc, tv = sh([PY, "-c", "import importlib.metadata as m\n"
                 "for p in ('torch','torchvision','torchaudio'):\n"
                 "  try: print(p+'=='+m.version(p))\n"
                 "  except Exception: pass"])
    cons = os.path.join(TMP, "constraints.txt")
    pins = [l.strip() for l in tv.splitlines() if "==" in l and l.strip().split("==")[0]
            in ("torch", "torchvision", "torchaudio")]
    open(cons, "w").write("\n".join(pins) + "\n")
    log("torch constraints:", pins)
    plog = os.path.join(OUT, "pip-install.log")
    rc, _ = sh([PY, "-m", "pip", "install", "-q", "-c", cons, "--only-binary=xformers"]
               + PINS, timeout=1500, logfile=plog)
    route = "A:resolve-with-torch-constraints"
    if rc != 0:
        route = "B:no-deps"
        sh([PY, "-m", "pip", "install", "-q", "--no-deps", PINS[0], PINS[1]],
           timeout=600, logfile=plog)
        sh([PY, "-m", "pip", "install", "-q", "-c", cons] + PINS[2:] + NODEPS_EXTRA,
           timeout=1500, logfile=plog)
    chk = ("import torch, transformers, peft, trl, bitsandbytes, accelerate\n"
           "import unsloth, unsloth_zoo\n"
           "import importlib.metadata as m, json\n"
           "v={p:m.version(p) for p in ['unsloth','unsloth_zoo','torch','transformers','peft',"
           "'trl','bitsandbytes','accelerate','datasets','triton']}\n"
           "for p in ['xformers','cut_cross_entropy','torchao']:\n"
           "  try: v[p]=m.version(p)\n"
           "  except Exception: v[p]=None\n"
           "v['cuda']=torch.version.cuda; v['gpu']=torch.cuda.get_device_name(0)\n"
           "print('VERSIONS_JSON='+json.dumps(v))\n")
    for attempt in range(3):
        rc, tail = sh([PY, "-c", chk], timeout=600, logfile=plog)
        if rc == 0:
            break
        miss = re.findall(r"No module named '([A-Za-z0-9_\.]+)'", tail)
        if not miss:
            break
        mod = miss[-1].split(".")[0].replace("_", "-")
        log("import check: missing module", mod, "-> pip install")
        sh([PY, "-m", "pip", "install", "-q", "-c", cons, mod], timeout=600, logfile=plog)
    m = re.search(r"VERSIONS_JSON=(\{.*\})", tail)
    versions = json.loads(m.group(1)) if m else None
    event("install", route=route, rc=rc, versions=versions, torch_constraints=pins)
    sh("pip freeze", shell=True, logfile=os.path.join(OUT, "pip-freeze.txt"))
    return rc == 0


# ============================================================ phase 2: trials
TRIAL_PY = r'''
import os, sys, json, time, argparse, traceback, gc, statistics
ap = argparse.ArgumentParser()
ap.add_argument("--model"); ap.add_argument("--tag"); ap.add_argument("--rows")
ap.add_argument("--seqs"); ap.add_argument("--steps"); ap.add_argument("--out")
ap.add_argument("--backend", default="unsloth"); ap.add_argument("--device-map", default="single")
ap.add_argument("--save-lora", default="")
a = ap.parse_args()
seqs = [int(s) for s in a.seqs.split(",")]; steps = [int(s) for s in a.steps.split(",")]
TARGETS = %(targets)r

def emit(**kw):
    kw.update(tag=a.tag, model=a.model, backend=a.backend, device_map=a.device_map)
    with open(a.out, "a") as f: f.write(json.dumps(kw) + "\n")
    print("EMIT", json.dumps(kw), flush=True)

def is_oom(e):
    s = (type(e).__name__ + " " + str(e)).lower()
    return "out of memory" in s or "outofmemory" in s or "cuda_error_out_of_memory" in s

import torch
ndev = torch.cuda.device_count()
GiB = 1024 ** 3
rows = json.load(open(a.rows))
t0 = time.time()
try:
    if a.backend == "unsloth":
        from unsloth import FastLanguageModel
        kw = dict(model_name=a.model, max_seq_length=max(seqs), load_in_4bit=True, dtype=None)
        if a.device_map == "balanced":
            kw["device_map"] = "balanced"
        model, tok = FastLanguageModel.from_pretrained(**kw)
        model = FastLanguageModel.get_peft_model(
            model, r=16, lora_alpha=16, lora_dropout=0, bias="none", target_modules=TARGETS,
            use_gradient_checkpointing="unsloth", random_state=3407)
        try:
            FastLanguageModel.for_training(model)
        except Exception:
            model.train()
    else:
        from transformers import AutoModelForCausalLM, AutoTokenizer
        from peft import LoraConfig, get_peft_model
        mm = {i: "13GiB" for i in range(ndev)}
        model = AutoModelForCausalLM.from_pretrained(a.model, device_map="auto",
                                                     dtype=torch.float16, max_memory=mm)
        tok = AutoTokenizer.from_pretrained(a.model)
        model.config.use_cache = False
        model.gradient_checkpointing_enable(gradient_checkpointing_kwargs={"use_reentrant": False})
        model.enable_input_require_grads()
        model = get_peft_model(model, LoraConfig(r=16, lora_alpha=16, lora_dropout=0.0,
                                                 target_modules=TARGETS, task_type="CAUSAL_LM"))
        model.train()
except Exception as e:
    emit(phase="load", status="OOM" if is_oom(e) else "ERROR", error=repr(e)[:1500],
         tb=traceback.format_exc()[-3000:], load_s=round(time.time() - t0, 1))
    sys.exit(3)

params = [p for p in model.parameters() if p.requires_grad]
for p in params:
    if p.dtype != torch.float32:
        p.data = p.data.float()
n_train = sum(p.numel() for p in params)
wdt = str(getattr(model, "dtype", "?"))
load_mem = [round(torch.cuda.memory_allocated(d) / GiB, 3) for d in range(ndev)]
tot_mem = [round(torch.cuda.get_device_properties(d).total_memory / GiB, 3) for d in range(ndev)]
emit(phase="load", status="OK", load_s=round(time.time() - t0, 1), trainable=n_train,
     model_dtype=wdt, mem_after_load_gib=load_mem, gpu_total_gib=tot_mem,
     hf_device_map_devices=sorted(set(str(v) for v in (getattr(model, "hf_device_map", None) or {}).values()))[:8])

enc = lambda s: tok(s, add_special_tokens=False)["input_ids"]
TH = enc("<think>\n")

def build(row, seq):
    P = enc("<|im_start|>system\n%%s<|im_end|>\n<|im_start|>user\n%%s<|im_end|>\n<|im_start|>assistant\n"
            %% (row["system"], row["user"]))
    A = enc("\n</think>\n\n" + row["answer"] + "<|im_end|>\n")
    seed = enc(row["think_seed"] + "\n\n")
    n = seq - len(P) - len(TH) - len(A)
    if n < 0:
        A = A[:len(A) + n]; n = 0
    think = (seed * (n // max(1, len(seed)) + 1))[:n]
    ids = P + TH + think + A
    return ids, [-100] * len(P) + ids[len(P):], len(P), len(A)

plen = [len(enc("<|im_start|>system\n%%s<|im_end|>\n<|im_start|>user\n%%s<|im_end|>\n<|im_start|>assistant\n"
                %% (r["system"], r["user"]))) for r in rows]
alen = [len(enc(r["answer"])) for r in rows]
emit(phase="tokens", prompt_tokens_mean=round(sum(plen) / len(plen), 1), prompt_tokens_max=max(plen),
     prompt_tokens_min=min(plen), answer_tokens_mean=round(sum(alen) / len(alen), 1), n_rows=len(rows))

import bitsandbytes as bnb
opt = bnb.optim.AdamW8bit(params, lr=2e-4, weight_decay=0.0)
scaler = torch.amp.GradScaler("cuda")
dev0 = model.get_input_embeddings().weight.device
any_pass = False
blocked = False
for seq, nst in zip(seqs, steps):
    if blocked:
        emit(phase="train", seq=seq, status="SKIPPED", reason="smaller seq already failed")
        continue
    gc.collect(); torch.cuda.empty_cache()
    for d in range(ndev):
        torch.cuda.reset_peak_memory_stats(d)
    times, losses, status, err = [], [], "PASS", None
    for i in range(nst):
        ids, lab, lp, la = build(rows[i %% len(rows)], seq)
        assert len(ids) == seq, (len(ids), seq)
        x = torch.tensor([ids], device=dev0); y = torch.tensor([lab], device=dev0)
        try:
            for d in range(ndev):
                torch.cuda.synchronize(d)
            t = time.time()
            with torch.autocast("cuda", dtype=torch.float16):
                out = model(input_ids=x, labels=y)
            loss = out.loss
            scaler.scale(loss).backward()
            scaler.step(opt); scaler.update(); opt.zero_grad(set_to_none=True)
            for d in range(ndev):
                torch.cuda.synchronize(d)
            dt = time.time() - t
            lv = float(loss.detach().float().item())
            times.append(round(dt, 2)); losses.append(round(lv, 4))
            print("STEP seq=%%d i=%%d dt=%%.2fs loss=%%.4f peak=%%s" %% (seq, i, dt, lv,
                  [round(torch.cuda.max_memory_allocated(d) / GiB, 2) for d in range(ndev)]), flush=True)
            del out, loss
        except Exception as e:
            status = "OOM" if is_oom(e) else "ERROR"
            err = repr(e)[:1500]
            print(traceback.format_exc()[-3000:], flush=True)
            opt.zero_grad(set_to_none=True)
            break
        finally:
            del x, y
    peak = [round(torch.cuda.max_memory_allocated(d) / GiB, 3) for d in range(ndev)]
    peak_res = [round(torch.cuda.max_memory_reserved(d) / GiB, 3) for d in range(ndev)]
    finite = all(l == l and abs(l) != float("inf") for l in losses)
    if status == "PASS" and not finite:
        status = "NAN"
    steady = times[1:] if len(times) > 1 else times
    emit(phase="train", seq=seq, steps_req=nst, steps_done=len(times), status=status, error=err,
         peak_alloc_gib=peak, peak_alloc_gib_max=max(peak), peak_reserved_gib=peak_res,
         s_per_step=times, s_per_step_median=(round(statistics.median(steady), 2) if steady else None),
         first_step_s=(times[0] if times else None), losses=losses, loss_finite=finite,
         scaler_scale=float(scaler.get_scale()))
    if status == "PASS":
        any_pass = True
    else:
        blocked = True
        gc.collect(); torch.cuda.empty_cache()

if a.save_lora and any_pass:
    try:
        model.save_pretrained(a.save_lora); tok.save_pretrained(a.save_lora)
        sz = sum(os.path.getsize(os.path.join(dp, f)) for dp, _, fs in os.walk(a.save_lora) for f in fs)
        emit(phase="save_lora", status="OK", dir=a.save_lora, bytes=sz)
    except Exception as e:
        emit(phase="save_lora", status="ERROR", error=repr(e)[:1500])
''' % dict(targets=TARGETS)


def trial(tag, model, seqs, steps, backend="unsloth", device_map="single",
          timeout_min=45):
    tfile = os.path.join(OUT, "trials.jsonl")
    before = open(tfile).read().count("\n") if os.path.exists(tfile) else 0
    env = dict(os.environ, PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True",
               TOKENIZERS_PARALLELISM="false")
    env["CUDA_VISIBLE_DEVICES"] = "0" if device_map == "single" else "0,1"
    lora = os.path.join(TMP, "lora-" + tag)
    cmd = [PY, os.path.join(TMP, "ee_trial.py"), "--model", model, "--tag", tag,
           "--rows", os.path.join(TMP, "rows.json"),
           "--seqs", ",".join(map(str, seqs)), "--steps", ",".join(map(str, steps)),
           "--out", tfile, "--backend", backend, "--device-map", device_map,
           "--save-lora", lora]
    log("TRIAL", tag, model, seqs, steps, backend, device_map)
    rc, tail = sh(cmd, timeout=timeout_min * 60, env=env,
                  logfile=os.path.join(OUT, "trial-%s.log" % tag))
    recs = []
    if os.path.exists(tfile):
        recs = [json.loads(l) for l in open(tfile).read().splitlines()[before:] if l.strip()]
    if rc == "TIMEOUT":
        event("trial_timeout", tag=tag, timeout_min=timeout_min)
    passed = {r["seq"] for r in recs if r.get("phase") == "train" and r.get("status") == "PASS"}
    load = [r for r in recs if r.get("phase") == "load"]
    load_err = bool(load) and load[0].get("status") != "OK"
    return dict(tag=tag, model=model, rc=rc, passed=sorted(passed), recs=recs,
                load_error=load_err, lora=lora if os.path.isdir(lora) else None,
                load_status=(load[0].get("status") if load else "NO_LOAD_RECORD"))


# ============================================================ phase 3: round trip
MERGE_PY = r'''
import sys, os, json, time
lora, outdir = sys.argv[1], sys.argv[2]
t = time.time()
from unsloth import FastLanguageModel
model, tok = FastLanguageModel.from_pretrained(model_name=lora, max_seq_length=2048,
                                               load_in_4bit=True, dtype=None)
model.save_pretrained_merged(outdir, tok, save_method="merged_16bit")
sz = sum(os.path.getsize(os.path.join(dp, f)) for dp, _, fs in os.walk(outdir) for f in fs)
print("MERGED_OK bytes=%d s=%.1f" % (sz, time.time() - t), flush=True)
'''


def find_server():
    hits = sorted(glob.glob("/kaggle/input/**/llamacpp/bin/llama-server", recursive=True))
    tars = sorted(glob.glob("/kaggle/input/**/llamacpp.tar.gz", recursive=True))
    dst = os.path.join(TMP, "llamacpp")
    if not os.path.isdir(dst):
        if hits:
            shutil.copytree(os.path.dirname(os.path.dirname(hits[0])), dst)
        elif tars:
            sh(["tar", "-xzf", tars[0], "-C", TMP])
        sh("chmod +x %s/bin/* || true" % dst, shell=True)
    srv = os.path.join(dst, "bin", "llama-server")
    return srv if os.path.isfile(srv) else None


def wait_health(proc, timeout=900):
    url = "http://127.0.0.1:%d/health" % PORT
    t0 = time.time()
    while time.time() - t0 < timeout:
        if proc.poll() is not None:
            return False
        try:
            with urllib.request.urlopen(url, timeout=5) as r:
                if r.status == 200:
                    return True
        except Exception:
            pass
        time.sleep(3)
    return False


def post(path, body, timeout=600):
    req = urllib.request.Request("http://127.0.0.1:%d%s" % (PORT, path),
                                 data=json.dumps(body).encode(),
                                 headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read().decode())


PROBE = ("In one sentence, what does a cascode transistor do in a low-noise "
         "amplifier? /no_think")


def serve_and_generate(tag, gguf, lora_gguf=None, ngl_split=False):
    srv = find_server()
    if not srv:
        return dict(status="NO_SERVER")
    cmd = [srv, "-m", gguf, "--host", "127.0.0.1", "--port", str(PORT),
           "--n-gpu-layers", "999", "-c", "4096", "--parallel", "1"]
    if ngl_split:
        cmd += ["--split-mode", "layer"]
    if lora_gguf:
        cmd += ["--lora", lora_gguf]
    slog = os.path.join(OUT, "llama-server-%s.log" % tag)
    log("launching", " ".join(cmd))
    env = dict(os.environ)
    env["CUDA_VISIBLE_DEVICES"] = "0,1" if ngl_split else "0"
    proc = subprocess.Popen(cmd, stdout=open(slog, "w"), stderr=subprocess.STDOUT, env=env)
    res = dict(status="LOAD_FAIL", gguf=os.path.basename(gguf),
               gguf_bytes=os.path.getsize(gguf), lora=bool(lora_gguf))
    try:
        t = time.time()
        if not wait_health(proc):
            res["server_log_tail"] = open(slog).read()[-2500:]
            return res
        res["load_s"] = round(time.time() - t, 1)
        body = dict(messages=[{"role": "user", "content": PROBE}], max_tokens=96,
                    temperature=0.0, seed=1)
        r1 = post("/v1/chat/completions", body)
        msg = r1["choices"][0]["message"]
        res.update(status="OK", completion=(msg.get("content") or "")[:600],
                   reasoning=(msg.get("reasoning_content") or "")[:300],
                   usage=r1.get("usage"))
        if lora_gguf:
            try:
                res["lora_adapters"] = json.loads(urllib.request.urlopen(
                    "http://127.0.0.1:%d/lora-adapters" % PORT, timeout=10).read().decode())
                post("/lora-adapters", [{"id": 0, "scale": 0.0}])
                r0 = post("/v1/chat/completions", body)
                res["completion_lora_scale0"] = (r0["choices"][0]["message"].get("content") or "")[:600]
                res["lora_changes_output"] = res["completion_lora_scale0"] != res["completion"]
            except Exception as e:
                res["lora_scale_probe_error"] = repr(e)[:400]
        sl = open(slog).read()
        res["server_log_lora_lines"] = [l for l in sl.splitlines() if "lora" in l.lower()][:8]
        res["server_version"] = [l for l in sl.splitlines() if "build" in l.lower()][:2]
        return res
    except Exception as e:
        res.update(status="GEN_ERROR", error=repr(e)[:800])
        return res
    finally:
        if proc.poll() is None:
            proc.send_signal(signal.SIGTERM)
            try:
                proc.wait(timeout=20)
            except Exception:
                proc.kill()


def llamacpp_ready(bg, wait_min=20):
    t = time.time()
    while bg.poll() is None and time.time() - t < wait_min * 60:
        time.sleep(10)
    ok_conv = os.path.isfile("/tmp/llama.cpp/convert_hf_to_gguf.py")
    q = "/tmp/llama.cpp/build/bin/llama-quantize"
    return ok_conv, (q if os.path.isfile(q) else None)


def run_convert(script_args, logname):
    """Run a llama.cpp converter; auto-install one missing python module per retry."""
    cons = os.path.join(TMP, "constraints.txt")
    for _ in range(4):
        rc, tail = sh([PY] + script_args, timeout=3600,
                      logfile=os.path.join(OUT, logname))
        if rc == 0:
            return True
        miss = re.findall(r"No module named '([A-Za-z0-9_\.]+)'", tail)
        if not miss:
            return False
        mod = miss[-1].split(".")[0].replace("_", "-")
        sh([PY, "-m", "pip", "install", "-q", "-c", cons, mod], timeout=600)
    return False


def roundtrip_merged(tr, bg):
    tag = tr["tag"]
    res = dict(route="merged", tag=tag, model=tr["model"])
    merged = os.path.join(TMP, "merged-" + tag)
    open(os.path.join(TMP, "ee_merge.py"), "w").write(MERGE_PY)
    free = disk("pre-merge")
    t = time.time()
    rc, tail = sh([PY, os.path.join(TMP, "ee_merge.py"), tr["lora"], merged], timeout=3600,
                  env=dict(os.environ, CUDA_VISIBLE_DEVICES="0"),
                  logfile=os.path.join(OUT, "rt-merge-%s.log" % tag))
    res["merge_rc"], res["merge_s"] = rc, round(time.time() - t, 1)
    if rc != 0 or not glob.glob(os.path.join(merged, "*.safetensors")):
        res["status"] = "MERGE_FAIL"
        res["tail"] = tail[-1200:]
        return res
    res["merged_bytes"] = sum(os.path.getsize(f) for f in glob.glob(os.path.join(merged, "*")))
    # the 16-bit source weights unsloth downloaded for the merge are no longer needed
    for c in glob.glob(os.path.expanduser("~/.cache/huggingface/hub/models--Qwen--Qwen3-*")):
        shutil.rmtree(c, ignore_errors=True)
    free = disk("post-merge")
    ok_conv, quant = llamacpp_ready(bg)
    if not ok_conv:
        res["status"] = "NO_CONVERTER"
        return res
    outtype = "f16" if free > res["merged_bytes"] / 1e9 * 1.15 + 5 else "q8_0"
    g1 = os.path.join(TMP, "%s-%s.gguf" % (tag, outtype))
    t = time.time()
    ok = run_convert(["/tmp/llama.cpp/convert_hf_to_gguf.py", merged, "--outtype", outtype,
                      "--outfile", g1], "rt-convert-%s.log" % tag)
    res["convert_outtype"], res["convert_s"] = outtype, round(time.time() - t, 1)
    shutil.rmtree(merged, ignore_errors=True)
    if not ok or not os.path.isfile(g1):
        res["status"] = "CONVERT_FAIL"
        return res
    gq = g1
    if quant:
        g2 = os.path.join(TMP, "%s-Q4_K_M.gguf" % tag)
        t = time.time()
        qargs = [quant] + (["--allow-requantize"] if outtype == "q8_0" else []) + \
            [g1, g2, "Q4_K_M", str(os.cpu_count() or 4)]
        rc, _ = sh(qargs, timeout=3600, logfile=os.path.join(OUT, "rt-quantize-%s.log" % tag))
        res["quantize_rc"], res["quantize_s"] = rc, round(time.time() - t, 1)
        if rc == 0 and os.path.isfile(g2):
            gq = g2
            os.remove(g1)
    res["quant_type"] = "Q4_K_M" if gq.endswith("Q4_K_M.gguf") else outtype
    res["serve"] = serve_and_generate(tag, gq)
    res["status"] = "OK" if res["serve"].get("status") == "OK" and res["quant_type"] == "Q4_K_M" \
        else ("SERVED_UNQUANTIZED" if res["serve"].get("status") == "OK" else "SERVE_FAIL")
    try:
        os.remove(gq)
    except Exception:
        pass
    return res


OFFICIAL_GGUF = {"14B": ("Qwen/Qwen3-14B-GGUF", "Qwen3-14B-Q4_K_M.gguf"),
                 "8B": ("Qwen/Qwen3-8B-GGUF", "Qwen3-8B-Q4_K_M.gguf")}


def roundtrip_adapter(tr, bg):
    """Runtime-LoRA route: base Q4 GGUF + LoRA GGUF in llama-server. 32B uses our
    attached proposer GGUF; 14B/8B (fallback only) download the official Q4_K_M."""
    tag = tr["tag"]
    res = dict(route="adapter", tag=tag, model=tr["model"])
    size = "32B" if "32B" in tr["model"] else ("14B" if "14B" in tr["model"] else "8B")
    if size == "32B":
        base = sorted(glob.glob("/kaggle/input/**/Qwen3-32B*.gguf", recursive=True))
    else:
        repo, fn = OFFICIAL_GGUF[size]
        rc, tail = sh([PY, "-c", "from huggingface_hub import hf_hub_download as d;"
                       "print('GGUF_PATH='+d(%r,%r,local_dir=%r))" % (repo, fn, TMP)],
                      timeout=1800)
        m = re.search(r"GGUF_PATH=(\S+)", tail)
        base = [m.group(1)] if m else []
    if not base:
        res["status"] = "NO_BASE_GGUF"
        return res
    ok_conv, _ = llamacpp_ready(bg)
    if not ok_conv:
        res["status"] = "NO_CONVERTER"
        return res
    snap = glob.glob(os.path.expanduser("~/.cache/huggingface/hub/models--%s/snapshots/*"
                                        % tr["model"].replace("/", "--")))
    lg = os.path.join(TMP, "lora-%s.gguf" % tag)
    args = ["/tmp/llama.cpp/convert_lora_to_gguf.py", tr["lora"], "--outtype", "f16",
            "--outfile", lg]
    args += (["--base", snap[0]] if snap else ["--base-model-id", tr["model"]])
    t = time.time()
    ok = run_convert(args, "rt-convert-lora-%s.log" % tag)
    res["convert_s"] = round(time.time() - t, 1)
    if not ok or not os.path.isfile(lg):
        res["status"] = "CONVERT_FAIL"
        return res
    res["lora_gguf_bytes"] = os.path.getsize(lg)
    res["base_gguf"] = os.path.basename(base[0])
    res["serve"] = serve_and_generate(tag, base[0], lora_gguf=lg, ngl_split=(size == "32B"))
    res["status"] = "OK" if res["serve"].get("status") == "OK" else "SERVE_FAIL"
    if size != "32B":
        try:
            os.remove(base[0])
        except Exception:
            pass
    return res


# ============================================================ main
def ok4096(tr):
    return tr is not None and 4096 in tr["passed"]


def main():
    os.makedirs(OUT, exist_ok=True)
    os.makedirs(TMP, exist_ok=True)
    summary = dict(prereg="kaggle/PREREG-BENCH-V12-AUDIT.md#E-e", budget_min=BUDGET_MIN,
                   trials=[], roundtrips=[])
    try:
        rows = json.loads(zlib.decompress(base64.b64decode(ROWS_B64)).decode())
        assert rows and all(r["source_lib"] == "editcap-lib-v1a" for r in rows)
        assert not any(r["cell"].startswith("v12-") for r in rows), "FENCE"
        json.dump(rows, open(os.path.join(TMP, "rows.json"), "w"))
        open(os.path.join(TMP, "ee_trial.py"), "w").write(TRIAL_PY)
        log("rows:", len(rows), "cells", [r["cell"] for r in rows][:5], "...")
        env_log()
        disk("start")
        bg = start_llamacpp_tools()
        if not install():
            summary["verdict"] = "INSTALL_FAILED"
            return
        trials = {}

        def run(tag, *a, **k):
            if el_min() > BUDGET_MIN - 20:
                event("skip_trial", tag=tag, reason="budget")
                return None
            tr = trial(tag, *a, **k)
            trials[tag] = tr
            summary["trials"].append({k2: v for k2, v in tr.items() if k2 != "recs"})
            json.dump(summary, open(os.path.join(OUT, "summary.json"), "w"), indent=1)
            return tr

        t14 = run("q14dyn", M14_DYN, [4096, 8192], [10, 10])
        best14 = t14 if ok4096(t14) else None
        need = [s for s in (4096, 8192) if not (t14 and s in t14["passed"])]
        if need:
            t14p = run("q14plain", M14_PLAIN, need, [10] * len(need))
            # plain wins if it covers seqs the dynamic quant could not (it is
            # re-tried only on the failed seqs, so any pass there is coverage)
            if t14p is not None and t14p["passed"] and (
                    best14 is None and ok4096(t14p) or best14 is not None and 8192 in t14p["passed"]):
                if best14 is not None:  # re-run it at 4096 too? no: 8192 pass implies 4096 fits
                    t14p["passed"] = sorted(set(t14p["passed"]) | {4096})
                    t14p["note"] = "4096 not re-run: dynamic-quant 14B passed 4096 and plain is smaller"
                best14 = t14p
            rm_hf_cache(M14_PLAIN if best14 is not t14p else M14_DYN)
        winner = best14
        if best14 is None:
            t8 = run("q8dyn", M8_DYN, [4096, 8192], [10, 10])
            winner = t8 if ok4096(t8) else None
            if winner is None:
                summary["verdict"] = "NO_MODEL_>=8B_TRAINS_AT_4096 (floor hit: stop and ask)"
        big = None
        if best14 is not None:
            if el_min() < 60:
                disk("pre-32B")
                t32 = run("q32split", M32_PLAIN, [4096, 8192], [5, 3],
                          device_map="balanced", timeout_min=50)
                if t32 is not None and t32["load_error"] and el_min() < 75:
                    log("unsloth balanced split failed at load -> HF+peft device_map=auto")
                    t32 = run("q32hf", M32_PLAIN, [4096, 8192], [5, 3], backend="hf",
                              device_map="balanced", timeout_min=45)
                if ok4096(t32):
                    big = t32
            else:
                event("skip_32b", reason="elapsed %.0f min >= 60" % el_min())
        # ---- round trip(s)
        disk("pre-roundtrip")
        if big is not None and big.get("lora"):
            summary["roundtrips"].append(roundtrip_adapter(big, bg))
            json.dump(summary, open(os.path.join(OUT, "summary.json"), "w"), indent=1)
            rm_hf_cache(M32_PLAIN)
        if winner is not None and winner.get("lora"):
            if el_min() < BUDGET_MIN - 35:
                rt = roundtrip_merged(winner, bg)
                summary["roundtrips"].append(rt)
                json.dump(summary, open(os.path.join(OUT, "summary.json"), "w"), indent=1)
                if rt.get("status") not in ("OK", "SERVED_UNQUANTIZED") and big is None \
                        and el_min() < BUDGET_MIN - 12:
                    log("merged round trip failed (%s) -> runtime-LoRA fallback" % rt.get("status"))
                    for c in glob.glob(os.path.expanduser(
                            "~/.cache/huggingface/hub/models--Qwen--Qwen3-*")):
                        shutil.rmtree(c, ignore_errors=True)
                    shutil.rmtree(os.path.join(TMP, "merged-" + winner["tag"]), ignore_errors=True)
                    summary["roundtrips"].append(roundtrip_adapter(winner, bg))
            else:
                event("skip_merged_roundtrip", reason="budget", tag=winner["tag"])
        largest = big or winner
        if largest is not None:
            summary["verdict"] = dict(largest_trainable=largest["model"], tag=largest["tag"],
                                      seqs_passed=largest["passed"])
    except Exception:
        summary["fatal"] = traceback.format_exc()[-3000:]
        log("FATAL", summary["fatal"])
    finally:
        summary["elapsed_min"] = round(el_min(), 1)
        json.dump(summary, open(os.path.join(OUT, "summary.json"), "w"), indent=1)
        log("SUMMARY", json.dumps(summary)[:4000])


if __name__ == "__main__":
    main()
