#!/usr/bin/env python3
"""build_release.py -- assemble the engineer env+benchmark release into a
distributable tree, from the LIVE repo, so the package is reproducible rather
than a hand-copied snapshot.

SCOPE (per E5-PACKAGING ruling, 2026-08-16)
-------------------------------------------
Environment + benchmark ONLY. The dhruva case study is staged for a later
release and is NOT bundled here (its evidence lives under lna/ on main). The 45
nm BSIM4 model card is NOT bundled or auto-fetched: it is documented as a manual
fetch from the AutoCkt repo with license status "unknown". VACASK stays out
(AGPL-3.0): its HB cross-check results are cited, and its build procedure is
pointed at (PORTING.md), but no VACASK source or binary ships. Data = aggregated
scoreboards + goldens only; no raw per-cell JSONs, no trajectories.

WHAT THIS SCRIPT DOES
---------------------
1. Copies the environment/harness/driver/protocol/prereg files from the live
   engineer tree into dist/engineer/.
2. Copies the aggregated scoreboards + goldens (tolerating ext_ldo's absence
   and noting it).
3. SCRUBS in the assembled copy (never the live repo): rewrites any hardcoded
   /home/dpatni scratch path in the assembled ext_gym.py/ext_ldo.py to a
   tempfile default (defence-in-depth; the live repo fix is a separate commit),
   and normalises machine-specific absolute paths in assembled docs.
4. Patches the assembled tasks.py so `--list` works WITHOUT lna/ or lna/data by
   reading a shipped tasks_registry_v0.json (generated by export_registry.py);
   `--check` still requires the live store and fails loudly without it.
5. Writes the release README, a LICENSE placeholder (license TBD at publish
   time, per ruling), and MANIFEST.md (every file + sha256 + exclusions list).
6. Verifies the assembled tree greps clean for /home/dpatni, the user's email,
   and C:\\Users.

    python engineer/release/build_release.py                 # -> $SCRATCH/dist or ./dist
    python engineer/release/build_release.py --dist PATH
"""
import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ENGINEER = os.path.dirname(HERE)
ROOT = os.path.dirname(ENGINEER)

# Patterns the assembled tree must NOT contain (verified at the end).
FORBIDDEN = [
    r"/home/dpatni",
    r"devavrat",
    re.escape("C:\\Users"),
]

# ---- what ships -----------------------------------------------------------
# Environment, drivers, harness, protocol, pre-registration docs. Source paths
# are relative to the live engineer/ tree.
ENGINEER_FILES = [
    # env + benchmark core
    "env.py", "tasks.py", "test_env.py",
    # in-house drivers
    "baseline_run.py", "random_run.py", "score_run.py",
    # memory harness (E-3)
    "memory_harness.py", "mem_arm.py", "mem_playbook.py",
    # unattended loop (E-4)
    "loop_run.py",
    # external calibration track (E-2 externals)
    "ext_gym.py", "score_ext.py",
    "ext_ldo.py", "score_ext_ldo.py",
    # protocol + pre-registration narrative docs
    "PROTOCOL.md",
    "E3-MEMORY.md", "E4-LOOP.md", "EXT-CALIBRATION.md",
    # the ruled-on packaging decision doc (its own MANIFEST is in release/)
    "E5-PACKAGING.md",
]

# Aggregated scoreboards + goldens. (key, filename, required?)
DATA_FILES = [
    ("scoreboard_v0",       "scoreboard_v0.json",       True),
    ("scoreboard_v0.1",     "scoreboard_v0.1.json",     True),
    ("mem_pairs_v0",        "mem_pairs_v0.json",        True),
    ("loop_v0",             "loop_v0.json",             True),
    ("ext_golden_v0",       "ext_golden_v0.json",       True),
    ("scoreboard_ext_v0",   "scoreboard_ext_v0.json",   False),  # tolerate absence
    ("ext_ldo_golden_v0",   "ext_ldo_golden_v0.json",   False),  # LDO deferred
]

# release/ docs and tools that ship alongside the assembled engineer tree.
RELEASE_FILES = ["export_registry.py", "build_release.py"]

# Files a stranger CANNOT get from this package, and why (the honest boundary).
EXCLUSIONS = [
    ("engineer/data/*per-cell*.json (baseline_/random_/ext_cmaes_/ext_random_)",
     "Raw per-cell result JSONs (~500 MB, carry machine-specific harness.deps "
     "provenance paths). Aggregated into the shipped scoreboards; deferred to a "
     "separate DOI-deposited data package."),
    ("engineer/data/trajectories.jsonl, engineer/data/ext_trajectories.jsonl",
     "(state, action, outcome, cost) trajectory logs (>100 MB each). Deferred "
     "to the separate data deposit; regenerable by running the drivers."),
    ("lna/ (the shared core: datastore, spec, size, extract, to_spice, "
     "topology, moves, null_sizer, playbook, ref/, specs/)",
     "Lives on main; a runtime dependency, not bundled here. The env imports it "
     "at runtime. Fetch the circuit-repro repo's main branch (see README)."),
    ("45nm BSIM4 model card (AutoCkt .../spice_models/45nm_bulk.txt)",
     "NOT bundled and NOT auto-fetched. License status UNKNOWN (no header; "
     "no LICENSE in the AutoCkt clone). Manual fetch from ksettaluri6/AutoCkt "
     "at the pinned SHA -- see README quickstart."),
    ("VACASK (harmonic-balance simulator)",
     "AGPL-3.0; out of scope. HB cross-check results are cited (case study, "
     "later release); build procedure is in PORTING.md. Not required to run "
     "the benchmark."),
    ("dhruva case study (lna/FINDINGS.md, JOURNEY.md, playbook entries)",
     "Staged for a later release per the E-5 ruling; environment + benchmark "
     "only in this package."),
]


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def git_sha(cwd):
    try:
        r = subprocess.run(["git", "rev-parse", "HEAD"], cwd=cwd,
                           capture_output=True, text=True, timeout=10)
        return (r.stdout or "").strip() or "UNKNOWN"
    except Exception:                                          # noqa: BLE001
        return "UNKNOWN"


# ---- scrubbing (applied to the assembled copy only) -----------------------
_SCRATCH_LIVE = re.compile(
    r'"/home/dpatni/\.claude/jobs/[^"]*?/tmp/(ext(?:_ldo)?_scratch)"')


def scrub_source(text):
    """Rewrite any hardcoded /home/dpatni scratch fallback to a tempfile
    default. Idempotent: if the live fix already landed this is a no-op."""
    n = [0]

    def repl(m):
        n[0] += 1
        name = m.group(1)
        # Replace ONLY the string literal with a bare expression -- no inline
        # comment, because the literal sits mid-call (`os.environ.get(KEY, <here>)`)
        # and a `#` would comment out the closing paren. The scrub is recorded in
        # the build notes / MANIFEST instead.
        return f'os.path.join(tempfile.gettempdir(), "{name}")'

    out = _SCRATCH_LIVE.sub(repl, text)
    if n[0] and "import tempfile" not in out:
        out = out.replace("import os\n", "import os\nimport tempfile\n", 1)
    return out, n[0]


def scrub_doc(text):
    """Normalise machine-specific absolute paths and identity tokens in assembled
    docs. Replaces the /home/dpatni/circuit-repro[-engineer] prefixes, the Claude
    scratch paths, the build-box username, and the author's Windows home path with
    neutral tokens so a public doc does not leak the build box's identity/layout.
    Counts hits. (E5-PACKAGING.md §4.3 names `devavrat` and `C:\\Users\\Devavrat`
    literally, in prose that reports the scrub search itself -- those literals are
    normalised here too so the assembled doc greps clean.)"""
    n = 0
    for pat, sub in [
        (r"/home/dpatni/circuit-repro-engineer", "<repo>"),
        (r"/home/dpatni/circuit-repro", "<repo>"),
        (r"/home/dpatni/\.claude/jobs/[^\s`\"']*", "<scratch>"),
        (r"/home/dpatni", "<home>"),
        (r"C:\\Users\\Devavrat[^\s`\"']*", "<win-home>"),
        (r"C:\\Users", "<win-home>"),
        (r"(?i)devavrat", "<user>"),
    ]:
        text, k = re.subn(pat, sub, text)
        n += k
    return text, n


def scrub_json(text):
    """Normalise machine-specific provenance paths in shipped data artifacts.
    Scoreboards/goldens carry a `harness` block that stamps the absolute ngspice
    (and, in per-cell JSONs, model-card/zoaf) paths resolved on the build box --
    a provenance stamp by design, but it leaks the /home/dpatni prefix. For the
    aggregated artifacts that DO ship, normalise the prefix to <repo> while
    leaving the rest of the stamp (binary name, version) intact. Counts hits."""
    n = 0
    for pat, sub in [
        (r"/home/dpatni/circuit-repro-engineer", "<repo>"),
        (r"/home/dpatni/circuit-repro", "<repo>"),
        (r"/home/dpatni/\.claude/jobs/[^\s`\"']*", "<scratch>"),
        (r"/home/dpatni", "<home>"),
    ]:
        text, k = re.subn(pat, sub, text)
        n += k
    return text, n


# ---- the tasks.py patch: --list without lna -------------------------------
_TASKS_ORIG_IMPORTS = (
    "from env import Task, _bind_runtime_deps        # noqa: E402\n"
    "\n"
    "_bind_runtime_deps()\n"
    "import datastore as ds                          # noqa: E402\n"
    "from spec import Spec                           # noqa: E402\n"
)

_TASKS_PATCHED_IMPORTS = '''# --- release patch: run `--list` without lna/ or lna/data ------------------
# The pinned reference VALUES are shipped in tasks_registry_v0.json (generated
# by release/export_registry.py from this same _ROWS table). When the shared
# core (lna/) and its deps are present, this module behaves exactly as upstream
# (both --list and --check). When they are absent -- a stranger who has only the
# release tree and has not done the manual fetches -- `--list` still works from
# the shipped JSON, and `--check` fails loudly (drift-checking REQUIRES the live
# store). This block is inserted by build_release.py; it is not in the live repo.
_REGISTRY_JSON = os.path.join(HERE, "tasks_registry_v0.json")
try:
    from env import Task, _bind_runtime_deps        # noqa: E402
    _bind_runtime_deps()
    import datastore as ds                          # noqa: E402
    from spec import Spec                           # noqa: E402
    _HAVE_LNA = True
except Exception as _e:                             # noqa: BLE001
    _HAVE_LNA = False
    _LNA_IMPORT_ERROR = _e

    class Task(object):                             # minimal stand-in
        def __init__(self, task_id, spec, wl_hash, budget, seed=1, tier=2,
                     ref_ts=None, ref_evals=None, ref_feasible=None,
                     ref_obj=None, era="current", inductor_q=None, nf_gate=None,
                     n_devices=None, notes=""):
            self.id, self.spec, self.wl_hash = task_id, spec, wl_hash
            self.budget, self.seed, self.tier = int(budget), int(seed), int(tier)
            self.ref_ts, self.ref_evals = ref_ts, ref_evals
            self.ref_feasible, self.ref_obj = ref_feasible, ref_obj
            self.era, self.n_devices, self.notes = era, n_devices, notes
            self.inductor_q, self.nf_gate = inductor_q, nf_gate

        def with_(self, **kw):
            raise RuntimeError("tasks.py: with_() needs the shared core (lna/); "
                               "only --list is supported without it")


def _offline_registry_json():
    """The shipped pin snapshot, or None. Load-bearing offline: `cmd_list`
    cross-checks the module's _ROWS-built table against it so the JSON a
    stranger reads is provably the same table the code prints."""
    import json as _json
    try:
        with open(_REGISTRY_JSON, encoding="utf-8") as _f:
            return _json.load(_f)
    except Exception:                                   # noqa: BLE001
        return None
# --- end release patch -----------------------------------------------------
'''

_TASKS_CHECK_GUARD = '''def cmd_check():
    if not _HAVE_LNA:
        sys.stderr.write(
            "tasks.py --check requires the shared core (lna/) and the live "
            "store lna/data/topo_labels.jsonl, which this release tree does "
            "not bundle.\\n  Fetch circuit-repro main (see README_RELEASE.md) "
            "so `import datastore`/`import size` resolve, then re-run.\\n"
            f"  underlying import error: {_LNA_IMPORT_ERROR!r}\\n")
        return 2
'''


_TASKS_LIST_PROV = '''def cmd_list(long=False):
    if not _HAVE_LNA:
        _doc = _offline_registry_json()
        if _doc is not None:
            _json_ids = {t["id"] for t in _doc["tasks"]}
            _code_ids = {t.id for t in all_tasks()}
            if _json_ids != _code_ids:
                sys.stderr.write("WARNING: shipped tasks_registry_v0.json and "
                                 "the module _ROWS disagree on task ids; "
                                 "regenerate with release/export_registry.py\\n")
            print(f"# offline mode: no lna/ -- pins from {os.path.basename(_REGISTRY_JSON)}"
                  f" (schema {_doc.get('schema')}, git {_doc.get('harness_git_sha')})")
        else:
            print("# offline mode: no lna/ -- pins from module _ROWS "
                  "(tasks_registry_v0.json not found)")
'''


def patch_tasks(text):
    """Insert the JSON-backed --list fallback and the --check guard."""
    if _TASKS_ORIG_IMPORTS not in text:
        raise RuntimeError("tasks.py import block not found verbatim; the "
                           "release patch is out of date with the live file")
    text = text.replace(_TASKS_ORIG_IMPORTS, _TASKS_PATCHED_IMPORTS, 1)
    # Guard cmd_check(): prepend the loud-fail body.
    text = text.replace("def cmd_check():\n", _TASKS_CHECK_GUARD, 1)
    # Prepend the offline provenance line to cmd_list().
    if "def cmd_list(long=False):\n" not in text:
        raise RuntimeError("tasks.py cmd_list signature changed; patch is stale")
    text = text.replace("def cmd_list(long=False):\n", _TASKS_LIST_PROV, 1)
    return text


# ---------------------------------------------------------------------------
def build(dist, emit_source_docs=False):
    eng_dst = os.path.join(dist, "engineer")
    data_dst = os.path.join(eng_dst, "data")
    rel_dst = os.path.join(eng_dst, "release")
    for d in (eng_dst, data_dst, rel_dst):
        os.makedirs(d, exist_ok=True)

    manifest = []      # (rel_path_in_dist, source_path, sha256, note)
    notes = []         # human-facing build notes

    # 1) engineer source/docs, with scrub + patch where relevant
    for name in ENGINEER_FILES:
        src = os.path.join(ENGINEER, name)
        if not os.path.exists(src):
            raise RuntimeError(f"required source missing: {src}")
        with open(src, "r", encoding="utf-8") as f:
            text = f.read()
        scrub_n = 0
        if name in ("ext_gym.py", "ext_ldo.py"):
            text, scrub_n = scrub_source(text)
            if scrub_n:
                notes.append(f"scrubbed {scrub_n} hardcoded scratch path(s) in {name}")
        elif name == "tasks.py":
            text = patch_tasks(text)
            notes.append("patched tasks.py: --list works without lna/ via "
                         "tasks_registry_v0.json; --check guarded")
        doc_n = 0
        if name.endswith(".md"):
            text, doc_n = scrub_doc(text)
            if doc_n:
                notes.append(f"normalised {doc_n} machine path(s) in {name}")
        dst = os.path.join(eng_dst, name)
        with open(dst, "w", encoding="utf-8") as f:
            f.write(text)
        rel = os.path.relpath(dst, dist)
        note = ("scrubbed" if (scrub_n or doc_n) else
                ("patched" if name == "tasks.py" else ""))
        manifest.append((rel, os.path.relpath(src, ROOT), sha256_file(dst), note))

    # 2) aggregated scoreboards + goldens
    for key, fname, required in DATA_FILES:
        src = os.path.join(ENGINEER, "data", fname)
        if not os.path.exists(src):
            if required:
                raise RuntimeError(f"required data artifact missing: {src}")
            notes.append(f"data artifact absent, skipped (tolerated): {fname}")
            continue
        with open(src, "r", encoding="utf-8") as f:
            jtext = f.read()
        jtext, jn = scrub_json(jtext)
        dst = os.path.join(data_dst, fname)
        with open(dst, "w", encoding="utf-8") as f:
            f.write(jtext)
        if jn:
            notes.append(f"normalised {jn} provenance path(s) in {fname}")
        manifest.append((os.path.relpath(dst, dist),
                         os.path.relpath(src, ROOT), sha256_file(dst),
                         "scrubbed" if jn else ""))

    # 3) generate the shipped registry JSON (needs lna on THIS box)
    sys.path.insert(0, HERE)
    import export_registry                                     # noqa: E402
    reg_dst = os.path.join(eng_dst, "tasks_registry_v0.json")
    export_registry.export(reg_dst)
    manifest.append((os.path.relpath(reg_dst, dist),
                     "generated by release/export_registry.py",
                     sha256_file(reg_dst), "generated"))
    notes.append("generated tasks_registry_v0.json from live REGISTRY")

    # 4) release/ tools
    for name in RELEASE_FILES:
        src = os.path.join(HERE, name)
        dst = os.path.join(rel_dst, name)
        shutil.copy2(src, dst)
        manifest.append((os.path.relpath(dst, dist),
                         os.path.relpath(src, ROOT), sha256_file(dst), ""))

    # 5) README_RELEASE.md, LICENSE placeholder
    readme_dst = os.path.join(eng_dst, "README_RELEASE.md")
    with open(readme_dst, "w", encoding="utf-8") as f:
        f.write(render_readme())
    manifest.append((os.path.relpath(readme_dst, dist), "release/build_release.py",
                     sha256_file(readme_dst), "assembled"))

    license_dst = os.path.join(dist, "LICENSE")
    with open(license_dst, "w", encoding="utf-8") as f:
        f.write(render_license())
    manifest.append((os.path.relpath(license_dst, dist), "release/build_release.py",
                     sha256_file(license_dst), "placeholder"))

    # 6) MANIFEST.md (also copied into release/ so it lives with the source)
    manifest_text = render_manifest(manifest, notes)
    for path in (os.path.join(dist, "MANIFEST.md"),):
        with open(path, "w", encoding="utf-8") as f:
            f.write(manifest_text)
    # add MANIFEST.md itself last (self-listing without its own hash, noted)
    m_dst = os.path.join(dist, "MANIFEST.md")
    manifest.append((os.path.relpath(m_dst, dist), "release/build_release.py",
                     "(self; regenerate to verify)", "assembled"))

    # 7) verify grep-clean
    findings = verify_clean(dist)

    # 8) optionally drop the canonical committed copies into the SOURCE release/
    # dir (engineer/release/) so README_RELEASE.md / LICENSE / MANIFEST.md are
    # reviewable in the repo and never hand-edited -- they are regenerated here.
    if emit_source_docs:
        shutil.copy2(readme_dst, os.path.join(HERE, "README_RELEASE.md"))
        shutil.copy2(license_dst, os.path.join(HERE, "LICENSE"))
        shutil.copy2(m_dst, os.path.join(HERE, "MANIFEST.md"))
        notes.append("emitted canonical README_RELEASE.md / LICENSE / "
                     "MANIFEST.md into engineer/release/ (source copies)")

    return dist, manifest, notes, findings


def verify_clean(dist):
    findings = {p: [] for p in FORBIDDEN}
    # The build script itself legitimately NAMES the forbidden patterns (its
    # FORBIDDEN list, scrub regexes, and doc strings). Scanning it would be a
    # guaranteed false positive, so it is excluded -- the scrub target is the
    # payload (env/benchmark/data/docs), not the assembler that names the rules.
    skip = {"build_release.py"}
    for root, _dirs, files in os.walk(dist):
        for fn in files:
            if fn in skip:
                continue
            path = os.path.join(root, fn)
            try:
                with open(path, "r", encoding="utf-8", errors="ignore") as f:
                    text = f.read()
            except Exception:                                  # noqa: BLE001
                continue
            for pat in FORBIDDEN:
                if re.search(pat, text):
                    findings[pat].append(os.path.relpath(path, dist))
    return findings


# ---- rendered documents ---------------------------------------------------
def render_license():
    return (
        "LICENSE -- PLACEHOLDER\n"
        "======================\n\n"
        "The license for the circuit-repro `engineer` environment + benchmark\n"
        "is TO BE DETERMINED at publish time. This placeholder is intentional:\n"
        "per the E-5 packaging ruling (2026-08-16), the license decision is\n"
        "deferred and is NOT made by the release-assembly step.\n\n"
        "No grant of rights is made by this file. Do not treat the presence of\n"
        "this file as a license. Until a real license is chosen and committed,\n"
        "the code is under default copyright.\n\n"
        "Note on upstreams: the environment depends at runtime on third-party\n"
        "repositories with their own licenses (AnalogGym BSD-3-Clause, ZOAF MIT,\n"
        "AnalogGenie MIT, SKY130 PDK Apache-2.0). Two dependencies have UNKNOWN\n"
        "redistribution status (AutoCkt: no LICENSE file; the 45nm BSIM4 model\n"
        "card: no license header) and are NOT bundled -- see README_RELEASE.md\n"
        "and MANIFEST.md. VACASK (AGPL-3.0) is out of scope and not bundled.\n"
    )


def render_readme():
    return f'''# circuit-repro `engineer` -- environment + benchmark release

**Scope of this package (E-5 ruling, 2026-08-16): the environment and the
in-house benchmark only.** The dhruva/GNSS-balun LNA case study and the external
AnalogGym scoreboards are staged for a later release. Nothing here is frozen as
"v1.0" until the protocol freeze lands (see PROVENANCE).

## What this is

An **RF-grade agentic analog-design environment + benchmark + measured
baselines**, framed as in the founding charter (§1):

- **Environment** (`engineer/env.py`) -- a *budgeted, counted, observable,
  deterministic* interface onto a golden-validated ngspice harness. Searches,
  agents, and unattended loops run and are compared over it.
- **Benchmark** (`engineer/tasks.py`) -- a registry of 8 pinned tasks (7 scoring
  + 1 smoke), each pinned to the exact stored reference row its budget and
  numbers come from, with a compute-matched scoring protocol
  (`engineer/PROTOCOL.md`).
- **Measured baselines, including honest negatives.** The scoreboards ship the
  CMA-ES and random null arms; the memory (E-3) and unattended-loop (E-4)
  harnesses ship results that came out **negative** (memory: warm < cold on 7/7
  tasks; loop: 0/10 feasible) -- these are deliverables, not gaps. The field's
  failure mode is scaffolding without measurement; this line measured, and
  published the negatives.

## Dependencies (the version cliffs are real)

- **Python 3.11 + numpy** (scipy + pyyaml for the shared core). No installs
  beyond these for the in-house benchmark.
- **ngspice >= 42** -- **VERSION CLIFF**: the RF decks use the `sp` S-parameter
  analysis with `portnum`/`z0` ports. conda-forge's ngspice **41 segfaults** on
  that deck; **36 rejects `portnum` outright**. Build ngspice **47** from source
  (this line's reference), or provide a >= 42 binary. See `PORTING.md`.
- **The shared core `lna/`** (datastore, spec, size, extract, to_spice,
  topology, moves, null_sizer, playbook, ref/, specs/) -- lives on the
  circuit-repro **main** branch. The environment imports it at runtime. Fetch
  the main branch alongside this release; the env dep-shim walks up to find it,
  or set `$LNA_DEPS_ROOT`.
- **ZOAF** (MIT) at pinned SHA `62615e91` -- imported by `null_sizer`; fetch per
  `UPSTREAM.md`.

### Manual fetch: the 45 nm BSIM4 model card (license status UNKNOWN)

> The 45 nm BSIM4 process model card (`45nm_bulk.txt`) is **NOT bundled with
> this release and is NOT auto-fetched.** Its redistribution status is
> **unknown**: the file carries no license header (header line: `* BPTM 45nm
> NMOS`), and the AutoCkt repository it lives in has no LICENSE file. To run any
> evaluation you must fetch it yourself, manually, from the AutoCkt repo:
>
> - Repo: `ksettaluri6/AutoCkt` at pinned SHA `a6c8a61d`
> - Path in that repo:
>   `eval_engines/ngspice/ngspice_inputs/spice_models/45nm_bulk.txt`
> - Place the clone so the env dep-shim finds it (at `<repo>/AutoCkt/repo/...`),
>   or point `$LNA_DEPS_ROOT` at a tree that contains it.
>
> **License status: unknown.** BPTM cards were historically released by the UC
> Berkeley BSIM Group for open use, but this specific file states no license.
> Do not redistribute it without clarifying its provenance. The environment
> reads it at runtime only; nothing in this package copies it.

### Optional: VACASK (harmonic-balance cross-check) -- out of scope

VACASK is **AGPL-3.0** and is **not bundled**. It is used only for the `check_hb`
IIP3 cross-check (case-study material, a later release). To reproduce that
cross-check, build VACASK from source per `PORTING.md`; it is **not required** to
run the benchmark.

## Benchmark protocol

The scoring protocol is pre-registered in `engineer/PROTOCOL.md` (committed alone
before any scoring run; the `§EXT` appendix committed alone before any external
cell ran -- the commit ordering is the pre-registration timestamp). The registry
pins are in `engineer/tasks.py` and mirrored, for offline listing, in
`engineer/tasks_registry_v0.json`.

## Reproduction commands

```bash
# 0) list the benchmark registry -- works WITHOUT lna/ or the model card:
python engineer/tasks.py --list
python engineer/tasks.py --list --long

# --- everything below needs the shared core (lna/) AND the manual 45 nm card ---

# 1) re-derive the registry pins against the live store (needs lna/data):
python engineer/tasks.py --check

# 2) the end-to-end smoke (150 evals, ~300 ngspice calls, lands infeasible):
python engineer/baseline_run.py

# 3) the in-house scoreboard (7 tasks x 2 arms x N seeds):
python engineer/score_run.py

# 4) the memory paired harness (E-3, warm vs cold):
python engineer/memory_harness.py

# 5) the unattended loop pilot (E-4):
python engineer/loop_run.py

# 6) API-hardening tests:
python engineer/test_env.py
```

## What a stranger can do WITHOUT the manual fetches

- `python engineer/tasks.py --list[/--long]` -- the full benchmark registry,
  from the shipped `tasks_registry_v0.json`.
- Read every shipped scoreboard/golden JSON and every doc (PROTOCOL, E3/E4,
  EXT-CALIBRATION, E5-PACKAGING, MANIFEST).
- Inspect all source.

## What a stranger canNOT do WITHOUT the manual fetches

- Run ANY evaluation (`baseline_run`, `random_run`, `score_run`,
  `memory_harness`, `loop_run`, `test_env`, `ext_*`). All route through
  `env._bind_runtime_deps()`, which requires `lna/` + ZOAF + the 45 nm card. The
  shim **fails loudly** when a dep is missing (by design).
- `tasks.py --check` (needs the live `lna/data/topo_labels.jsonl`).

## PROVENANCE

- **Era stamps.** Every benchmark reference row carries an `era` field.
  `current` means the row was produced after the 2026-08-10 multi-finger cutover
  (`w_finger == 2e-6`). FINDINGS §43.1 measured 1,109/1,215 stored designs
  era-stale on >= 1 metric -- an era stamp is the difference between a reference
  number and a number from a simulator that no longer exists.
- **Replay fences.** Goldens (`ext_golden_v0.json`, `ext_ldo_golden_v0.json`)
  record in-process AND separate-process replay reps so a stranger can confirm
  determinism (spread 0.000000 on the anchor).
- **Pre-registration.** PROTOCOL.md and its §EXT appendix were each committed
  ALONE before the runs they govern; scoreboard artifacts stamp the
  pre-registration SHA. This ordering is in git history -- ship the history, not
  just a snapshot, to preserve it.
- **"Frozen v1.0"** means: once the user rules the protocol freeze, the frozen
  commit SHA becomes the cited benchmark version; the null scoreboards at that
  commit become the fixed reference future arms compete against. **As of this
  package the protocol is NOT frozen** -- these are real measurements under the
  working protocol, citable by their pre-registration SHAs, not yet locked.

## License

See `LICENSE` -- a **placeholder**: the license is **TBD at publish time** per
the E-5 ruling. No rights are granted by this package yet.

## The honest boundary

`MANIFEST.md` lists every shipped file with its sha256 and the exclusions (raw
per-cell JSONs, trajectories, VACASK, the 45 nm model card, `lna/` internals,
the case study) with the reason each is out.
'''


def render_manifest(manifest, notes):
    lines = []
    lines.append("# MANIFEST -- engineer env+benchmark release\n")
    lines.append("Assembled by `engineer/release/build_release.py` from the live "
                 f"circuit-repro `engineer` branch at git `{git_sha(ENGINEER)}`.\n")
    lines.append("Scope: environment + benchmark ONLY (case study staged later). "
                 "License placeholder (TBD at publish). 45 nm model card NOT "
                 "bundled (manual fetch, license unknown). VACASK out (AGPL). "
                 "Data = aggregated scoreboards + goldens only.\n")
    lines.append("## Files in the assembled tree\n")
    lines.append("| path in package | source (relative to repo root) | sha256 | note |")
    lines.append("|---|---|---|---|")
    for rel, src, sha, note in sorted(manifest):
        lines.append(f"| `{rel}` | `{src}` | `{sha}` | {note} |")
    lines.append(f"\n**{len(manifest)} files** in the assembled tree.\n")
    lines.append("## Build notes\n")
    for n in notes:
        lines.append(f"- {n}")
    lines.append("\n## Exclusions -- what is NOT in this package, and why\n")
    for item, why in EXCLUSIONS:
        lines.append(f"- **{item}** -- {why}")
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    default_dist = os.path.join(os.environ.get("SCRATCH",
                    os.environ.get("TMPDIR", "/tmp")), "engineer_release", "dist")
    ap.add_argument("--dist", default=default_dist,
                    help="output dist/ dir (default: $SCRATCH/engineer_release/dist)")
    ap.add_argument("--clean", action="store_true",
                    help="remove the dist dir first")
    ap.add_argument("--emit-source-docs", action="store_true",
                    help="also write the canonical README_RELEASE.md / LICENSE "
                         "/ MANIFEST.md into engineer/release/ (the committed copies)")
    a = ap.parse_args()
    if a.clean and os.path.isdir(a.dist):
        shutil.rmtree(a.dist)
    dist, manifest, notes, findings = build(a.dist,
                                            emit_source_docs=a.emit_source_docs)

    print(f"assembled -> {dist}")
    print(f"  {len(manifest)} files")
    for n in notes:
        print(f"  note: {n}")
    print("scrub verification (forbidden-pattern grep counts, want 0):")
    ok = True
    for pat, hits in findings.items():
        print(f"  {pat!r}: {len(hits)}" + (f"  {hits}" if hits else ""))
        if hits:
            ok = False
    print("scrub: " + ("CLEAN" if ok else "DIRTY -- FIX BEFORE RELEASE"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
