"""_gen_ladder.py -- emit the capability-v0 experimental spec ladder.

Run once to (re)generate the 24 `cap-<tier><nn>-<hint>.yaml` files and
`ladder.json` in this directory. The generated YAMLs are the committed
artefacts; this script is kept alongside them only to document exactly how the
numbers were derived (provenance, house rule -- no magic constants).

EXPERIMENTAL / capability-v0. NONE of these specs is frozen protocol. Adoption
or freezing of any target is a USER RULING (memory: circuit-repro-governance).

Calibration policy (brief + G0-FAIRNESS "calibrations.allowed:never"): every
number is a round, published-practice figure or a relaxed/tightened step off the
three real bring-up specs -- wifi24 (2.4 GHz), ism58 (5.8 GHz), gps-l1
(1.575 GHz) -- NOT read off this pipeline's behaviour. device_budget / l_min /
l_max / sizing ranges are COPIED verbatim from those specs per band.

Grading axes (loose -> tight), per the brief:
    band     0.9 / 1.575 / 2.4 / 3.5 / 5.8 GHz narrowband + 2 wideband
    NF max   3.5 -> 1.5 dB
    S11 max  -8 -> -15 dB
    S21 min  10 -> 20 dB
    Idd max  15 -> 5 mA

Tiers:
    E (8) loose everything -- the sanity floor (should be broadly clearable)
    M (8) realistic commercial-ish middle
    H (8) tight combinations (low NF + tight match + low power at once),
          incl. one 5.8 GHz-tight and one wideband with band-wide S11.

Exactly TWO wideband entries (brief): cap-e08 (loose) and cap-h08 (tight,
band-wide S11); both reuse the wideband screen (allow_inductorless true,
s11_max_db + s21_ripple_db band-wide). The other 22 are narrowband.

iip3_dbm is declared on EVERY spec with `status: unsupported` -- the schema
value that means MEASURED-BUT-NOT-GATED reporting is *not* what we want here:
`status: measured` would make spec.feasible() gate iip3 (and a missing metric
= violated). The campaign measures IIP3 post-sizing as an ADVISORY column via
verify.py regardless of this status, so `unsupported` keeps it un-gated in the
sizing loop while still declaring the target. (See spec.py D5/D5b + plans2/23.)
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# ---- per-band physical envelope, COPIED from the real specs -----------------
# (device_budget, l_min, l_max, max_inductors) -- verbatim off wifi24/gps-l1/
# ism58 by nearest band; sizing block is identical across all three real specs.
SIZING = {
    "w_um": [1, 200], "l_fixed": 45e-9, "r_ohm": [50, 20e3],
    "c_f": [50e-15, 10e-12], "vb_v": [0.2, 0.9],
}

# narrowband centres + guard band widths (round standards figures).
NB = {
    "0p9":  dict(f0=0.915e9,  f_lo=0.902e9,  f_hi=0.928e9,  hint="900mhz",
                 l_max=15e-9, max_ind=4),   # 900 MHz ISM; larger spirals (gps-like)
    "1p575": dict(f0=1.57542e9, f_lo=1.565e9, f_hi=1.586e9, hint="gpsband",
                 l_max=15e-9, max_ind=4),   # == gps-l1 band exactly
    "2p4":  dict(f0=2.442e9,  f_lo=2.400e9,  f_hi=2.4835e9, hint="wifi",
                 l_max=12e-9, max_ind=3),   # == wifi24 band exactly
    "3p5":  dict(f0=3.5e9,    f_lo=3.4e9,    f_hi=3.6e9,    hint="35ghz",
                 l_max=10e-9, max_ind=3),   # 3.5 GHz (interpolated wifi/ism)
    "5p8":  dict(f0=5.8e9,    f_lo=5.725e9,  f_hi=5.875e9,  hint="ism58",
                 l_max=8e-9,  max_ind=3),   # == ism58 band exactly
}
# wideband envelope == wideband-sdr's band (0.5-3 GHz), reusing the wideband
# screen (allow_inductorless true, s11_max_db / s21_ripple_db band-wide).
WB = dict(f0=1.75e9, f_lo=0.5e9, f_hi=3.0e9, l_max=10e-9, max_ind=1)

DEVICE_BUDGET = [3, 16]     # identical across wifi24 / ism58 / gps-l1
L_MIN = 0.3e-9              # identical across all three

HDR = (
    "# capability-v0 EXPERIMENTAL spec -- NOT frozen protocol.\n"
    "# Generated by kaggle/specs-ladder/_gen_ladder.py for the overnight\n"
    "# capability-estimate campaign (kaggle/CAMPAIGN-CAPABILITY-V0.md).\n"
    "# Adoption/freezing of any target here is a USER RULING (governance).\n"
    "# Numbers are round published-practice figures or relaxed/tightened steps\n"
    "# off wifi24 / ism58 / gps-l1; device_budget/l_min/l_max/sizing copied from\n"
    "# those real specs. iip3_dbm declared unsupported (advisory-only via\n"
    "# verify.py; NOT gated anywhere in this ladder). Tier: {tier}  ({tier_note})\n"
)

TIER_NOTE = {
    "e": "loose everything -- sanity floor",
    "m": "realistic commercial-ish middle",
    "h": "tight combination -- low NF + tight match + low power at once",
}


def _num(x):
    """YAML scalar: keep engineering floats in 1e-9 form, ints as ints."""
    if isinstance(x, float):
        # engineering notation, matching the real specs (e.g. 2.442e9, 3e-10),
        # not python's 2442000000.0 repr.
        return ("%g" % x)
    return str(x)


def _yaml_str(s):
    """Quote a scalar that YAML would otherwise mis-parse (colon-space, etc.)."""
    return '"%s"' % s.replace('"', '\\"')


def emit(spec_id, tier, name, desc, band, nb_key, cons, objs, topo, note):
    """Render one spec YAML string."""
    L = []
    L.append(HDR.format(tier=tier.upper(), tier_note=TIER_NOTE[tier]))
    L.append("# %s\n" % note)
    L.append("name: %s" % name)
    L.append("description: %s\n" % _yaml_str(desc))
    L.append("process:")
    L.append("  models: AutoCkt/repo/eval_engines/ngspice/ngspice_inputs/spice_models/45nm_bulk.txt")
    L.append("  vdd: 1.1")
    L.append("  temp: 27\n")
    L.append("band:")
    L.append("  type: %s" % band["type"])
    L.append("  f0: %s" % _num(band["f0"]))
    L.append("  f_lo: %s" % _num(band["f_lo"]))
    L.append("  f_hi: %s" % _num(band["f_hi"]))
    L.append("")
    L.append("ports:")
    L.append("  z0: 50")
    L.append("  input: VIN1")
    L.append("  output: VOUT1\n")
    L.append("constraints:")
    for k, v in cons:
        L.append("  %s" % _fmt_constraint(k, v))
    L.append("")
    L.append("objectives:")
    for o in objs:
        L.append("  - {metric: %s, direction: %s, weight: %s}"
                 % (o[0], o[1], o[2]))
    L.append("")
    L.append("topology:")
    L.append("  differential: false")
    L.append("  reject_floating: true")
    L.append("  device_budget: [%d, %d]" % (DEVICE_BUDGET[0], DEVICE_BUDGET[1]))
    if topo.get("allow_inductorless"):
        L.append("  allow_inductorless: true")
        L.append("  max_inductors: %d" % topo["max_ind"])
    else:
        L.append("  allow_inductorless: false")
        L.append("  max_inductors: %d" % topo["max_ind"])
    L.append("  l_min: %s" % _num(L_MIN))
    L.append("  l_max: %s" % _num(topo["l_max"]))
    L.append("")
    L.append("sizing:")
    L.append("  w_um: [1, 200]")
    L.append("  l_fixed: 45e-9")
    L.append("  r_ohm: [50, 20e3]")
    L.append("  c_f: [50e-15, 10e-12]")
    L.append("  vb_v: [0.2, 0.9]")
    return "\n".join(L) + "\n"


def _fmt_constraint(k, v):
    parts = []
    for lim in ("min", "max"):
        if lim in v:
            parts.append("%s: %s" % (lim, v[lim]))
    if "status" in v:
        parts.append("status: %s" % v["status"])
    return "%-12s {%s}" % (k + ":", ", ".join(parts))


# ---- the ladder --------------------------------------------------------------
# Each row: (spec_id, tier, nb_key|"wb", nf_max, s11_max, s21_min, idd_max,
#            iip3_min, note). iip3 is always unsupported.
LADDER = [
    # ===================================================== Tier E (sanity floor)
    ("cap-e01", "e", "2p4",   3.5, -8,  10, 15, -10,
     "Loosest WiFi-band target: everything relaxed one step below wifi24. The "
     "sanity floor -- if the loop cannot clear this, nothing downstream matters."),
    ("cap-e02", "e", "1p575", 3.5, -8,  10, 15, -10,
     "GPS band, all-loose. gps-l1 relaxed hard (NF 1.8->3.5, S21 15->10, Idd "
     "3->15): tests band handling without the noise-first squeeze."),
    ("cap-e03", "e", "0p9",   3.5, -8,  10, 15, -10,
     "900 MHz ISM, all-loose. Lowest band on the ladder; larger spirals "
     "(l_max 15 nH like gps-l1)."),
    ("cap-e04", "e", "3p5",   3.5, -8,  12, 15, -8,
     "3.5 GHz, loose. Interpolated wifi/ism band with a mild S21 bump to 12."),
    ("cap-e05", "e", "5p8",   3.5, -8,  10, 15, -8,
     "5.8 GHz, loose. ism58 band with NF/S21/Idd all relaxed -- isolates the "
     "high-band matching difficulty from the tight-spec difficulty."),
    ("cap-e06", "e", "2p4",   3.0, -10, 12, 12, -8,
     "WiFi, mild. One notch tighter than e01 toward wifi24's real numbers "
     "(NF 3.0, S11 -10, S21 12)."),
    ("cap-e07", "e", "1p575", 3.0, -10, 12, 10, -8,
     "GPS band, mild. Halfway between e02 and the real gps-l1 squeeze."),
    ("cap-e08", "e", "wb",    3.5, -8,  10, 15, 5,
     "Wideband 0.5-3 GHz, loosest. Reuses the wideband screen "
     "(allow_inductorless, band-wide S11/ripple) at relaxed thresholds; the "
     "inductorless-class sanity floor."),

    # ================================================= Tier M (commercial-ish)
    ("cap-m01", "m", "2p4",   2.5, -10, 12, 5,  -5,
     "wifi24 exactly (NF 2.5, S11 -10, S21 12, Idd 5). The reference "
     "commercial target as a mid-tier rung."),
    ("cap-m02", "m", "1p575", 2.2, -10, 14, 5,  -8,
     "GPS-ish, noise-leaning but not the full 1.8 dB squeeze. Between gps-l1 "
     "and wifi24."),
    ("cap-m03", "m", "0p9",   2.5, -10, 14, 6,  -5,
     "900 MHz commercial: WiFi-class NF with a bit more gain at the low band."),
    ("cap-m04", "m", "3p5",   2.8, -11, 14, 6,  -5,
     "3.5 GHz commercial. NF eased slightly vs 2.4 GHz (higher band), tighter "
     "match (-11)."),
    ("cap-m05", "m", "5p8",   3.5, -10, 12, 10, -8,
     "ism58 exactly (NF 3.5, S11 -10, S21 12, Idd 10). The real 5.8 GHz "
     "experimental-transfer target as a mid rung."),
    ("cap-m06", "m", "2p4",   2.2, -12, 15, 6,  -3,
     "WiFi, tighter match + gain. Pushes S11 to -12 and S21 to 15 while "
     "holding NF near wifi24."),
    ("cap-m07", "m", "1p575", 2.0, -12, 15, 4,  -6,
     "GPS, noise-first mid. NF 2.0 (approaching gps-l1's 1.8), gain 15, low "
     "power 4 mA."),
    ("cap-m08", "m", "5p8",   3.0, -11, 14, 8,  -6,
     "5.8 GHz commercial-tight. ism58's band with NF eased to 3.0 but match "
     "tightened to -11 and gain to 14 -- a second high-band mid rung distinct "
     "from m05, so the M tier still spans all five narrowband centres."),

    # ======================================================= Tier H (tight)
    ("cap-h01", "h", "2p4",   1.8, -13, 16, 4,  -3,
     "WiFi, tight. Low NF (1.8) + tight match (-13) + high gain (16) + low "
     "power (4) simultaneously."),
    ("cap-h02", "h", "1p575", 1.8, -12, 16, 3,  -6,
     "gps-l1 tightened: its NF 1.8 / Idd 3 kept, but S11 -12 and S21 16 added "
     "-- the noise-first target with a match+gain squeeze on top."),
    ("cap-h03", "h", "0p9",   1.6, -13, 17, 4,  -3,
     "900 MHz, tight. Lowest NF at the low band with high gain and low power."),
    ("cap-h04", "h", "3p5",   1.8, -14, 17, 4,  -3,
     "3.5 GHz, tight. Tight match (-14) at a mid-high band with low NF."),
    ("cap-h05", "h", "5p8",   2.0, -13, 16, 5,  -3,
     "5.8 GHz TIGHT (brief-required). ism58's band with NF 2.0, S11 -13, S21 "
     "16, Idd 5 -- high-band matching difficulty stacked with a tight spec."),
    ("cap-h06", "h", "2p4",   1.5, -15, 18, 5,  0,
     "WiFi, hardest narrowband. NF 1.5 (the floor of the NF axis) + S11 -15 "
     "(the floor of the match axis) + S21 18 at once."),
    ("cap-h07", "h", "1p575", 1.5, -14, 20, 3,  -3,
     "GPS, extreme. NF 1.5 + S21 20 (the top of the gain axis) + Idd 3 -- the "
     "corner where noise, gain and power all bind."),
    ("cap-h08", "h", "wb",    2.5, -15, 16, 5,  3,
     "Wideband TIGHT with band-wide S11 (brief-required). 0.5-3 GHz, "
     "s11_max_db -15 across the whole band, ripple 1.5, NF 2.5, gain 16, 5 mA "
     "-- the inductorless hard corner."),
]


def build():
    manifest = []
    for spec_id, tier, band_key, nf, s11, s21, idd, iip3, note in LADDER:
        wideband = band_key == "wb"
        if wideband:
            b = dict(type="wideband", **{k: WB[k] for k in ("f0", "f_lo", "f_hi")})
            topo = dict(allow_inductorless=True, l_max=WB["l_max"],
                        max_ind=WB["max_ind"])
            hint = "wideband"
            # wideband uses band-wide S11 (s11_max_db) and adds a ripple cap,
            # matching wideband-sdr's schema.
            ripple = 1.5 if tier == "h" else 2.0
            cons = [
                ("nf_db", {"max": nf}),
                ("s11_max_db", {"max": s11}),
                ("s21_db", {"min": s21}),
                ("s21_ripple_db", {"max": ripple}),
                ("idd_ma", {"max": idd}),
                ("iip3_dbm", {"min": iip3, "status": "unsupported"}),
            ]
            objs = [("nf_db", "min", 1.0), ("s21_db", "max", 0.5),
                    ("idd_ma", "min", 0.5)]
        else:
            nbk = NB[band_key]
            b = dict(type="narrowband", f0=nbk["f0"], f_lo=nbk["f_lo"],
                     f_hi=nbk["f_hi"])
            topo = dict(allow_inductorless=False, l_max=nbk["l_max"],
                        max_ind=nbk["max_ind"])
            hint = nbk["hint"]
            cons = [
                ("nf_db", {"max": nf}),
                ("s11_db", {"max": s11}),
                ("s21_db", {"min": s21}),
                ("idd_ma", {"max": idd}),
                ("iip3_dbm", {"min": iip3, "status": "unsupported"}),
            ]
            # noise-first objective ordering when NF is the binding (tight) axis
            if nf <= 1.8:
                objs = [("nf_db", "min", 1.0), ("s21_db", "max", 0.5),
                        ("idd_ma", "min", 0.5)]
            else:
                objs = [("s21_db", "max", 1.0), ("nf_db", "min", 0.5),
                        ("idd_ma", "min", 0.5)]

        fname = "%s-%s.yaml" % (spec_id, hint)
        name = "%s-%s" % (spec_id, hint)          # spec.name (unique)
        band_lbl = "wideband 0.5-3 GHz" if wideband else (
            "%.3g GHz" % (b["f0"] / 1e9))
        desc = ("capability-v0 %s tier: %s LNA (NF<=%s S11%s%s S21>=%s Idd<=%s)"
                % (tier.upper(), band_lbl, nf,
                   "_max<=" if wideband else "<=", s11, s21, idd))
        text = emit(spec_id, tier, name, desc, b, band_key, cons, objs, topo, note)
        with open(os.path.join(HERE, fname), "w", encoding="utf-8") as fh:
            fh.write(text)
        manifest.append({
            "tier": tier.upper(), "spec_id": spec_id, "name": name,
            "file": fname, "band": band_lbl,
            "band_type": b["type"],
            "nf_max_db": nf, "s11_max_db": s11, "s21_min_db": s21,
            "idd_max_ma": idd, "iip3_min_dbm_advisory": iip3,
            "notes": note,
        })
    with open(os.path.join(HERE, "ladder.json"), "w", encoding="utf-8") as fh:
        json.dump({
            "campaign": "capability-v0",
            "experimental": True,
            "frozen": False,
            "doc": "kaggle/CAMPAIGN-CAPABILITY-V0.md",
            "axes": {
                "band_ghz": [0.9, 1.575, 2.4, 3.5, 5.8, "wideband 0.5-3"],
                "nf_max_db": [3.5, 1.5], "s11_max_db": [-8, -15],
                "s21_min_db": [10, 20], "idd_max_ma": [15, 5],
            },
            "iip3_policy": "declared unsupported; measured post-sizing as an "
                           "ADVISORY column via kaggle/loop/verify.py; NOT gated.",
            "specs": manifest,
        }, fh, indent=2)
        fh.write("\n")
    return manifest


if __name__ == "__main__":
    m = build()
    print("wrote %d spec YAMLs + ladder.json to %s" % (len(m), HERE))
    for r in m:
        print("  %-3s %-22s %-16s NF<=%-4s S11<=%-4s S21>=%-3s Idd<=%-3s"
              % (r["tier"], r["file"], r["band"], r["nf_max_db"],
                 r["s11_max_db"], r["s21_min_db"], r["idd_max_ma"]))
